### ISSUE TITLE
Initial openedX deployment

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#1]
We need an initial deployment of openedX to an RC environment for our first milestone. The setup for this should be similar to how we did it for xPro

- Hardcoded Openedx configuration
- Install `social_auth mitxpro` (this isn't specific to xpro, it's just named as such because that was our sole use case when implementing)
- Install `mitxpro_openedx_extensions`

**Comment by blarghmatey** [comment]
This is currently deployed to lms-qa.mitxonline.mit.edu
