### ISSUE TITLE
Before Launch: Permission Error when running RC tested BI reports with Prod data

### ISSUE THREAD

**Issue by dseaton** [mitodl/mitxonline#1001]
### Steps to Reproduce
In preparation for the MITx Online launch, I have created two reports that work with RC data, but fail with the following error when used with Prod data. `permission denied for table courses_courseruncertificate`

Report in question set to use RC data:
* Purchase Reconciliation: https://bi.odl.mit.edu/queries/1163/source#2051
* Customer Support: https://bi.odl.mit.edu/queries/1171/source#2052

Failing Reports using Prod data:
* Purchase Reconciliation: https://bi.odl.mit.edu/queries/1190/source
* Customer Support: _use the Redash interface to select MITx Online Prod as the source for the query_. This method eliminates concerns about differences in the SQL between RC and Prod reports.

### Expected Behavior

I expect that these reports would work seamlessly, whether using RC or Prod as the source.

### Actual Behavior

In switching to MITx Online Prod as the data source, the report throws the following error:
`permission denied for table courses_courseruncertificate`

### Related Issues
https://github.com/mitodl/hq/issues/258
https://github.com/mitodl/hq/issues/258

**Comment by blarghmatey** [comment]
This appears to be working now as I'm not getting a permission error, though there is no data being displayed. My assumption is that the missing data is an artifact of having not run through the purchase flow in production yet.

**Comment by dseaton** [comment]
Great! You are correct in that 'transactions' and 'certificates' are not yet available, so the output is not complete compared to RC. Thanks for getting this working!
