### ISSUE TITLE
MM Data Migration: New instances of MicroMaster and MITxOnline production snapshot

### ISSUE THREAD

**Issue by rachellougee** [mitodl/mitxonline#1013]
In support of testing the MM data migration script with MicroMaster and MITxOnline production data, we need the following snapshot of _production_ databases

- MicroMaster
- MITxOnline

For the MITxOnline instance, 
- it needs to connect to MicroMaster as a foreign data wrapper, so we can run SELECT * FROM micromasters.TABLE_NAME on it.
- it needs a user with at least SELECT and INSERT privileges to all tables on it

The goal is to run `heroku run --app mitxonline python ./manage.py import_micromasters_data` against the production database instances. Or we could directly run queries on the new instance of MITxOnline as long as it has postgres_fdw configured to access the new instance of MicroMaster production as mentioned above

**Comment by rachellougee** [comment]
@rhysyngsun @pdpinch Per @blarghmatey, he could snapshot the production instances of MicroMaster and MITxOnline for us to test the migration script with production data. So we can verify if the imported data before running it on production

**Comment by blarghmatey** [comment]
I connected the `MITx Online Integration Test with Micromasters` data source to Redash which is an instance running from a snapshot of MITx Online production, connected via the foreign data wrapper to a snapshot of the Micromasters production database, both taken yesterday afternoon. I can also share connection info for interacting with it directly.
