### ISSUE TITLE
Bug: deactivating products on RC results in a 500 error

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#1024]
### Steps to Reproduce

See Sentry issue: https://sentry.io/organizations/mit-office-of-digital-learning/issues/3609909359/?alert_rule_id=8724694&alert_timestamp=1663787179172&alert_type=email&environment=rc&project=5864687&referrer=alert_email

1. On RC, use the admin to set the Is Active flag to false for a given product. 
2. Navigate to the course details page for the product's course.

### Expected Behavior

The course details page should render, minus the now-disabled upsell messaging.

### Actual Behavior

You get a 500 error. 

### Stacktrace

https://sentry.io/organizations/mit-office-of-digital-learning/issues/3609909359/?alert_rule_id=8724694&alert_timestamp=1663787179172&alert_type=email&environment=rc&project=5864687&referrer=alert_email

### Related Issues

Noticed this during a sanity check for https://github.com/mitodl/hq/discussions/227#discussioncomment-3702377 .

**Comment by arslanashraf7** [comment]
Closed via #1026
