### ISSUE TITLE
Refunds: rows that have been processed are "failing"

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#1033]
In the production worksheet the first row that's there is being marked as "failed" when you run the management command. This is probably related to some bad state that existed when the integration first ran. 

The data issue was that there was a blank row at the top which failed to process. To try and fix this I removed the row and updated the `RefundRequest` database records to delete the failed one for that row and also updated the `form_response_id` column to match what the spreadsheet was now reflecting (it had gone from `3` to `2` since i deleted that row).

I tried digging into it but it's a bit involved to figure this out. It should be just skipping the row since it has a completed date marked, but the fact that it's failing indicates it isn't.

**Comment by pdpinch** [comment]
Does the failing row still exist in the google sheet? How can you tell that it's failing?

**Comment by rhysyngsun** [comment]
@pdpinch if you run the management command it'll indicate that row 4 is failing

**Comment by jkachel** [comment]
Looked at this. The rows that are being indicated as failing currently (2-Nov) are ones that have been processed. This seems right, looking at the code - the order wouldn't be in the `FULFILLED` state anymore so it fails out in `ecommerce/api.py:refund_order`. Do we maybe want to skip these rows entirely? I have new code in https://github.com/mitodl/ol-django/pull/99 that can be amended to do this.

**Comment by pdpinch** [comment]
@jkachel do you think this can be closed now that https://github.com/mitodl/ol-django/pull/99 is merged?

**Comment by jkachel** [comment]
Yup, closing this.
