### ISSUE TITLE
As a staff member I want to be able to setup certificates for a program in the CMS

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1037]
Summary
---
Staff users need to be able to setup program certificates that learners earn when they pass enough certificates in a program. These are set up in the CMS in our xPRO implementations and we want to do a similar thing here. 

#### Prior Art

See xPro CMS page models: https://github.com/mitodl/mitxpro/blob/master/cms/models.py

#### acceptance criteria

- [ ] CMS:
    - [ ] CMS user can create a certificate page as a child of a program page, even if the program page is a draft 
    - [ ] The title of the certificate should be pre-populated with the name of the program, but the CMS user can override it
    - [ ] The CMS user can choose multiple signatories to include on the certificate
    - [ ] xPRO has fields for "institute text" and "partner logo." Do not include those at this time
- [ ] certificate template: 
    - [ ] template design similar to xPROs (at least for the first iteration) 
    - [ ] Dates on the certificate should be from the earliest start date of a course the learner earned a certificate for in the program, to the latest date they earned a certificate
    - [ ] the learner view of the certificate should include the same sharing options as the course certificate
    - [ ] anonymous view of the certificate should not include sharing options
    - [ ] all views should include "valid certificate id"
    - [ ] include screenshots for desktop & mobile in the PR

#### related issues

- [ ] #1038
- [ ] don't let search engines index certificates

**Comment by pdpinch** [comment]
@aliraza-abbasi what is the status of this?

**Comment by aliraza-abbasi** [comment]
> @aliraza-abbasi what is the status of this?

This issue is completed and merged. It can be closed now
