### ISSUE TITLE
program certificate data model

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1038]
#### Acceptance Criteria:

- [ ] similar in concept to the course certificate data model, and the xPRO implementation of program certificates
- [ ] like the course certificate data model, it should support versioning of the templates

#### related issues

- #1037
- #706

**Comment by pdpinch** [comment]
@aliraza-abbasi Can this be closed?

**Comment by aliraza-abbasi** [comment]
> @aliraza-abbasi Can this be closed?

issue #1037 is completed and merged to prod. If the issue #706 is completed then it can be closed
