### ISSUE TITLE
Program dashboard v2

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1040]
As a learner, I'd like to see:
- what programs I am enrolled in
- what courses make up those programs 
- what my status is in those courses 

#### Designs and Mockups

- [Program Details pane](https://projects.invisionapp.com/d/main?origin=v7#/projects/prototypes/21535972)
- [Course cards revisited](https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/469597997/preview?scrollOffset=46)

#### Acceptance Criteria:

- [ ] Add a Program tab to the dashboard
- [ ] When the program tab is clicked, display all the programs the user is enrolled in 
- [ ] When a program is clicked, open the program drawer (program detail pane) 
- [ ] The program drawer lists _all_ the courses in the program, with the learner's status
- [ ] learner statuses:
   - [ ] if the learner isn't enrolled at all, display the "Enroll Today" card extension (if the course is open for enrollment) 
   - [ ] if the learner is enrolled but hasn't paid, display the "Upgrade today" card extension (same as course dashboard) 
   - [ ] if the learner is enrolled in the certificate track, display the appropriate tag (with no call to action)
   - [ ] if the learner has passed the course display the "course passed" label
   - [ ] if the learner has a course certificate, display the "course certificate" link 
   - [ ] if the learner failed the course, go back to the "Enroll Today" card extension  (if the course is open for enrollment) 

#### Out of Scope

- Group the courses in the program detail pane according to required, elective, etc.

**Comment by jkachel** [comment]
Couple questions regarding mostly the Program Details pane mock:
- The red underline for active tab is the same red we use elsewhere (like on the Enroll buttons, etc.), correct? Assuming yes but there's not a view of this without a backdrop. 
- The dashboard seems slightly confused. Does My Courses work like the dashboard currently does (i.e., lists out all of your enrolled courses, regardless of program membership, but does not list out any programs)? That seems the most logical approach but the mockup has a program in it. 
- The program drawer is visible on the My Courses page. Also assuming that won't necessarily be the case? (This ties in a bit with the second item.)
