### ISSUE TITLE
When referring to a course in email, don't include the full course id

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1044]
courses in email should always be formatted as “<number> <title>”. 

In  this example of a refund email, it should be “Test101 
Engineering Test Course” 

![image](https://user-images.githubusercontent.com/430126/192004638-fff51157-490d-499b-a6f7-c27001e4b965.png)

**Comment by collinpreston** [comment]
@pdpinch I assume that a course referenced in the Flexible Price emails should also follow the described formatting?

**Comment by pdpinch** [comment]
> I assume that a course referenced in the Flexible Price emails should
also follow the described formatting?

yes
