### ISSUE TITLE
Upsell card displays negative values if the discount is greater than the purchase price of the course

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#1069]
### Steps to Reproduce

1. Configure a course with a low enough value so that the financial assistance discount will result in the course price being less than zero. 
2. Apply for and approve a financial assistance request for that course. 
3. Navigate to the course details page.
4. Click Enroll.

On RC, this can be tested with Test External Checkout Course - https://rc.mitxonline.mit.edu/courses/course-v1:MITx+CHECKOUT/ . 

### Expected Behavior

The price displayed should be the course price minus the discount, with a floor of $0.00. 

### Actual Behavior

The price displayed doesn't have a floor, so the price displayed may be less than $0. 

### Related Issues

Found while working through #1006 .

### Screenshot or Screencast

Post-approved flex pricing page:
![image](https://user-images.githubusercontent.com/945611/192870476-a78dea8b-012d-4881-9bb0-07ba31ad1cd7.png)

Upsell card with wrong price:
![image](https://user-images.githubusercontent.com/945611/192870515-de4c77a2-4d66-47b5-8899-a0bc65c5e985.png)

**Comment by pdpinch** [comment]
So far, it seems like everyone wants to use percent-off discounts for financial assistance. Can this happen with percent-off discounts?

**Comment by pdpinch** [comment]
Oh wait. I'm wrong. I'm going to delete my comment.

**Comment by arslanashraf7** [comment]
Closing via #1079
