### ISSUE TITLE
Upgrade deadlines in open edX keep reverting

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1073]
### Steps to Reproduce

1. Yesterday, I set the upgrade deadline on https://courses.mitxonline.mit.edu/admin/course_modes/coursemode/9/change/ to 2022-10-07. 
2. Today it is set to 2022-12-04 (a setting that it mistakenly had some time ago)

### Expected Behavior

- After setting a date for a course mode in open edX, it shouldn't change without an admin user changing it. 
- I am expecting mitxonline upgrade deadlines to sync periodically with the setting in open edX

### Actual Behavior

- The date keeps reverting on this record (some others too, but most recently this one)
- The ugprade deadline in mitxonline doesn't seem to be updating

**Comment by pdpinch** [comment]
@collinpreston this is a very strange bug, but I've confirmed over and over that it is happening. 

Can you review the sync settings for upgrade deadlines and let me know if it's possible that this is a bug with the sync code?

**Comment by collinpreston** [comment]
@pdpinch, yes I'll check this out now.

**Comment by pdpinch** [comment]
It happened again since yesterday! 

On https://courses.mitxonline.mit.edu/admin/course_modes/coursemode/9/change/ the upgrade deadline is 12/4/2022.

This is so bizarre & crazy-making

**Comment by pdpinch** [comment]
I haven't seen this happen again since Friday. 

Can you leave some notes here about what you found regarding course publish?

**Comment by collinpreston** [comment]
@pdpinch, I'm at a dead-end with each theory I had for how this might be occurring.

**Comment by pdpinch** [comment]
@collinpreston can this be closed?

**Comment by collinpreston** [comment]
We can finally close this!


![Image](https://user-images.githubusercontent.com/8311573/227313421-0282a8b1-1e93-4eef-bf65-7ed7a610aa4a.png)
