### ISSUE TITLE
tracking types of discounts 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1074]
As a member of the marketing team, I'd like to be able to filter financial reports on marketing discounts, so I can focus my analysis on the transactions where marketing coupons were used. 

As a member of the MITx team, I'd like to be able to filter on financial assistance discounts, so I can analyze and project how much it costs. 

in xPRO we have various coupon "types." These have proven helpful for filtering data in reports
https://github.com/mitodl/mitxpro/blob/2dfd014f70abf56b3bde856160ad5d2686bfa6d3/ecommerce/models.py#L506-L515

#### Acceptance Criteria:

- [ ] Attach a type to coupons. Suggested types: 
  1. marketing (sometimes called "B2C") 
  2. customer support (enrollment codes for medical issues, etc.) 
  3. flexible pricing / financial assistance 
  4. sales (sometimes called "B2B", for the future)
- [ ] #1427

**Comment by asadali145** [comment]
Removing the `On Hold` tag as it seems we can start working on this one as it is moved to TODO.

**Comment by asadali145** [comment]
As we are adding a new choice field that will also indicate whether a discount is for financial assistance or not. We will also need to remove the usages of the existing boolean field `for_flexible_pricing`. This includes writing a data migration and some refactoring to use the new field in place of `for_flexible_pricing`. 

@jkachel WDYT how we should approach replacing `for_flexible_pricing`? Should all this be a part of a single PR? Or should we create a separate ticket/PR for replacing the usages and creating a data migration?

We (me & @arslanashraf7) think that we should go with a single PR.

**Comment by asadali145** [comment]
> include the type in AR/Financial reports

@pdpinch What do I need to do for this? Sorry, but I do not know about these changes. Is this something that I need to work on?

**Comment by jkachel** [comment]
> @jkachel WDYT how we should approach replacing `for_flexible_pricing`? Should all this be a part of a single PR? Or should we create a separate ticket/PR for replacing the usages and creating a data migration?

I think this is fine to roll into the open PR, since it's all affecting the same parts of the code.

**Comment by pdpinch** [comment]
> > include the type in AR/Financial reports

> @pdpinch What do I need to do for this? Sorry, but I do not know about these changes. Is this something that I need to work on?

I opened a separate issue for this, and put it on hold. You can close this issue when #1390 is merged.
