### ISSUE TITLE
Performance: django admin for order editing is selecting all users

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#1086]
### Steps to Reproduce

This is most easily observed in production where we have a large enough number of users for it to manifest. View a particular order and note how slow it is to load.

### Expected Behavior

The page loads in a second or so.

### Actual Behavior

The page takes up to 10 seconds because it's querying for and rendering an html select of all users. See the screenshot.

We should probably make most/all fields on this page readonly because there's no reason for the data to be altered manually - if we did need to do something we'd implement a management command or a refine interface to do it.

### Screenshot or Screencast

![Screenshot from 2022-10-04 12-38-16](https://user-images.githubusercontent.com/28598/193877587-766de5eb-41ef-418a-95a8-b90b306780d2.png)

**Comment by asadali145** [comment]
Just FYI @rhysyngsun @rachellougee and to document,

Actions for an order are also disabled as a result of this ticket. Not sure if we need those or not. It throws 403 forbidden if we try to move using the action buttons.

<img width="1058" alt="Screenshot 2022-10-12 at 4 51 14 PM" src="https://user-images.githubusercontent.com/52656433/195335994-0cb7384e-db58-4c6b-823f-56e0beb9d666.png">
<img width="1394" alt="Screenshot 2022-10-12 at 4 53 36 PM" src="https://user-images.githubusercontent.com/52656433/195336033-004ac899-ab12-40ac-a660-5ca2331f681a.png">

**Comment by asadali145** [comment]
Got it! Thanks
