### ISSUE TITLE
management command to create verified enrollment

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1109]
As an admin I need to create verified enrollments sometimes: 
- to address customer support issues
- to test the system
- to enroll staff 

These verified enrollments need to be accounted for properly, so they should be created with an enrollment code.

Sometimes I need to do this after the `enrollment_end` date has passed, or the `upgrade_deadline` has passed. 

#### Acceptance Criteria:

- [ ] create a verified enrollment in mitxonline and in open edX 
- [ ] if possible, use a `-f` switch to force the creation after the `enrollment_end` date and after the `upgrade_deadline` date

**Comment by pdpinch** [comment]
This could be an addition to the existing create_enrollment management command

**Comment by aliraza-abbasi** [comment]
@pdpinch the `-f` switch should also create enrollment on edx after `enrollment_end` date?
I'm currently looking into OpenEdx if it supports enrollment after the enrollment end date

**Comment by pdpinch** [comment]
If it's easier to break this into two PRs I would be OK with that. The first one would create verified enrollments for courses that are open, and the second would be the `-f` switch for creating verified enrollments in courses that are closed. 

Regarding your approaches, I agree that #3 is best. Is it a REST API that could be used by mitxonline?

**Comment by aliraza-abbasi** [comment]
Sure, I'll raise the first PR without expired courses enrollment and after that, I'll make the follow-up PR to support expired courses enrollment. But before that, I want to confirm a few things.

- The `enrollment_code` that we pass in the command should be assumed to be already created and `raise` the `CommandError` if not created or do we have to create the `enrollment_code` on run time if it is not created?
- Should I need to verify the `DiscountProduct` relation or it is ok to use the `enrollment_code` even if there is no relation between the `product` and `enrollement_code`?
- Do I need to verify that the given `enrollment_code` should be 100% off or it should be the same amount as the product price, or not?
- If the given `enrollement_code` is expired can we use it through the command or not?

In current context the `enrollment_code` can be used with any `product` without `DiscountProduct` relation if it is not `for_flexible_pricing` if it is `for_flexible_pricing` then the `enrollement_code` requires a relation with `product` in DiscountProduct model

**Comment by aliraza-abbasi** [comment]
> Sure, I'll raise the first PR without expired courses enrollment and after that, I'll make the follow-up PR to support expired courses enrollment. But before that, I want to confirm one thing.
> 
>     * The `enrollment_code` that we pass as the command parameter should be assumed to be already created and `raise` the `CommandError` if not created or do we have to create the `enrollment_code` on run time if it is not created?
> 
>     * Should I need to verify the `DiscountProduct` relation or it is ok to use the `enrollment_code` even if there is no relation between the `product` and `enrollement_code`?
> 
>     * Do I need to create `Order`  `FulfilledOrder` and `Transaction` entries for verified enrollment via command?

I've tried step 3, but it's not working as I expected, my findings are listed below.
- Keywords
   - `URL`: `http://edxhost/support/enrollment/username_or_email`
   - `username_or_email`: the username or email of the student to whom you want to enroll in the course
   - `EnrollmentView`: `edx-platform/lms/djangoapps/support/views/enrollments.py:EnrollmentSupportListView`
   - `SupportStaffRole`: `edx-platform//common/djangoapps/student/roles.py:SupportStaffRole`
   - `CourseAccessRole`: `edx-platform/common/djangoapps/student/models.py:CourseAccessRole`
   - `GlobalStaffRole`: `is_staff=True` in User Model
- The `URL` (which points out to `EnrollmentView`) should be called out by a `SupportStaffRole` (Can be assigned to any user to a specific course using `CourseAccessRole` on edx) or by `GlobalStaffRole`.
- Whenever I tried to hit the `URL`, I got redirected to `Login URL`
- Initially, I was not able to understand why this is happening even though I was already sending the auth token
- Then I found that the `EnrollmentView` has `@login_required` decorator implemented in the permission check decorator.
- `@login_required` only works with browser requests and accepts CSRF token but not the auth token

What we can do here?
- We can go with the first or second approach which I think will not be much feasible
- We can make a fix on edx by creating an issue on openedx repo, The fixes I've in my mind are
    1. Edx follows the `http://edxhost/api/url` convention which accepts the auth token. We can make a new APIView to accept the auth token and this will also follow the `http://edxhost/api/url` convention. (this is an existing feature we just need it to accept the auth token)
    2. Or we can make changes to the existing `EnrollmentView` just by adding the support of auth token
