### ISSUE TITLE
"Unknown error" occurs when completing a transaction

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#1116]
When purchasing a course _on production_, the system records an unknown error. The transaction succeeds, but the user is redirected back to the cart with an error message. It appears the transaction result is falling out the bottom of the `process_cybersource_payment_response` call. In looking at the transaction details in CyberSource, it seems like it's sending back a response status of `TRANSMITTED` - the code doesn't know what to do with that, so it displays the generic error message. It should handle this status and, additionally, it should log something when it hits this status so we can have some logs when/if this happens again. The `TRANSMITTED` state is code 100, which indicates that the transaction was successful; we should process this state like an accepted transaction. 

This may require a PR in the ol-django repo to add a constant for the `TRANSMITTED` status. 

I'm not 100% sure about this but CyberSource's ability to process webhooks may have some bearing on why this hasn't popped up on RC or in local instances. 

### Steps to Reproduce

1. Add a course to the cart and attempt to check out.
2. Complete the purchase process. (Payment method does not matter here - it fails with either PayPal or credit card transactions.)

### Expected Behavior

You are returned to the dashboard with a success message indicating the purchase was successful.

### Actual Behavior

You are returned to the cart with an error message. However, you have been enrolled in the course successfully - it will appear in your dashboard and you'll have a `verified` enrollment. 

### Related Issues

#1114 is probably related to this.

**Comment by pdpinch** [comment]
Here a screenshot from the ebc for a transaction in this state: 

![image](https://user-images.githubusercontent.com/430126/194935464-109009dc-03d3-471b-b617-3d7e71a57a1d.png)
