### ISSUE TITLE
No "Get Certificate" pop-up when clicking enroll button

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1127]
### Steps to Reproduce

1. go to https://mitxonline.mit.edu/courses/course-v1:MITxT+8.01.3x/ 
2. Click Enroll

### Expected Behavior

- Since the course has a product, with a $49 price, I expect to get the "get certificate" pop-up, where I can choose to enroll for free, or pay for the certificate. 

### Actual Behavior

- I'm immediately enrolled, as an auditor.

**Comment by collinpreston** [comment]
This was caused to the `content type` being marked as "courses | program run" instead of "courses | course run".
