### ISSUE TITLE
Customer support discount enrollment codes for future course runs

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1139]
As a customer supporter, I'd like to have (small) pools of coupons for a course, so I can offer it to users who have paid but can't complete the course. 

This is most common with DEDP, for example this request for JPAL102x: [ZenDesk 137496](https://odl.zendesk.com/agent/tickets/137496)

#### Acceptance Criteria:

- [ ] a short list of enrollment codes that can be drawn down over time
- [ ] that expire in two years
- [ ] for simplicity, it would be good if they were good for any course run within the expiration period. If that's too hard, CS will just have to manage them more carefully

**Comment by jkachel** [comment]
Created a management command to make these in #1142, then used it to generate 25 codes with `CS-` prefix for this purpose. These are all one-time use 100% off codes that expire on 2024-10-17. These got put into a Google Sheet in the shared drive for MITxOnline and sent explicitly to @pdpinch as well. I can rerun this at any time to add more codes as necessary (and the command offers a few other options too if we want to generate some for some other reason). 

For completeness, this was the command I ran:
```
heroku run -a mitxonline-production ./manage.py generate_discount_code --one-time --expires 2024-10-17 --amount 100 --discount-type percent-off --prefix CS- --count 25
```

**Comment by jkachel** [comment]
Closing this - has been done for a bit now.
