### ISSUE TITLE
add currency converstion for Jamaican dollar

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1140]
Not sure why it isn't on the list. Hopefully it's supported by the API. 

I haven't checked to see if we had it in MicroMasters. 

re: https://odl.zendesk.com/agent/tickets/138075

**Comment by asadali145** [comment]
The Jamaican Dollar seems to be supported by the API as can be checked from the SS. It is there on RC but I am not sure about production. I do not have access to production and zendesk.


![Image](https://user-images.githubusercontent.com/52656433/196157967-2555ee90-b3f9-4402-858e-dd9f566d2ee9.png)

![Image](https://user-images.githubusercontent.com/52656433/196157968-2955d563-9721-4068-b946-4ae2a062d41f.png)

**Comment by asadali145** [comment]
Hey @pdpinch, The Zendesk ticket is invalid. The Jamaican dollar is there on the list.
<img width="1400" alt="Screenshot 2022-10-17 at 6 08 49 PM" src="https://user-images.githubusercontent.com/52656433/196185448-c8222126-b409-414c-ade7-04d60d4335f6.png">

**Comment by pdpinch** [comment]
not an issue
