### ISSUE TITLE
admin improvements for basketdiscount

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1143]
In production it can take a long time to load the admin page for a `basked` or a `basketdiscount`, presumably because they have drop down lists for foreign keys that have to load a large number of items. 

We should change these to raw fields so the entire list of users and discounts don't need to be loaded just to display the admin page for a single `basketdiscount`

**Comment by asadali145** [comment]
Additionally, I have also fixed the same in the following pages:

1. Basket Item
2. Discount Product
3. User Discount
4. Discount Redemption
