### ISSUE TITLE
get "self-paced" value from open edX Studio

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1155]
As an admin, I'd like mitxonline to determine whether a course is self-paced or not from studio so I'm not responsible for setting it in django admin. 

#### Acceptance Criteria:

- [x] Determine if there is a setting in studio for self-paced courses
- [x] Determine if there is an API in studio that exposes whether a course is self-paced
- [x] Update our edx-api-client to pull the self-paced setting 
- [x] Update mitxonline's course sync code to include the self-paced setting

**Comment by pdpinch** [comment]
The "Course Pacing" setting is part of the course schedule settings in Studio: 

![image](https://user-images.githubusercontent.com/430126/196546910-aec80e2c-58f6-4aba-96bb-4347ed309d5c.png)

**Comment by arslanashraf7** [comment]
Update:

>Determine if there is an API in studio that exposes whether a course is self-paced

Going to check the box, Looking through edX APIs it looks like the [course details API](https://courses.edx.org/api-docs/#/courses/courses_v1_courses_read) would return the course pace too which we can use for this ticket.

**Comment by arslanashraf7** [comment]
Closed via https://github.com/mitodl/edx-api-client/pull/93 & #1158
