### ISSUE TITLE
PaidCourseRun for legacy orders

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#1167]
We've brought over legacy micromasters order data but one thing we've missed is populating `PaidCourseRun` based on this data.

Since we'll need this for any new data, it probably makes sense to update our existing scripts.

**Comment by rhysyngsun** [comment]
> Yes, we do have an existing migration script 0013_backfill_paid_courserun.py, we can just re-use it to backfill PaidCourseRun

We can't reuse that exact migration because ti's already been run, but you can definitely reuse the code elsewhere.

**Comment by rachellougee** [comment]
Yes, that's what I meant by reuse, not exactly the same script
