### ISSUE TITLE
open edX: inconsistent headers and footers

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1182]
### Steps to Reproduce

Compare: 

1. Learning MFE header and footer: 
    1. https://courses.mitxonline.mit.edu/learn/course/course-v1:MITx+Jace.101x+1T2022/home 
    2. Courseware (learning MFE) : https://courses.mitxonline.mit.edu/learn/course/course-v1:MITx+Jace.101x+1T2022/block-v1:MITx+Jace.101x+1T2022+type@sequential+block@265b12714970424ba141feeb4fcc8cac/block-v1:MITx+Jace.101x+1T2022+type@vertical+block@9dec004fe2f14e47936d45e6f3f8be96

![image](https://github.mit.edu/storage/user/19530/files/f797f800-343b-11ed-9b97-8e6fbbbfad87)
![image](https://github.mit.edu/storage/user/19530/files/16968a00-343c-11ed-9a43-e8ce46aa6034)

2. Discussion page header and footer (part of mitxonline theme?): 
    1. https://courses.mitxonline.mit.edu/courses/course-v1:MITx+Jace.101x+1T2022/discussion/forum/

![image](https://github.mit.edu/storage/user/19530/files/cc61d880-343c-11ed-98fb-a55d63cc84eb)
![image](https://github.mit.edu/storage/user/19530/files/f0bdb500-343c-11ed-8843-3b95645a14ad)

4. mitxonline-theme on most other pages : 
    5.  Progress page: https://courses.mitxonline.mit.edu/courses/course-v1:MITx+Jace.101x+1T2022/progress
    6.  Discussion: https://courses.mitxonline.mit.edu/courses/course-v1:MITx+Jace.101x+1T2022/discussion/forum/
    7.  Teams: https://courses.mitxonline.mit.edu/courses/course-v1:MITx+Jace.101x+1T2022/teams/#browse
    8.  Wiki: https://courses.mitxonline.mit.edu/courses/course-v1:MITx+Jace.101x+1T2022/wiki/MITx.Jace.101x.1T2022/
    9. Custom Tab: https://courses.mitxonline.mit.edu/courses/course-v1:MITx+Jace.101x+1T2022/1237ff7e91ee48e6b416b4ef460e322f/
   10. Textbook: https://courses.mitxonline.mit.edu/courses/course-v1:MITx+Jace.101x+1T2022/pdfbook/0/

![image](https://github.mit.edu/storage/user/19530/files/cc61d880-343c-11ed-98fb-a55d63cc84eb)
![image](https://github.mit.edu/storage/user/19530/files/177beb80-343d-11ed-945f-b8fcf87ba8c8)

### Expected Behavior

All of the templates should match the courseware template (i.e. the learning MFE) 

### Related Issue 

- open edX user menus don't match mitxonline user menus

**Comment by asadali145** [comment]
Leaving some thoughts here.
1. Footer:
  - PR to fix the footer is created in ol-infrastructure https://github.com/mitodl/ol-infrastructure/pull/1203. 
2. Header:
  - The header in the legacy site has 2 links `Sysadmin` and `Catalog`. Both are added through the mitxonline-theme https://github.com/mitodl/mitxonline-theme/blob/main/lms/templates/header/navbar-authenticated.html#L81.
  - To make the header consistent with the Learning MFE, we can either remove these from the legacy site or we can add them in MFE. To add these links in the MFE, we will need to see if it supports this behavior with some configs or not.
