### ISSUE TITLE
pool of 50 discount coupons for alumni

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1189]
As an alum, I've been promised a 15% off coupon for MITx courses. 

As a member of the alumni association, I would like to issue 15% off coupons to alumni who ask for them. 

#### acceptance criteria

- [ ] 50 coupons
- [ ] coupon name format: `MITALUM15-` followed by a random string 
- [ ] single use

**Comment by pdpinch** [comment]
There is some concern here about coupon re-use. Can the coupon be limited to a single use, but for any product?

Alternately, can the coupon be limited to users with a @alum.mit.edu email address?

**Comment by jkachel** [comment]
Coupons can be single-use. We can't limit them by email address in that way, though. 

Do you have a preference for the prefix for the code? My thought was to prefix with `alum-` but if there's something specific they should have (or if they shouldn't have a prefix at all), I can do that too.

**Comment by pdpinch** [comment]
I updated the description to clarify the requirements and share the requested prefix.

**Comment by jkachel** [comment]
Ok, cool. I've generated the codes and put them into a Google sheet (which I've sent a link to in Slack; it's in a pretty normal place in the OL Engineering shared drive).
