### ISSUE TITLE
Configure Fastly to serve uploaded images from /media

### ISSUE THREAD

**Issue by gsidebo** [mitodl/mitxonline#12]
_Related to #11_ 

PR #11 adds Wagtail to the app. In order to serve Wagtail-uploaded images, we want to configure our cloud provider so that requests to `/media/.*` will serve uploaded files that are stored in our S3 buckets.

**NOTE:** In xPro, uploaded images are not currently stored within a `/media/` directory

_Background detail:_

We've had a lot of trouble with the performance of the Wagtail view that serves images, so at least to start out, we're going to avoid that view entirely. Wagtail stores uploaded files using the storage backend configured for Django, which in deployed environments is an S3 bucket. We can bypass using any kind view in Python to serve these images by just using simple `img` tags and prefixing the `src` path with the `MEDIA_URL` Django setting, which right now is hardcoded to `/media/`.

**Comment by blarghmatey** [comment]
This has been deployed for QA and will be matched as we move to production.

**Comment by blarghmatey** [comment]
This is deployed in production now as well.
