### ISSUE TITLE
Add learner program records

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#1208]
As a learner on MITx Online, I'd like to be able to access a record of my progress through a program I'm enrolled in, similar to how I can do this in MicroMasters. 

This will be cross-porting the Program Record functionality from MicroMasters to MITx Online, including these features:
- Overview of the learner's progress through the courses in the program
- Sharing a copy of the record directly to a partner institution
- Generating a revokable link to view the record that can be shared by the learner

The first attempt at this will lean heavily on the MicroMasters look and feel (for the record-specific parts); it is expected that the design team will have a MITx Online-specific design in the future.

#### Designs and Mockups

See the Program Record in MicroMasters:
![image](https://user-images.githubusercontent.com/945611/201734546-df58fa9a-0013-4e85-9b7b-0664abb8c42d.png)

#### Acceptance Criteria:

- [ ] The program record is accessible through the dashboard
- [ ] The dashboard link is hidden behind a toggle (feature flag and URL param; like was done for the program UI) so it isn't viewable by the public until it has been reviewed
- [ ] The program record displays the program name and a tag indicating the overall progress the learner has made (Partially Completed or Completed)
- [ ] It displays the learner's name, username and email
- [ ] It displays each course in the program, with a tag for its status (core/required or elective) in the program, along with the course ID, grade earned, verified attempts, certificate date earned, and certificate status for the learner
- [ ] It allows record sharing as a whole to be toggled on or off
- [ ] Once record sharing is allowed, it allows records to be sent to a partner institution (which then cannot be revoked)
- [ ] Once record sharing is allowed, it allows a shareable link to be generated to allow an unauthenticated users to view the learner's record. This link should not be available before the learner activates it and should be deactivated if the learner revokes record sharing. 

#### Out of Scope

- Not sure just yet

**Comment by pdpinch** [comment]
Does this include a feature flag, for controlling the appearance of the link on the dashboard?

**Comment by jkachel** [comment]
Yes, will update the reqs
