### ISSUE TITLE
Can not create a program from django admin

### ISSUE THREAD

**Issue by annagav** [mitodl/mitxonline#1224]
### Steps to Reproduce

Go to /admin/courses/program/add/ and try to create a program

### Expected Behavior

successfuly create a program

### Actual Behavior
Throws an error 
```
ValueError at /admin/courses/program/add/
save() prohibited to prevent data loss due to unsaved related object 'program'.
```

**Comment by pdpinch** [comment]
@rhysyngsun @annagav is this still an issue?

**Comment by jkachel** [comment]
Can confirm that this is still a problem - I've been creating them in a Django shell as a workaround.

**Comment by pdpinch** [comment]
@rhysyngsun I'm going to take you off this, so someone else can work on it. Let me know if that's an issue. 

I'd like to be able to make a test program on RC soon-ish, for DEDP 2, the US version.

**Comment by annagav** [comment]
I think this was fixed in https://github.com/mitodl/mitxonline/pull/1477

**Comment by asadali145** [comment]
Yeah, Sorry I missed assigning myself as I came to know about this ticket after my PR.

**Comment by asadali145** [comment]
Fixed with the linked PR.
