### ISSUE TITLE
Create 2023 DEDP courses on RC for testing

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1235]
As a developer, I'd like a robust and representative testing environment on RC. 

In production, there are 7 DEDP courseruns scheduled for 2023. There are only two on RC. The necessary course runs should already existing on studio-qa.mitxonline.mit.edu but they don't have courserun records.

#### Acceptance Criteria:

- [ ] Follow the necessary steps (7-9) in https://github.com/mitodl/hq/discussions/306 to create the course runs
- [ ] update the [discussion](https://github.com/mitodl/hq/discussions/306) with suggestions on streamlining and automating the process

**Comment by jkachel** [comment]
Looking at this but I think I need some clarification - there are only 3 "2023" courses in Studio on RC:
- 14.740x (twice; one's MITx and one's MITxT)
- 14.009x

Do the remaining courses need to be created in Studio on RC as well? They're definitely there in production so I can just export them from there and import them into RC - really just want to make sure I won't be intruding on any other process before I do it.

**Comment by pdpinch** [comment]
There should be 5 for 1T2023. I created the missing ones by clicking the "rerun" in studio for the missing ones. Then I set the dates [based on this sheet](https://docs.google.com/spreadsheets/d/1FGJPXhuWUGs-YPj2HFEYaQK4Sf7lO2oYf0V0ycKYjfY/edit#gid=0).

course-v1:MITxT+14.310x+1T2023
course-v1:MITxT+14.73x+1T2023
course-v1:MITxT+14.740x+1T2023
course-v1:MITxT+JPAL102x+1T2023
course-v1:MITx+14.750x+1T2023
