### ISSUE TITLE
Update course_mode records in edX MySQL database

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mitxonline#1236]
This PR (https://github.com/openedx/edx-platform/pull/31289) has not been getting much attention and may remain open for some time which means that whenever someone makes an update to a course through edX Studio, the course_mode upgrade_deadline will revert to being 10 days before the course's end date.
We can fix these course_modes from reverting by setting `expiration_datetime_is_explicit` to `True` for any `course_mode` where the `upgrade_deadline` is not `null` and is more than 10 days before the course's end date.

**Comment by pdpinch** [comment]
Can that be set in the admin, or do we need shell access?

**Comment by collinpreston** [comment]
@pdpinch, we will need shell access.  My PR https://github.com/openedx/edx-platform/pull/31289 adds the ability to define this value through the admin screen.

**Comment by Ardiea** [comment]
Ran these updates in RC and Production for Collin 👍 

```
MariaDB [(none)]> UPDATE edxapp.course_modes_coursemode cm
    -> INNER JOIN edxapp.course_overviews_courseoverview co ON
    -> cm.course_id = co.id
    -> SET cm.expiration_datetime_is_explicit=1
    -> WHERE cm.expiration_datetime IS NOT NULL and
    -> co.end IS NOT NULL and
    -> cm.expiration_datetime < DATE_SUB(co.end, interval 10 day);
Query OK, 10 rows affected (0.007 sec)
Rows matched: 10  Changed: 10  Warnings: 0

```

**Comment by collinpreston** [comment]
Marking this closed based on Mikes comment.  I will still periodically check for reverted course_mode upgrade_deadlines but this should lesson the work needed for:
