### ISSUE TITLE
program drawer for text program won't load

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1242]
### Steps to Reproduce

1. Enroll in a test course like https://rc.mitxonline.mit.edu/courses/course-v1:xOnline+test/
2. go to the dashboard, with the program feature turned on, i.e. https://rc.mitxonline.mit.edu/dashboard/?enable_programs
3. Click on the program card for "Test Program"

### Expected Behavior

- drawer opens for test program 

### Actual Behavior

- page goes blank
- type errors in console

### Stack trace

I think this is the corresponding sentry error: https://sentry.io/organizations/mit-office-of-digital-learning/issues/3780966252/?environment=rc&project=5864687&query=is%3Aunresolved&referrer=issue-stream

### Screenshot or Screencast

<img width="1692" alt="image" src="https://user-images.githubusercontent.com/430126/205097958-e9f08b73-3acc-40ee-bf42-f639da74489d.png">

**Comment by pdpinch** [comment]
> My thoughts on this are we log an error message and then only display courses that are set up in the requirements tree, 

I most agree. The error needs to be pretty loud because this is a configuration issue that needs to be fixed. 

> unless the tree is empty 

I think we should validate somehow on empty trees and require them. We only have one program in production currently, and it absolutely needs a requirements tree.

**Comment by jkachel** [comment]
Some thoughts regarding the implementation in #1244:

* The validation check function will pump out some error messages that should be easy to identify if they pop up in Sentry. 
* I added a Celery task and a management command but I _didn't_ add validation to the program save in Django Admin. My thought here is that you're not naturally going to go to Programs there unless you're there to add a program (and at that point (a) there's no courses in the program to validate against and (b) the admin will create an empty tree by default, which is fine if there's no courses). I think it'd be somewhat easy to add to the program but maybe there should be a check when you save the program too? Ultimately it might be best to add some UI in (somewhere, either in Django Admin if possible or in the staff dashboard) to let you create courses or assign courses to the program while you're working with the program record. EIther way, the Celery task will catch it (if it's a live program) when it runs at 3AM.
