### ISSUE TITLE
Program card update

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1250]
#### Designs and Mockups

Based on https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/470593814/comments/149902381 but not everything is there yet. 

#### Acceptance Criteria:

- [ ] Remove the program id from the card. Users don't recognize program ids, like program-v1:MITx+DEDP 
- [ ] Link to program certificate if one exists. There's no design yet, but we could follow the approach taken for course certificate links on course cards. 

#### Related issues

- Allow user to unenroll from a program

**Comment by jkachel** [comment]
PR #1274 removes the ID - the certificate functionality appears to work fine, though; I set up a signatory and a certificate page for a program locally, then gave myself a cert, and the View Certificate link appeared as per usual and displayed a program certificate.
