### ISSUE TITLE
unenroll from program 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1251]
As a learner who is enrolled in a course that is part of a program, I might not want to be enrolled in the program and I need a way to unenroll. 

#### Designs and Mockups

https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/470593814/comments

#### Acceptance Criteria:

- [ ] Show a menu when the user clicks on the ⋮ menu on the program card
  - currently, the only item is "unenroll from program" 
- [ ] Make sure the menu is accessible
- [ ] display a "are you sure" dialog (design coming, but probably similar to https://github.com/mitodl/mitxonline/issues/1078)

#### Related Issues

- #1250

**Comment by jkachel** [comment]
One thing: there are some spots that the code calculates program enrollments based on course enrollment; those places will need to be updated to either stop doing implicit program enrollments or to check for an explicit unenrollment.
