### ISSUE TITLE
Dashboard: course shouldn't be "In Progress" and "Ended" at the same time

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1252]
### Steps to Reproduce

Not sure, but I saw it on one user's dashboard in production. 

![image](https://user-images.githubusercontent.com/430126/206021253-6ae701cf-f963-4b85-af72-013e9934d6c6.png)

### Expected Behavior

- remove the "In Progress" label?

**Comment by collinpreston** [comment]
@pdpinch 
I went to check some of the mock ups for the course and program cards.  Based on this mock-up (https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/469597997/preview?scrollOffset=306) should we indeed have an "in progress" label, and should the labels be displayed under the image (currently they are displayed at the top of the card)?

**Comment by pdpinch** [comment]
Collin and I discussed and the simplest solution now is to just remove the "In Progress" label, while we make some longer-term decisions about the UI. 

I've updated the description to reflect that.
