### ISSUE TITLE
Enrolling in a course from the program drawer doesn't necessarily work as expected

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#1304]
If you're not enrolled in a course, the program drawer displays a `ProgramCourseInfoCard` that has the course details in it, including a call-to-action to enroll if there's a CMS page for the course. However, you can't always enroll in the course - if the course doesn't have any runs that can accept enrollments, you won't get an enroll card on the course info page. If the course isn't eligible for enrollment, the enroll messaging should not appear. 

### Steps to Reproduce

1. Enroll in a program (doesn't matter what way, but the program does need to have >1 course in it that has a CMS page and does _not_ have open enrollments).
2. Open the program drawer for the course from your dashboard.
3. Click Enroll on the course you're not enrolled in.

### Expected Behavior

You're delivered to the course details page, where you can then enroll in the course.

### Actual Behavior

You're punted to the course info page, and no enroll button is presented. 

### Other Notes

(These are mostly for @pdpinch)

Do we want the enroll button to send the users to the course details page? I looked back through the issues relating to the program drawer and I'm not sure there was a clear spec for that. It seems like the Enroll button would be more clear if it were a More Info button, or if the button actually did enroll you in the course. 

Similarly, we don't link the title at all in the `ProgramCourseInfoCard`, where we do in the `EnrolledItemCard` (it either goes to the program drawer or to the courseware URL, if there is one). Thinking it should also link to the Course Details page (if there is one) for consistency.

**Comment by pdpinch** [comment]
@jkachel we removed the enroll button from the program drawer in https://github.com/mitodl/mitxonline/issues/1309 didn't we?

If that's correct, please close this.
