### ISSUE TITLE
Adjust 3T2022 DEDP certificates to reflect passing requirement for final exam

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1315]
For the 3T2022 DEDP courses, the passing status from the edX grades API is not reliable. For these courseruns, the course team has a policy that the learner must pass the final exam, in addition to getting an overall score above 50%. 

As far as I know, we don't have easy access to an API that can return the status of the final exam grade. 

Since this will be a one-time adjustment, just for this course run, I think we can treat this as a data migration, or perhaps a batch run of the `manage_certificates` management command. 

#### Acceptance Criteria:

- [ ] Don't give a certificate to the learners who failed the final exam.
- [ ] Give a certificate to anyone with a passing grade in the course who did pass the final exam.

#### Related issues

- We will need to do some similar grade and certificate manipulation in MicroMasters

**Comment by pdpinch** [comment]
After we get a list of who will be revoked, we can batch up the management commands

1. create a certificate for someone who failed
2. revoke the certificate for them 
3. repeat

4. run the management command to create the remaining certificates

**Comment by jkachel** [comment]
These should be processed now. 

* There's a new BI query that shows the certificates that have been created: https://bi.odl.mit.edu/queries/1218
* 67 total certificates were revoked. 
* I've documented the process for this here in case we need to do it again: https://github.com/mitodl/hq/discussions/402

I can throw the processed Excel sheets up somewhere (GDrive share) if that'd be helpful too.
