### ISSUE TITLE
unenroll without a refund

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1321]
Sometimes learners want to unenroll from a course but they can't go through the refund process. Currently the only automated way to unenroll a user is via submitting a refund request through the Google sheets.  

Some cases:

1. MicroMasters users who were enrolled automatically based on a legacy payment. 
2. Learners who missed the refund deadline but still want to get out of the course. 

#### Acceptance Criteria:

- [x] add an "unenrolled" status to the `courserunenrollment` record
- [x] #1335
  1. updates the courserunenrollment in mitxonline
  2. updates the enrollment status in open edX 
  3. if the edX update fails, there should be a `-f` flag that only updates the mitxonline enrollment
- [ ] propose a customer support UI for unenrolling users (via refine? or google form?)

**Comment by aliraza-abbasi** [comment]
@pdpinch I've some questions.

- Can we create a `refine` page to display the list of users in the `staff dashboard`? There we can unenroll users.
- Does this `management command` and `refine` page will only be for users from MicroMasters or it'll be for all users?

**Comment by pdpinch** [comment]
> Does this management command and refine page will only be for users from MicroMasters or it'll be for all users?

All users.

**Comment by pdpinch** [comment]
> I see an "unenroll" option in the course card ?!

When a user tries to unenroll from a course they have paid for, we force them to go through Customer Support, so CS can determine if they are eligible for a refund. (maybe we should rethink this UI?). 

> Currently the only automated way to unenroll a user is via submitting a refund request through the Google sheets

> Is that bad ?

Yes, if the user isn't eligible for a refund.

**Comment by pdpinch** [comment]
For reference, here are some screenshots of the unenroll UI when the user has paid for a course: 

Screenshots of the current UI: 

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/430126/211561870-c8c3623c-e9c5-48b2-a36f-15946b3cc6ae.png">

<img width="526" alt="image" src="https://user-images.githubusercontent.com/430126/211561912-daba5ff6-f0f9-494d-aa04-c1f32eb96bf5.png">

**Comment by aliraza-abbasi** [comment]
@pdpinch I would like to share my thoughts on how I want to add the `refine` page for user unenrollment with the following steps.

1. A page that will display the users list with an `enrollments` button for each user and can be filtered
2. Clicking on the `enrollments` button for a user will move to the next page where we can see the list of course runs in which the user is enrolled with an `unenroll` button and can be filtered.
3. By clicking on the `unenroll` button the user will be unenrolled from the selected course run.

Please let me know if you need to add or change something

**Comment by pdpinch** [comment]
Thanks Ali. I need to discuss this a bit more before we decide to go ahead with adding a refine UI for it.

**Comment by pdpinch** [comment]
I created a sub-issue just for the management command. If that's what your PR #1333 does, we can move ahead with that while we are deciding about using refine vs. updating the learner UI.

**Comment by aliraza-abbasi** [comment]
Thanks, Peter. Yes, my PR does the same as the new ticket I've updated the PR with a new ticket. This PR #1333 is ready for review
