### ISSUE TITLE
3 learners who are missing course certificates & program certificates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1343]
Members of the course team review the list of program certificate earners and found 3 learners who should have gotten one. 

Further investigation showed that these 3 learners were still owed certificates. 

Account details on https://odl.zendesk.com/agent/tickets/145049

We need to:
- [x] generate the certificates for these 3 users
- [x] determine why this happened
- [ ] determine if there any other learners who are owed certificates 
- [x] propose a solution

**Comment by asadali145** [comment]
Hey @pdpinch, Could you please give me access to https://odl.zendesk.com/agent/tickets/145049?

**Comment by asadali145** [comment]
> determine why this happened

Summary: Grades were updated after the end date + 24h. We only look for the courses that expired within the last 24 hours and update grades for those courses.

The end date for both courses was 4th Jan 2023.

- For [14.100x](https://courses.mitxonline.mit.edu/courses/course-v1:MITxT+14.100x+3T2022/), the grades for both the users were overridden on 12th Jan, Our task only looks for the courses expired within 24h.
- For [14.750x](https://courses.mitxonline.mit.edu/courses/course-v1:MITxT+14.750x+3T2022/), the user grade was overridden on 5th Jan 8:43PM, but the course expiry was 4th Jan 19.20. So, When our task picked the course for the last time the grade was not updated.

> propose a solution

Currently, we have set CERTIFICATE_CREATION_DELAY_IN_HOURS=24h. If this seems feasible then we can that to 48h maybe.

> determine if there any other learners who are owed certificates

I am currently looking into it.

**Comment by pdpinch** [comment]
Great, thanks for the research. You can check off some of the boxes up top. 

I'll discuss changing `CERTIFICATE_CREATION_DELAY_IN_HOURS` with some users. If it makes sense to change it, I'll open a separate issue. I think the work done on #1339 will also help in the future. 

You can close this issue after you've finished "determine if there any other learners who are owed certificates" (assuming you find a way to do that)

**Comment by asadali145** [comment]
@pdpinch There seems to be no easy way to find out this information to `determine if there any other learners who are owed certificates`. We have a couple of options:
 
- If we only need the information of such learners and don't want to generate certificates then we will need to fetch grades in MITxOnline somehow maybe by writing a migration or by calling a function from shell etc.

- **Recommended**: If we also want to generate missing certificates then we can use the `manage_certificates` command for the expired course runs to fetch grades and generate missing certificates.

What do you think we can go with?

**Comment by pdpinch** [comment]
> Recommended: If we also want to generate missing certificates then we can use the manage_certificates command for the expired course runs to fetch grades and generate missing certificates.

Can you explain more about how this would work?

**Comment by asadali145** [comment]
`manage_certificates` provides an option to pull all the grades for a course run and it also creates the missing certificates for that course run if any. So, We can run this management command using this option to pull grades for the course runs that we suspect have missing certificates.

A snippet from the docs of the management command:
> 1. Sync grades with edX and generate certificates. (For all users)
./manage.py manage_certificates -—create -—run=<course_run_courseware_id>

**Comment by pdpinch** [comment]
Thanks for this clarification. I didn't know that running `manage_certificates` this way would pull grades from open edX. 

Two more questions:

1. How does it handle revoked certificates? 

2. Does it produce any output, like a list of updated or created certificates?

**Comment by asadali145** [comment]
> 1. How does it handle revoked certificates?

It won't do anything if a certificate already exists for a user.

> 2. Does it produce any output, like a list of updated or created certificates?

Yes, It produces output like this:

<img width="1752" alt="Screen Shot 2023-01-26 at 4 29 04 PM" src="https://user-images.githubusercontent.com/52656433/214824933-f2230128-68e6-4619-a370-9560712e23b8.png">

**Comment by cachob** [comment]
@asadali145 I was able to run this command successfully:

~ $ python manage.py manage_certificates --user [piyushpat89@gmail.com](mailto:piyushpat89@gmail.com) --run course-v1:MITxT+14.100x+3T2022 --create
Processed user piyushpsr ([piyushpat89@gmail.com](mailto:piyushpat89@gmail.com)) in course run course-v1:MITxT+14.100x+3T2022. Result - Grade: updated (passed: True), Certificate: created

Are we able to apply this command on xpro? I believe that --grade is a required field for the `sync_grades_and_certificates` command that allows us to create a certificate manually for an individual. The `manage_certificates` command will save us a step of having to find the final grade of the user in order to generate the cert.
