### ISSUE TITLE
User learning record should use course number instead of course readable ID

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mitxonline#1344]
### Steps to Reproduce

1. When logged in as a user who is registered for a course(s) associated with a program, visit: https://rc.mitxonline.mit.edu/records/1/

### Expected Behavior

The Course ID column should display only the course number (course-v1:MITx+JPAL102x -> JPAL102x).

### Actual Behavior

The full course readable ID is displayed.

### Screenshot or Screencast

![Screenshot 2023-01-12 at 13 36 00](https://user-images.githubusercontent.com/8311573/212150674-b5dea647-ebfa-4276-a82f-6711c103bb8b.png)

**Comment by collinpreston** [comment]
@pdpinch, should the column be renamed from "Course ID"?

**Comment by pdpinch** [comment]
Yeah. Should be "course number"
