### ISSUE TITLE
Vertical align table headers on learner record UI

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mitxonline#1347]
### Steps to Reproduce

When viewing a learner record (https://rc.mitxonline.mit.edu/records/1/), the table headers should be vertically aligned to the bottom as is done in MicroMasters.

### Expected Behavior

The table headers are vertically aligned to the bottom.

### Actual Behavior

The table headers are not vertically aligned to the bottom.

### Screenshot or Screencast

Future:
![Screenshot 2023-01-12 at 13 56 23](https://user-images.githubusercontent.com/8311573/212157681-d89e1ba1-94f7-46e2-9564-cf423d07bb8f.png)

Current:
![Screenshot 2023-01-12 at 13 56 29](https://user-images.githubusercontent.com/8311573/212157684-9383421d-fd8e-46ff-abb7-3b4adb435323.png)

**Comment by pdpinch** [comment]
@collinpreston I don't think this is particularly important issue, but I'm wondering if you're actually working on it. If you don't plan to work on it soon, you could remove yourself (and I'll probably put it into the backlog)

**Comment by collinpreston** [comment]
@pdpinch ah sorry Peter, I completed this in https://github.com/mitodl/mitxonline/pull/1368.
