### ISSUE TITLE
Set blocked country when importing new courseruns 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1349]
As an admin, it's time-consuming and error-prone to set up country blocking. We should make this simpler and more robust. 

Currently, everytime I create a new **_course_** in mitxonline, I need to add a new record for each blocked course and country pair through the django admin `/admin/courses/blockedcountry/`

**And**, in open edX studio, when we create a new **_courserun_**, I need to add a new record for each course run in the django admin, `/admin/embargo/restrictedcourse/`

#### Acceptance Criteria:

- [ ] Add a parameter to the `import_courserun` management command for setting the blocked countries. This should be pretty simple for creating a `blockedcountry` record in mitxonline
- [ ] research if there is a way to get and set `restrictedcourse` in open edX studio.

**Comment by asadali145** [comment]
> research if there is a way to get and set restrictedcourse in open edX studio.

There is no way in edX to get and set `restrictedcourse` data for a course. Maybe we can create our own app and APIs if needed in [open-edx-plugins](https://github.com/mitodl/open-edx-plugins)

**Comment by Ferdi** [comment]
>  in open edX studio, when we create a new courserun, I need to add a new record for each course run in the django admin, /admin/embargo/restrictedcourse/

Is this necessary  if we are blocking users in mitxonline app ?

**Comment by pdpinch** [comment]
> in open edX studio, when we create a new courserun, I need to add a new record for each course run in the django admin, /admin/embargo/restrictedcourse/

> Is this necessary if we are blocking users in mitxonline app ?

We miss some edge cases, like users who report they are from one country, but use an IP address from another country. However, I don't (small) risk justifies the effort and complexity.
