### ISSUE TITLE
BI: display certificate revoked in customer service report

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1358]
As a CS teammember, I'd like to be able to tell when a certificate has been revoked, so I don't give out a broken URL to customers. 

When a certificate has been revoked, the URL will return a 404.

**Comment by rachellougee** [comment]
@pdpinch added "Certificate_Revoked" next to "Certificate_URL"
![image](https://user-images.githubusercontent.com/3138890/213238284-feb1e51a-1268-4735-8e4b-7171341b2c19.png)

**Comment by pdpinch** [comment]
Thanks. How hard would it be to hide the value of "Certificate URL" when the certificate is revoked? If it's more than 10m of effort, we probably shouldn't do it.

**Comment by rachellougee** [comment]
@pdpinch it's a quick fix so I hide the value of "Certificate URL" when the certificate is revoked. Please take a look.

**Comment by pdpinch** [comment]
🤦 neither one of us included a link on this issue. The report in question is at https://bi.odl.mit.edu/queries/1189

Looks good to me!
