### ISSUE TITLE
course.title and courserun.title don't match

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1365]
### Steps to Reproduce

1. There are a couple of different ways to see this, but the easiest is to look at the API results at 
https://mitxonline.mit.edu/api/courses/ and search for the course id `course-v1:MITxT+10.50.CH01x`

Presumably this is a result of the title being updated in Studio, which is then synced with courserun.title but not course.title (see https://github.com/mitodl/mitxonline/issues/106) 

### Expected Behavior

- course.title and courserun.title should be the same

### Actual Behavior

- course.title and courserun.title are not the same
- If there are multiple courserun.titles, we could set the course title to the one with the latest start date

### Screenshot or Screencast

<img width="1126" alt="Screenshot 2023-01-20 at 10 22 37 AM" src="https://user-images.githubusercontent.com/430126/213738104-ebdd98ca-ee2b-469c-801e-c54f0d946287.png">

**Comment by pdpinch** [comment]
@asadali145 what is your plan with this? 

There was some discussion in Slack at https://mitodl.slack.com/archives/C02649X2P1V/p1674227568748509

In particular, I liked this suggestion from @rhysyngsun 
> so an option might be to update the course title from the page title, although right now we don't enforce 1 product page per course/program so we'd want to address that too

**Comment by asadali145** [comment]
@pdpinch I was about to implement it as we have mentioned in the ticket i.e. sync course.title with courserun.title. But it seems like the suggestion above by @rhysyngsun is a better option to go with.

> although right now we don't enforce 1 product page per course/program so we'd want to address that too

I don't think there is any issue with this part of the suggestion as we **_cannot_** create multiple CMS Pages for a single course. So, It does not require anything else apart from syncing the CMS Page title with course.title.

**Comment by asadali145** [comment]
@pdpinch Could you please have a look at these changes and see if you have any suggestions? https://github.com/mitodl/mitxonline/pull/1382

**Comment by pdpinch** [comment]
Your PR looks like what @rhysyngsun and I had in mind.

**Comment by mbertrand** [comment]
This seems to be an issue still on production:

```json
    {
        "id": 45,
        "title": "Chapter 2: Mathematical Formulation",
        "readable_id": "course-v1:MITxT+10.50.CH02x",
        "courseruns": [
            {
                "title": "Analysis of Transport Phenomena: Mathematical Formulation",
                "start_date": "2023-03-01T14:00:00Z",
                "end_date": "2025-02-26T14:00:00Z",
                "enrollment_start": "2023-01-03T14:00:00Z",
```

                
![Screenshot 2023-03-06 at 3 56 47 PM](https://user-images.githubusercontent.com/187676/223231232-03ed54e5-c50c-4060-80ac-0daa8363d16a.png)

**Comment by asadali145** [comment]
I was looking into it. What we did in this ticket was to sync all the future changes in CMS product pages with the course objects.

Somehow we missed fixing the current courses. I have shared the list of courses in [slack](https://mitodl.slack.com/archives/C02649X2P1V/p1678190763947209?thread_ts=1678163400.687869&cid=C02649X2P1V) that need to be repaired.

9 of these are straight forward and we just need to press the Publish button again from the CMS. Some of the above have conflicting titles but we should have a look at those and change the title in CMS or just publish from CMS.

I can write a data migration to update the titles and can also publish the courses again to reflect the course titles.

Let me know what seems better to you and we can do that.

FYI @pdpinch

**Comment by pdpinch** [comment]
I'm planning to take a look and click the publish button.

I don't understand what you mean by conflicting titles though.

**Comment by asadali145** [comment]
> I don't understand what you mean by conflicting titles though.

I meant that they are slightly different from each other like the one in CMS is a bit different than the one we have in Course.title

**Comment by pdpinch** [comment]
I think I published all of them. Can you look over my work and see if I missed any?

**Comment by asadali145** [comment]
Looks good except for this 1 course. Titles differ a bit in CMS and Admin.
https://mitxonline.mit.edu/admin/courses/course/8/change/?_changelist_filters=o%3D1.4.2
https://mitxonline.mit.edu/cms/pages/17/edit/
