### ISSUE TITLE
Discounts Dashboard: Discount creation form is not working

### ISSUE THREAD

**Issue by asadali145** [mitodl/mitxonline#1370]
### Steps to Reproduce

- Visit the staff dashboard at `https://rc.mitxonline.mit.edu/staff-dashboard/discounts`.
- Click on the `create` button to create a new discount. The discount creation form is not showing up.

### Expected Behavior

- Discount creation form is working fine.

### Actual Behavior

- The discount creation form is not loaded with a console error.

### Screenshot or Screencast

<img width="1755" alt="Screen Shot 2023-01-23 at 5 52 02 PM" src="https://user-images.githubusercontent.com/52656433/214044429-82eee474-81dd-4e32-af14-36a8a989cf65.png">

**Comment by jkachel** [comment]
Probably worth noting that https://github.com/mitodl/mitxonline/pull/1361 hasn't been deployed to RC yet.

**Comment by jkachel** [comment]
Yup, closing at fixed by #1361.
