### ISSUE TITLE
BI: Purchase Reconciliation report is throwing an error

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1383]
### Steps to Reproduce

refresh the report at  https://bi.odl.mit.edu/queries/1190
 
### Actual Behavior

- Error running query: column "purchaser_id" does not exist LINE 6: , purchaser_id as "User ID" ^

### Screenshot or Screencast

<img width="1690" alt="image" src="https://user-images.githubusercontent.com/430126/214563972-eca41f37-5c70-44ea-b7af-cce879f9cc76.png">

**Comment by rachellougee** [comment]
Sorry about that. I might accidentally change the data source to "Bootcamp Ecommerce" I stumble upon this report when reviewing the OL data platform issue.
