### ISSUE TITLE
wrong help URL in Learning MFE

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1385]
### Steps to Reproduce
1.  Go to course 24.02x at https://courses.mitxonline.mit.edu/learn/course/course-v1:MITxT+24.02x+3T2022/
2. Activate the "Help" link in the header.
3. The link resolves to https://mitx-micromasters.zendesk.com/hc/en-us

### Expected Behavior
As a learner in a non-MicroMaster's course, I expect to be directed to a generic help page like this one: 
https://mitxonline.zendesk.com/hc/

### Screenshot or Screencast
![image](https://github.mit.edu/storage/user/923/files/028bcd80-9739-11ed-8201-964719de44ac)

**Comment by arslanashraf7** [comment]
@blarghmatey Could you confirm if a new release of MITxOnline/edX has been deployed after the merge of https://github.com/mitodl/ol-infrastructure/pull/1325?

I was looking at this and the help URL still resolves to https://mitx-micromasters.zendesk.com/hc/en-us.

**Comment by arslanashraf7** [comment]
Closing this, Tested it, It's working now.
