### ISSUE TITLE
wrong aria-label for ⋮ menu on course cards

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1386]
(this comes from the open learning accessibility experts)

### Steps to Reproduce

On any course card on any Dashboard, the kebab menu (⋮) announces to NVDA as "more_vert".

### Expected Behavior
Expect the button to announce "Course options for COURSE NAME"

### How to Remediate
This is easy to fix by MOVING the current aria-label="Course options for COURSE NAME" from the inner span to the button.

For example, this code:

```
<button type="button" aria-haspopup="true" aria-expanded="false"
class="d-inline-flex unstyled dot-menu btn btn-secondary">
<span class="material-icons"
aria-label="Course options for Designing and Running Randomized Evaluations"
title="Course options for Designing and Running Randomized Evaluations">
more_vert
</span></button>
```

would be changed to this:

```
<button type="button" aria-label="Course options for Designing and Running Randomized Evaluations" aria-haspopup="true" aria-expanded="false"
class="d-inline-flex unstyled dot-menu btn btn-secondary">
<span class="material-icons"
title="Course options for Designing and Running Randomized Evaluations">
more_vert
</span></button>
```

### Screenshot or Screencast

(Optional)
![image](https://github.mit.edu/storage/user/923/files/9febee80-7703-11ed-9a6a-2e0e1335e228)

**Comment by collinpreston** [comment]
I believe this issue was resolved in an early PR: https://github.com/mitodl/mitxonline/pull/1267.  Checking the current HTML, the suggested change shown in the issue appears to be in place.  Closing.
