### ISSUE TITLE
Add (minimal) fields to the user registration form

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1399]
part of #1398 

As a user registering, I don't want to spend a lot of time filling out information before I'm sure I really want to enroll in a course. 

As an admin, I want to gather enough information that we can create an account and do the necessary compliance checks for age, OFAC (country) and SDN (name) 

### acceptance criteria 

- [ ] add a field for age and validate that the user is at least 13 years old
- [ ] if the user is in the US, display a field for their state
  - partial addresses help us avoid false positives from SDN checks

**Comment by jkachel** [comment]
Per discussion, I'm starting with:
* State field - if the user is in the United States, show a dropdown field with US states in it and make the field required
* Year of Birth - adding the field in; will also need a bit of validation to block registration if age is < 13
* Gender - adding optional field
This will be implemented in the signup flow and the profile view/edit flow. (This is not a comprehensive description of what needs to be done, just notating first steps for me.)
