### ISSUE TITLE
Manual process to refund PayPal purchases 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1426]
We reliably get 400 errors when refunding PayPal purchases. While we are working on #1047, what is the correct way to handle these errors?

The Finance team has been helpful by manually refunding the purchases through the Cybersource Business Center. What do we need todo to make sure the mitxonline application is in sync with that refund?

example user issues:
- https://github.com/mitodl/hq/issues/585

**Comment by cachob** [comment]
@jkachel or @collinpreston - do you mind taking a stab at this pls?

**Comment by jkachel** [comment]
What I've done in the past is set the order to "Refunded" using a database shell and then manually reconciling the enrollments in MITx Online according to the situation. (So, if it's a partial refund and the learner's keeping their `verified` enrollments, I don't adjust them at all; but for https://github.com/mitodl/hq/issues/585 I'd set the enrollment back to `audit` and then sync it with edX.) 

An important thing to note is that the Django Admin has a Refund Order button/workflow for Completed Orders - this will try to push a refund through using the CyberSource API so it's not useful in this case (the order is already refunded - and we can't refund PayPal transactions using this method either; it fails for the same reasons they fail via the Google sheet).

**Comment by pdpinch** [comment]
@jkachel Is it possible to write a management command, or add a button somewhere so @cachob and I can do this?
