### ISSUE TITLE
Inconsistent enrollment status if edX enrollment fails

### ISSUE THREAD

**Issue by asadali145** [mitodl/mitxonline#1433]
### Steps to Reproduce

- Enroll in a course and make sure that the edX enrollment fails somehow. Maybe set `CourseRunEnrollment.edx_enrolled=False`
- Course detail page shows the `Enroll Now` button.
- Visit the dashboard. You can see the enrolled course.

### Expected Behavior

- Should be consistent.

### Actual Behavior

- Inconsistent course enrollment status.

### Screenshot or Screencast

<img width="1750" alt="Screen Shot 2023-02-16 at 4 21 29 PM" src="https://user-images.githubusercontent.com/52656433/219351710-ef34c5b9-9001-4243-badd-ba4703249be7.png">
<img width="1750" alt="Screen Shot 2023-02-16 at 4 21 36 PM" src="https://user-images.githubusercontent.com/52656433/219351734-7502f73d-364c-46bc-a841-16e9bcaad527.png">

**Comment by asadali145** [comment]
@pdpinch What do you think we should do in this case?

We can either show the `Enrolled` button on the detail page as enrollments eventually get repaired, but enrollments might not be synced at a time between edX and MITxOnline.

Another thing that we can do is to hide such enrollments from the dashboard as well.

**Comment by pdpinch** [comment]
We changed the UX of the course about page, so this issue is no longer relevant as written.
