### ISSUE TITLE
Block search crawlers on CI, RC

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1455]
As a google search user, it's confusing to see search results from MicroMasters RC.

on MicroMasters, we added a library django-robots (https://github.com/mitodl/micromasters/pull/5280) which made it easy to customize the robots.txt file on each instance of the app. 

Acceptance Criteria:
 - [ ] Add django-robots
 - [ ] When deployed to CI and RC, block all robots
 - [ ] When deployed to production, confirm that the expected pages are still crawlable

**Comment by collinpreston** [comment]
Hi @pdpinch , so when researching this approach further I found a few things out:
1. `mitxonline` is already using `django-robots`
2. Based on Google's documentation (ref: https://developers.google.com/search/docs/crawling-indexing/robots/intro#what-is-a-robots.txt-file-used-for) the best way to block robots is not actually by hiding or modifying the robot.txt file but actually with a `<meta>` tag containing a reference to `noindex`.  This ensures that search engines don't index the pages even if other pages or sites link to the pages.

**Comment by pdpinch** [comment]
Is it set up right on CI and RC?

https://rc.mitxonline.mit.edu/robots.txt 

returns:

```
User-agent: *
Disallow:
```

Shouldn't it be 

```
User-agent: *
Disallow: /
```

I could be wrong. 

As for a metadata tag, I'm not sure how to apply that to every page on CI and RC and none on production. Robots.txt seems simpler when we want to block the whole site.
