### ISSUE TITLE
Allow users to unenroll from a course at any time

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1466]
We've received many customer supports tickets for users who want more control over unenrolling and refunds, which could be self-service if: 

1) We let users unenroll themselves whenever they want to 
2) When refunding a user, we don't automatically unenroll them

#### Designs and Mockups

No new design is needed; the existing Unenroll and Refund UX is adequate.

#### Acceptance Criteria:

- [ ] Allow enrolled users to unenroll at any time
- [ ] Update the refund workflow so that users _**are not unenrolled**_ when they get a refund. 
   - Customer Support will instruct users to unenroll, if they choose to do so. 
   - refunded learners should still have there enrollment mode/course mode changed from "verified" to "audit" 
- [ ] Confirm that unenrolled users can still request a refund

**Comment by jkachel** [comment]
> Update the refund workflow so that users are not unenrolled

For clarity, the refund process should still knock the learners' enrollment back to `audit` status?

**Comment by pdpinch** [comment]
> For clarity, the refund process should still knock the learners' enrollment back to audit status?

Yes. I added that to the description as well.

**Comment by jkachel** [comment]
Another question: I have the code updated to allow for unenrollments for `verified` enrollments. However, I think it's probably a good idea to alert learners that they _won't_ receive a refund for their payment. I've amended the text in the unenroll dialog to this - can you take a look?

![image](https://user-images.githubusercontent.com/945611/223824213-46d47fa1-d874-4cb5-83d3-c2b9c1360526.png)

**Comment by pdpinch** [comment]
Good idea. 

Why do you say “(if any)” ?

**Comment by jkachel** [comment]
> Why do you say “(if any)” ?

Mainly for the case where the learner has used a code that's given them the course for free (so there's nothing to refund).
