### ISSUE TITLE
Redirect studio-qa.mitxonline.mit.edu from http to https

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#15]
### Steps to Reproduce

- Type studio-qa.mitxonline.mit.edu or http://studio-qa.mitxonline.mit.edu into the URL field of a browser
- Note that rather than trying to load https://studio-qa.mitxonline.mit.edu, it will fail to load the http version of the page

### Expected Behavior

- You would be redirected to https://studio-qa.mitxonline.mit.edu

### Actual Behavior

- Tries to display http://studio-qa.mitxonline.mit.edu and gives an error:

![image (4)](https://user-images.githubusercontent.com/21342568/126206145-9f3b20bb-3811-4ac0-b24d-4f75969799c2.png)

**Comment by blarghmatey** [comment]
This is functional now
