### ISSUE TITLE
don't set `Addl field flag` to true until the user has filled out the required fields

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1513]
### Steps to Reproduce

1. Create a new account on RC
2. Don't fill out the second screen of optional fields in the profile, i.e. highest level of education and user type (student, professional, etc.)
3. Enroll in a course that has started 
4. Go to the mitxonline dashboard
5. Click a course title to enter the course
6. Since you haven't filled out the required additional fields, you should get a pop-up to complete them. 
7. Dismiss the pop-up. 
8. Click the course title to enter the course again. 

### Expected Behavior

- `Addl field flag` should still be false because you haven't filled in the required additional fields 
- Since you haven't completed the additional fields, the pop-up should display again

### Actual Behavior

- the pop-up does not display because `Addl field flag` is set to true on your user profile
- you link into the course

**Comment by pdpinch** [comment]
Before working on this, please briefly describe how it could be fixed. I'm not yet sure it's worth the effort.

**Comment by jkachel** [comment]
The code that fires the popup also fires off a migration that explicitly sets that field to True because we didn't want the popup to happen twice. Easiest remedy would be to remove this and have the field be set as part of the normal save operation.

**Comment by pdpinch** [comment]
Ok, let's do it.
