### ISSUE TITLE
intro text on profile form isn't accurate

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1552]
### Steps to Reproduce

1. Create a new account on RC

### Actual Behavior

- the intro text on the form says that we won't ask again, but we do
> To help us with our education research missions, please tell us
                more about yourself. If you do not want to supply this
                information, simply click the Close button - we won't ask you
                again.

### Expected Behavior

- new intro text:
> ### Actual Behavior

- form says 
> To help us with our education research missions, please tell us
                more about yourself.

**Comment by collinpreston** [comment]
@pdpinch, is this the form that this issue is referring to?
![Screenshot 2023-04-14 at 13 52 26](https://user-images.githubusercontent.com/8311573/232120480-ffe6088f-6d5c-4be8-9998-638ee396d27a.png)

**Comment by pdpinch** [comment]
Oh, did this get updated already?

**Comment by collinpreston** [comment]
@pdpinch Looks like James caught it while doing https://github.com/mitodl/mitxonline/pull/1499

**Comment by collinpreston** [comment]
@pdpinch In those other locations, the text used is "To help us with our education research missions, please tell us more about yourself."

**Comment by collinpreston** [comment]
@pdpinch I think we can close this.  Reopen if I misunderstood.
