### ISSUE TITLE
Two accounts with the same e-mail

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1580]
### Steps to Reproduce

1. Enter an email, with lowercase letters in the address, at https://rc.mitxonline.mit.edu/create-account/
2. In another tab, open https://rc.mitxonline.mit.edu/create-account/ again and enter the same email, but all uppercase 
3. You should get two verification emails with different links. 
4. Open both links in separate tabs
4. Fill out one of the registration forms and  complete the first screen of the account creation process
5. In the second tab, fill out the registration form again. In my testing, I used a different username to avoid the username validation check. 

### Expected Behavior

- you should get an error when filling out the second form because an account with that email already exists

### Actual Behavior

- two accounts are created
- You can see where I've done this at https://rc.mitxonline.mit.edu/admin/users/user/?q=2023-04-28
- I'm not aware of this having happened in production on mitxonline, but we should check

### Related Issues

- xPRO has the same bug, https://github.com/mitodl/mitxpro/issues/2633
- I imagine that bootcamps does as well.

**Comment by jkachel** [comment]
This is on production now; probably a similar approach can be used for the other two (I know MITx Online lifted a lot of the code from xPro so that's probably the easiest to do it in).

**Comment by jkachel** [comment]
Closing this; this has been on prod for about a week.
