### ISSUE TITLE
Add more user email normalization to lowercase

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#1592]
Noticed this while working through https://github.com/mitodl/mitxonline/pull/1586 - didn't address it in that PR though. Searches for email addresses in the user object should be case insensitive, as email addresses themselves are not case sensitive. I noted this because I created an account with all caps and then tried to log in without that capitalization and was denied access. (Oddly, there's some of this already - the _domain_ is normalized to lowercase but the username part is not. I was able to log into RC as `APPTEST+DUPTEST@JKACHEL.COM` but this is stored as `APPTEST+DUPTEST@jkachel.com` in the database.) 

We should probably store the email address as specified by the user and instead normalize interactions through the system to lowercase to compensate for insufficiently smart email servers that may actually treat the username part of the email address as case-sensitive. (In less words, login should use a case insensitive search but in my example it should be stored as it was.) 

### Steps to Reproduce

1. Create a user account using an email address in all capitals. 
2. Attempt to log in with that same email address, but input it in lowercase.

### Expected Behavior

I should be able to supply the password and complete the login process.

### Actual Behavior

I get the "Can't find your email" message and cannot log in.

**Comment by pdpinch** [comment]
It doesn't look like this is working as intended. 

See https://github.com/mitodl/hq/issues/1523#issuecomment-1561762003

**Comment by collinpreston** [comment]
I'm pretty sure I introduced this error in this PR: https://github.com/mitodl/mitxonline/pull/1610.  I'm working through Docker troubles, but I would assume this line (https://github.com/mitodl/mitxonline/blob/d69dba9965a4c80f42dff552b44f96933ab12aa0/authentication/serializers.py#L225) should have `__iexact` added to it
