### ISSUE TITLE
Implement home page product section

### ISSUE THREAD

**Issue by gsidebo** [mitodl/mitxonline#16]
Related: https://github.com/mitodl/mitxonline/issues/14
Desktop design: https://projects.invisionapp.com/share/KH11D3ZN53GC#/screens/455419669
Mobile design: https://projects.invisionapp.com/share/KH11D3ZN53GC#/screens/455488637

PR #11 added Wagtail and some initial barebones models for the home page. This issue covers the work to implement the product/courses section with the individual cards (headed by the "Duis aute" text in the designs)

**Acceptance criteria:**
- Products can be added to home page product section, and any product type can be chosen (to start out, the only valid product type will be `CoursePage`)
- When fully configured in Wagtail, the feature product section of the home page matches the designs in desktop and mobile screen widths

**Not needed:**
- Courses (products) do not need to link to anything  
- Header section with MITx Online logo
- Footer

**Implementation details:**
- Updated product page models (`ProductPage`, `CoursePage`) were added in PR #28 (still open as of 7/26)
- We will not be using Wagtails views and template tags to serve images. We're going to expect that images are optimized and correctly sized when they're uploaded, and the `wagtail_img_src` template tag can be used to get the image source URL
  - You can use services like [img.pizza](https://img.pizza/) or [placekitten](https://placekitten.com/) to create exactly-sized images if you don't want to chop up your own images
- The `HomePage` field that stores the "Duis aute" text in the designs can be called `product_section_title 
- In Wagtail, the field name of this section in the home page should be something like `featured_products`
- We should be able to add any number of these product cards  to the home page, and to add one you should only need to select a `ProductPage` object 
  - In terms of UX, this should work like FAQ page in mitxpro ([RC link](https://xpro-rc.herokuapp.com/cms/pages/151/edit/)) using an inline panel
  - [This Wagtail doc](https://docs.wagtail.io/en/stable/reference/pages/panels.html#inline-panels-and-model-clusters) should help guide the implementation of this inline panel so that we can select any object of any model that inherits from `ProductPage`
- Taking the "Microeconomics" card as an example: "Microeconomics" is the `Course.title` field, the image is the `ProductPage.feature_image` field, the "Use economic model..." text is the `ProductPage.description` field, and the start date should be `CourseRun.start_date` of the related course run with the closest future start date. If there is no course run with a future start date, it should be blank
- If the screen is too narrow to display all of the courses/products, they should flow to a new line and the cards should all be vertically and horizontally aligned in a grid

**Comment by HamzaIbnFarooq** [comment]
(For posterity) The implementation details say that we have to use InlinePanel on ProductPage but as per my research that doesn’t seem possible, the InlinePanel works if we are mapping a django model with a wagtail page. It doesn’t work with Wagtail page to wagtail page mapping. I tried to get it to working and it does to some extent but doesn't allow the object/page to be saved in the DB.

Even the [wagtail docs](https://docs.wagtail.io/en/stable/reference/pages/panels.html#inline-panels-and-model-clusters) doesn’t seem to say anything regarding page to page mapping.

In my understanding we need to create another django model for course cards and then create a page and link both via using InlinePanel just like we did with [FrequentlyAskedQuestion in xpro](https://github.com/mitodl/mitxpro/blob/master/cms/models.py#L1585).

@gsidebo would you like to share your thoughts?

cc: @pdpinch

**Comment by gsidebo** [comment]
@HamzaIbnFarooq I think you're right. We're going for a similar UI to the one produced by that `InlinePanel` example, but that example differs from our needs in some fundamental ways. I think what we need here is a `PageChooserPanel` (https://docs.wagtail.io/en/stable/reference/pages/panels.html#pagechooserpanel) that can pick objects of any `ProductPage`-derived model (or if that doesn't work, just point it at the `CoursePage` model and we can figure it out later). If just that type of panel doesn't give us the ability to select multiple pages, you can try to combine that with `InlinePanel`
