### ISSUE TITLE
Program Record: Show letter grades instead of pass 

### ISSUE THREAD

**Issue by annagav** [mitodl/mitxonline#1647]
Few users have complained that they would like to see letter grades instead of "PASS" in their program record in MITxonline dashboard.
Related tickets: https://github.com/mitodl/hq/issues/1577, https://github.com/mitodl/hq/issues/1574
In MM:
<img width="1341" alt="Screen Shot 2023-05-15 at 8 27 48 AM" src="https://github.com/mitodl/mitxonline/assets/7574259/c596effc-6d52-4dc3-b269-4e6ed149c7cb">

In MITxOnline:
<img width="340" alt="Screen Shot 2023-06-02 at 5 04 09 PM" src="https://github.com/mitodl/mitxonline/assets/7574259/d5eef493-7076-48c7-af1c-e08b30a95329">

**Comment by pdpinch** [comment]
@annagav please add some detail about the root cause and the plan to fix it.

**Comment by annagav** [comment]
I think the root cause of this is that we use the letter grade that is in the model CourseRunGrade.letter_grade to display in the Program Record. This is very inconsistent, some grades are showing letter, some are showing 'pass'.

We should compute the letter grade based on the score, if `letter_grade` is 'pass'.

**Comment by pdpinch** [comment]
I think the problem here is that we never stored the letter grades in MicroMasters, and left it to a runtime calculation. When we migrated the data, there were no letter grades to migrate. @rachellougee can you confirm?

Let's not perpertuate the same mistake here. Instead of hard-coding the grade bands in the serializer as #1651 does, we should migrate the data. 

At the end of the day, the letter grades should follow the grading policy as defined by the course team. Since 1T2023 they can do this in open edX Studio.

**Comment by pdpinch** [comment]
I'd like to know which course runs we are missing letter grades for. 

- For most of the legacy course DEDP runs, we should follow the grading scheme that was in use in MicroMasters, for consistency. 
- I'm uncertain what to do with the DEDP grades from 3T2021, 1T2022, 2T2022 and 3T2022 grades, so I'd like to be able to look at those first. In particular, we have to be careful about passing status. 
- We shouldn't change any grades that aren't from DEDP migrated data. I don't know offhand what the grading configurations are for non-DEDP courses, and we should defer to the open edX configuration for those.

**Comment by rachellougee** [comment]
@annagav https://bi.odl.mit.edu/queries/1289 Here are DEDP course IDs that have a "Pass" letter grade

**Comment by annagav** [comment]
It is not only grades that we imported from MM, there are grades for course runs from 3T2022, like 'course-v1:MITxT+14.750x+3T2022` and `course-v1:MITxT+14.310x+3T2022`, and `course-v1:MITxT+14.73x+3T2022`. Not all courses are DEDP but majority.

**Comment by annagav** [comment]
I am reopening this issue since there are still some letter grades set to 'Pass'. This could be due to the fact that we only populated grades for the DEDP courses prior to 3T2022.
In this ticket the user still has "Passing" grade for Microeconomics: https://github.com/mitodl/hq/issues/1691

**Comment by annagav** [comment]
We need to find what was the grading policy for these courses:

course-v1:MITxT+14.100x+3T2022 |  
course-v1:MITxT+14.750x+3T2022 |  
course-v1:MITxT+JPAL102x+3T2022 |  
course-v1:MITxT+14.73x+3T2022 |  
course-v1:MITxT+14.310x+3T2022

**Comment by annagav** [comment]
@pdpinch all of these course runs have grading policy set to 'pass'/'fail'. Could you ask the course team if we can populate letter grades for these course grades based on the same distributed we did for earlier course runs?

**Comment by pdpinch** [comment]
> all of these course runs have grading policy set to 'pass'/'fail'

Which runs, exactly? I think there may be some complications with getting the desired result, particularly with 3T2022 courses.

**Comment by annagav** [comment]
@pdpinch  For these course runs:
course-v1:MITxT+14.100x+3T2022 |  
course-v1:MITxT+14.750x+3T2022 |  
course-v1:MITxT+JPAL102x+3T2022 |  
course-v1:MITxT+14.73x+3T2022 |  
course-v1:MITxT+14.310x+3T2022

**Comment by annagav** [comment]
Davis has confirmed that the grading policy was the as follows:
A 82.5-100
B 65-82.5
C 55-65
D 50-55
F <50

So we are gonna go ahead and populate 3T2022 grades.
