### ISSUE TITLE
Only courses in future are getting processed for certificate generation and grade sync

### ISSUE THREAD

**Issue by annagav** [mitodl/mitxonline#1675]
There is a user whose grade for 3T2022 recently got updated(Early June 2023) on open edx, combining the exam and course together. The users grade was not getting updated on mitxonline keeping the original grade from the course, and no certificate generated.
Looking into this closer I discovered that the grades get updated only for courses whos `certificate_available_date__gt=now-24hours`
### Expected Behavior

Updated grades should get updated in mitxonline and certificates generated accordingly.

### Actual Behavior

Grade changes after `certificate_available_date` won't get synced automatically.

### Related Issues
Discovered from this issue https://github.com/mitodl/hq/issues/1639

**Comment by annagav** [comment]
So it looks like setting `certificate_available_date` to today reprocesses the certificates and updates the grades. But the course team are unaware that when they update grades after `certificate_available_date` that grades don't get synced and they need to notify us.
Would be nice to automate this.

**Comment by pdpinch** [comment]
Can we just tell the course teams to update the certificate generation date when they update a grade?

**Comment by annagav** [comment]
@pdpinch do they have access to mitxonline django admin?

**Comment by pdpinch** [comment]
They don’t, but I thought we synced the certificate generation dates from Studio.

**Comment by annagav** [comment]
Okay, I need to check how often do we sync course run info.

**Comment by annagav** [comment]
yes, course run info syncs every hour so it should work, if they update the date.

**Comment by annagav** [comment]
@pdpinch is there a document where I can add this step as a requirement for the procedure of updating grades after certificates had been generated. So that it is documented somewhere...

**Comment by pdpinch** [comment]
Thanks for asking. I'll have to bring it up with the MITx team, since they do the training and docs for course teams. 

Can you write out the process as you see it here, so I can make sure I understand?

**Comment by annagav** [comment]
I added a signal to sync grades and generate certificates on `CourseRun` update. https://github.com/mitodl/mitxonline/pull/1745

**Comment by annagav** [comment]
After a discussion with @collinpreston, we thought it would be most efficient to allow grades to sync and certificates to be generated for another 6 months after the course has ended to avoid wrong grades and missing certificates.

**Comment by pdpinch** [comment]
> After a discussion with @collinpreston, we thought it would be most efficient to allow grades to sync and certificates to be generated for another 6 months after the course has ended to avoid wrong grades and missing certificates.

I understand the rationale for this, but it feels like a hidden setting. Someday we may have a grade that gets updated more than 6 months after the course has ended. How will we know why the grade isn't updating when that happens? What will we do to update the grade at that time?

**Comment by annagav** [comment]
Right now there are two things that one needs to do in order to sync the grades manually:
1. Go to django admin set the `certificate_avaialble_date` to now
2. go to the django shell and run ```from courses.api import *
generate_course_run_certificates()```
When I do run this task I see a bunch of grades getting updated that were out of sync.
If a grade is update after six months of the end date we can perform this manually as we do always.

**Comment by pdpinch** [comment]
Ok. Let me check to see what the limit is on updating grades in open edX. I think the course team can't update grades after 30 or 90 days after the course ends.

**Comment by pdpinch** [comment]
Grades in  open edX are frozen after 30 days ([hard-coded](https://github.com/openedx/edx-platform/blob/b97007e1823320c3d97b5a84b0c988d888250e84/lms/djangoapps/grades/grade_utils.py#L25)), according to https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/grades/docs/decisions/0005-grade-freeze.rst

This is controlled by a waffle flag, which we have turn on in production: https://courses.mitxonline.mit.edu/admin/waffle/flag/?q=enforce_freeze_grade_after_course_end

**Comment by arslanashraf7** [comment]
fwiw, I read through this ticket and I think we have [manage_certificates](https://github.com/mitodl/mitxonline/blob/main/courses/management/commands/manage_certificates.py) command. I can't recall the whole details but I think the core purpose of this command was what's mentioned in this ticket. The command can generate certificates based on user(s), course run. This command should also fetch the new grades and sync them.

**Comment by annagav** [comment]
We decided to extend the period of eligibility for certificate creation by 30 days
