### ISSUE TITLE
Program and course relationship should depend on program requirements and electives

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mitxonline#1681]
### Expected Behavior

Functionality that resolves courses or programs based on program requirements or electives should rely solely on the program's requirements and electives.

### Actual Behavior

Some functionality for resolving courses or programs is based on the Foreign relationship that Courses have with Programs.

**Issues discovered**

- [x] Enrolling in a course that is a requirement for a program should enroll the user into the program.
- [x] No program card is shown under the “My Programs” tab for a user enrolled in the program and subsequent required courses if the courses don’t have a FK to the program.
- [x] “Program overview” on the program drawer only displays course numbers based on courses with a FK to the program.  This should display courses defined as requirements or electives for the program.
- [x] Program drawer does not display course requirements or electives if the courses don’t have a FK to the program.
- [x] Program learner record does not display required or elective courses which do not have a FK to the Program.

**Comment by pdpinch** [comment]
How is this working in production?

**Comment by collinpreston** [comment]
@pdpinch, I would assume that any example is using the Course object's Program ID foreign key, but that relationship is 1:1.  That 1:1 relationship means that a second program with the same course included as a requirement, but not defined as the Course object's Program ID foreign key, will no be displayed here.

**Comment by collinpreston** [comment]
Based on [this comment,](https://github.com/mitodl/hq/issues/1578#issuecomment-1590312758) courses displayed in the Program drawer should display based on the Course and not the Course Run.

**Comment by collinpreston** [comment]
> How is this working in production?

I'll need to look into this further.  The process to setup the Program is not straightforward, at least how I approached it.

**Comment by collinpreston** [comment]
@pdpinch, there are some situations that James and I are unsure about and would like to discuss after standup soon.

1. If a user enrolls into a course which is a requirements for multiple programs
--- Should that user be enrolled into all programs?
---- If not, should the user be enrolled into one of the programs.
---- If so, how do we determine which program to enroll the user into?

2. If there exists 2 separate financial assistance forms, one associated with a Course belonging to a Program and one associated with the Program, which financial assistance form should the user be directed to?

3. When a user unenrolls from a program
--- The user should be unrolled from all course runs associated with that program.
----- What if the user is enrolled into a second program which contains the same course run?
----- If a user unenrolls from all courses within a Program, should the user be unenrolled from the Program?

**Comment by pdpinch** [comment]
> If a user enrolls into a course which is a requirements for multiple programs
> --- 1.1 Should that user be enrolled into all programs?

They should be enrolled in all the programs. 

Users can unenroll from programs through the program dashboard. 

> 2. If there exists 2 separate financial assistance forms, one associated with a Course belonging to a Program and one associated with the Program, which financial assistance form should the user be directed to?

The user should be directed to the Program for financial assistance. 

> 3. When a user unenrolls from a program

Unenrolling from a program should not affect course enrollments.

**Comment by jkachel** [comment]
WRT determining which program is the correct one to deliver the user to: one way we could tackle this is to just have one form for DEDP, period (both "kinds" for lack of a better word). Since we'll have to find an actual URL to send the user to, we can find both programs by dint of them sharing courses, and then just send the user to the one that actually has a form. It'd be up to the course team to make the form itself workable for both programs (in terms of verbiage, etc.) but in this case the programs are going to be so similar that this shouldn't be a problem. We'd also probably want to keep both sets of tiers set to the same values as well. This makes some assumptions based on the discussion in #1464 too.

**Comment by jkachel** [comment]
Friday sitrep on this - I think the initial run at this (which is just retrofitting things to stop using the `Course.program` FK) is about 85%ish done. We had tests failing in most places in the app and there are currently 28 failing now (all in the `courses` app). We'll have to do some of this again when the associated programs support is put in.
