### ISSUE TITLE
Revamp Financial Assistance to use related programs

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#1683]
As a learner, I'd like my financial assistance for one program to be applied to the other ones that it's related to. 
 
Per discussions in https://github.com/mitodl/mitxonline/issues/1464 and https://github.com/mitodl/mitxonline/issues/1681 and https://github.com/mitodl/hq/issues/1578, we have a new way to associate programs with each other via the `RelatedPrograms` table. Programs that are related using this table should share financial assistance decisions - in the specific use case we're working towards, if DEDP Public Policy has a financial assistance form and a learner applies for and receives aid, that aid should also apply for DEDP Internal Development. 

#### Acceptance Criteria:

- [ ] If financial assistance is entered for a program that has related programs, the learner should be disallowed from entering further requests in other programs. 
- [ ] If the request is approved for one program, the approval alone should apply to any related programs. 
- [ ] Similarly, if the request is denied, the denial should also apply to any related programs. 
- [ ] The financial assistance discount applied to the learner's cart should be the best one available for the given courserun they are upgrading. If the course exists in both programs, this means the best financial assistance tier out of both programs; if the course is only in one program, then the appropriate tier for that single program should be applied. (Normal rules apply otherwise - if the learner has a user discount or manually applies a discount that exceeds the financial aid discount, the learner should receive that discount instead.) 

#### Out of Scope

- Other than maybe some stuff in the Wagtail pages, this shouldn't touch on any frontend work. This should all be backend/API changes.

**Comment by jkachel** [comment]
E2E functional test

For these I also went in and adjusted the financial assistance forms to include the proper program name and saved so the fields were added. The `create_finaid_form` command doesn't know how to do this.

*Non-Related Program*

1. [x] Can create program, tiers, courseware page, and financial assistance request form
2. [x] Can create a course as a requirement in the program, with products and an about page
3. [x] Can create a course as an elective in the program, with products and an about page
4. [x] "Financial assistance" CtAs appear in the appropriate spots - in the program dashboard cards, in the upsell cards, etc.
5. [x] Can submit and approve a financial assistance request for the program
6. [x] Personalized pricing displays appropriately on the course about pages
7. [x] Can enroll in the course programs
8. [x] After enrolling, the program appears successfully in the dashboard and displays all associated courses within the program
9. [x] Upgrading course enrollment results in the proper financial assistance tier being applied as discount

*Related Programs, No Overlapping Courses*

1. [x] Can create program, tiers, courseware page, and financial assistance request form
2. [x] Can create a course as a requirement in the program, with products and an about page
3. [x] Can create a course as an elective in the program, with products and an about page
4. [x] "Financial assistance" CtAs appear in the appropriate spots - in the program dashboard cards, in the upsell cards, etc.
5. [x] Can submit and approve a financial assistance request for the program
6. [x] Personalized pricing displays appropriately on the course about pages
7. [x] Can enroll in the course programs
8. [x] After enrolling, the program appears successfully in the dashboard and displays all associated courses within the program
9. [x] Upgrading course enrollment results in the proper financial assistance tier being applied as discount
10. [x] Can add a second program to the system, with a relation to the first, and complete the first three steps for it
12. [x] Personalized pricing appears in the courses assigned to the second program
12. [x] Can create a secondary financial assistance request page for the second program
13. [x] Attempting to apply for financial assistance should be disallowed
  - This delivered me to the approved page for the proper program (test program 2 rather than 1)
15. [ ] The dashboard should automatically see both related programs
16. [x] Enrolling in a course in the second program should result in a program enrollment for the second program; one should not exist prior to this

*Notes*: I only enrolled in the course in the second program for #16 - no upgrade. I didn't see the upsell card on the course details page for the other program I enrolled but did not upgrade in. I do see the upsell card on the dashboard page.

*Related Programs, Overlapping Courses*

1. [x] Can create program, tiers, courseware page, and financial assistance request form
2. [x] Can create a course as a requirement in the program, with products and an about page
3. [x] Can create a course as an elective in the program, with products and an about page
4. [x] "Financial assistance" CtAs appear in the appropriate spots - in the program dashboard cards, in the upsell cards, etc.
5. [x] Can add a second program to the system, with a relation to the first
6. [x] Can create a course as a requirement in the second program, with products and an about page
7. [x] Can add the new course to the first program as either a requirement or an elective
8. [x] Enrolling in the overlapping course should result in a program enrollment for both programs
9. [ ] After clearing program enrollments, enrolling in the non-overlapping courses should also result in a program enrollment in both
10. [x] After applying for financial assistance in the first program, personalized pricing should be shown in both program's courses

*Tiers Check*

1. [ ] After applying for financial assistance for a program with related programs, adjust one program so that the applied tier is better in one than the other. The tier with the better value should apply.
   - Should be noted that the request for program 1 approved me with the tiers for program 1 too, so even when checking out with a course only in program 2, I got the tiers for the first program.

**Comment by pdpinch** [comment]
@jkachel can this be closed?

**Comment by jkachel** [comment]
Think so, closing.
