### ISSUE TITLE
The program requirement operation titles should not be used in logic

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mitxonline#1695]
As a program administrator, when adding requirements to a program, defining the title of the operators in the requirements tree should be hard coded and not left up to the administrator.  This will ensure that requirements operator titles such as "Elective courses", "Required courses", and "One of" are reliably referenced throughout the code of our application.

#### Acceptance Criteria:

- [ ] Remove dependency on program requirement and elective operator titles for logic in code.
- [ ] Documentation is updated to reflect this.

**Comment by pdpinch** [comment]
I don't understand. "Elective" and "required" aren't operators, they are titles. The operators are "All of" and "Minimum # of" combined with a value. 

@rhysyngsun @jkachel do we have documentation somewhere on configuring program requirements?

**Comment by jkachel** [comment]
We enforce the root level ones in code; if you add an elective or a requirement through the Program model helper methods, it'll create either a "Elective Courses" or a "Required Courses" for you if they don't exist already. The `ProgramAdminForm` also enforces these if you open a program in Django Admin that doesn't have a requirements tree. There's nothing keeping someone from changing the titles later, though.

**Comment by rhysyngsun** [comment]
Those fields were supposed to be opaque values and up to the course team to decide on what's best, are we relying on them to be specific values?

**Comment by collinpreston** [comment]
@rhysyngsun https://github.com/mitodl/mitxonline/blob/56a164b3a25128cdb51aeac9ff9aba4a9d9204f3/frontend/public/src/containers/pages/records/LearnerRecordsPage.js#L93, frontend/public/src/containers/pages/records/LearnerRecordsPage.js, https://github.com/mitodl/mitxonline/blob/bc5a9a86364f1b30e2564360282e2a10dc7c4984/courses/models.py#L318, https://github.com/mitodl/mitxonline/blob/bc5a9a86364f1b30e2564360282e2a10dc7c4984/courses/models.py#L311

**Comment by pdpinch** [comment]
Well. I guess we broke that today. I named the titles to be descriptive of the courses, as intended. You can see it now in production. 

What’s the impact on the front end?

**Comment by collinpreston** [comment]
@pdpinch, I would probably change them back to the defaults.

**Comment by pdpinch** [comment]
It looks like this affects the program record. Anything else?

**Comment by collinpreston** [comment]
Having a value for the operation title which is not the default will likely impact more than just the program record.  It appears that our application _should_ only use this value for configuring the text shown in the badge for each course in the program record.

**Comment by pdpinch** [comment]
Ok, I reverted the original DEDP Program, and I can see that it affected the display of the program record. 

https://mitxonline.mit.edu/admin/courses/program/1/change/

I left the new DEDP Program as is, since it's new to everyone anyway. 

https://mitxonline.mit.edu/admin/courses/program/2/change/ 

We need to find a way to balance between UI text that we want to be customizable and functional settings. And we need to make the distinction clear in the code so we don't drift like this in the future.
