### ISSUE TITLE
Increase efficiency for program enrollments API

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#1700]
The program enrollments API call (`/api/program_enrollments`) is pretty slow - testing locally, it generates a bunch of n+1 errors and it takes many seconds to resolve (tested at ~10s with debug turned on and ~3 with it turned off).

### Steps to Reproduce

Observe the program enrollments API.

### Expected Behavior

It returns enrollments in a reasonable timeframe.

### Actual Behavior

It takes several seconds to return data.

**Comment by pdpinch** [comment]
Seems like this is still very slow, at least on rc.mitxonline.mit.edu. What more can we do?

**Comment by jkachel** [comment]
#1708 wasn't intended to be the last word in this; there's still a bunch of n+1s that need investigation and we can/should also look at how the frontend uses the APIs, and either optimize that usage, create new/refactor existing APIs that provide the data, or do more processing on the client side. (Or maybe all of those.)
