### ISSUE TITLE
Remove usage of deprecated github actions commands

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#1711]
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The current documentation on how to do this is here: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files

I think the usage it's warning on is here: https://github.com/mitodl/mitxonline/blob/main/.github/workflows/ci.yml#L149

**Comment by cp-at-mit** [comment]
This issues appears to no longer be applicable.  Verified with Nathan.  Closing.
