### ISSUE TITLE
Open edX: hide "Order History" from the MFE user menu when it isn't configured

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#172]
As a open edX operator, I'd like to be able to run the site without ecommerce (i.e. courses are free). If I don't configure a URL for "Order History" it shouldn't appear in the user menu. 

#### Acceptance Criteria:

- [x] Upstream PR to https://github.com/edx/frontend-component-header-edx/
- [x] If `ORDER_HISTORY_URL` is not set at build time, "Order History" should be omitted from the component. 

#### Related issues 

We have a couple of other MFE issues currently open:

- #132 
- #162

**Comment by pdpinch** [comment]
Wow, your PR was merged fast! If I had a chance to review, I would have asked for the commit message to follow conventional commmits. I think you just needed a "fix: " at the start of it.

**Comment by umarmughal824** [comment]
@pdpinch As the upstream PR is merged so what's next should I close this ticket?

**Comment by pdpinch** [comment]
Can you coordinate with @mitodl/devops to:

1. Configure the setting for `ORDER_HISTORY_URL`
2. deploy the MFE to the various mitxonline instances

**Comment by blarghmatey** [comment]
What is the intended destination for that URL?

**Comment by umarmughal824** [comment]
@blarghmatey I have merged the PR in upstream with working screenshots, there you could get the idea from these screenshots https://github.com/edx/frontend-component-header-edx/pull/161

**Comment by blarghmatey** [comment]
Thanks, understood now. We'll update the build to set that to an empty value to hide the link.

**Comment by blarghmatey** [comment]
I set the value for the learner MFE build, but it seems that we'll need to wait for that project to update its dependencies to use the newer version of the header component.

**Comment by umarmughal824** [comment]
@pdpinch @blarghmatey they have already created a new release after merging my PR https://github.com/edx/frontend-component-header-edx/releases/tag/v5.0.12

**Comment by pdpinch** [comment]
What's the dependency chain from front-app-learning to frontend-component-header-edx? Do we need to open another PR (or PRs) to see Umar's change?

**Comment by umarmughal824** [comment]
> What's the dependency chain from front-app-learning to frontend-component-header-edx? Do we need to open another PR (or PRs) to see Umar's change?

@blarghmatey could you please confirm that?

**Comment by pdpinch** [comment]
I think we need to also make this change in [`frontend-component-header`](https://github.com/edx/frontend-component-header/)

See https://github.com/openedx/build-test-release-wg/issues/109#issuecomment-974658913

It sounds like someone from OpenCraft is planning to open a PR

**Comment by asadiqbal08** [comment]
I believe, It should be fixed now as some of the Header MFE PRs are merged and we added the [corresponding condition](https://github.com/mitodl/frontend-component-header-mitol/blob/master/src/learning-header/AuthenticatedUserDropdown.jsx#L38-L42) there to take care of it. We need to test it after deployment. Any instance where we have deployed the [frontend-component-header-mitol](https://github.com/mitodl/frontend-component-header-mitol)

@pdpinch @blarghmatey @Wassaf-Shahzad

**Comment by pdpinch** [comment]
@briangrossman @asadiqbal08 can we close this?

**Comment by briangrossman** [comment]
@pdpinch Yes. Now we can.
