### ISSUE TITLE
Letter grade is set to None when grade is populated through a management command

### ISSUE THREAD

**Issue by annagav** [mitodl/mitxonline#1762]
### Steps to Reproduce
Example course run grade id 43640.

I noticed that some grades are missing `letter_grade` value. We think that happens through the management command `manage_certificates`.  If `is_grade_override` is true then we set letter grade to None: [code here]
(https://github.com/mitodl/mitxonline/blob/2f951479e328c2a9f9d21d79f84fc3e04837ff43/courses/api.py#L871-L897)
### Expected Behavior

If the grade is passing and enrollment verified we need an actual letter grade.

### Actual Behavior

The learner is missing a letter grade.

<img width="688" alt="Screen Shot 2023-07-20 at 8 51 09 AM" src="https://github.com/mitodl/mitxonline/assets/7574259/c69a7458-9b0c-4886-9ce9-730d3228e86f">

**Comment by pdpinch** [comment]
When we pass a grade to the management command, we should require a letter grade (string) as well.

**Comment by pdpinch** [comment]
> Example course run grade id 43640.

Solving this issue also requires doing a search for other missing letter grades and fixing them up. If the courses are DEDP courses, it's straightforward since they always use the same grading policy. If there are missing letter grades from other courses, we will have to look at their grading policy in Studio.

**Comment by arslanashraf7** [comment]
@pdpinch FYI.

>Solving this issue also requires doing a search for other missing letter grades and fixing them up. If the courses are DEDP courses, it's straightforward since they always use the same grading policy. If there are missing letter grades from other courses, we will have to look at their grading policy in Studio.


This might be difficult in the sense that, a `None` letter grade in Django would not mean that it was only set by the override command. So, To reduce the scope, We can check those grades that are `set_by_admin=True` to back fill the data.

Also, Just to add more thoughts to what's already defined above:

1. I believe that the Letter grade from edX can have possible values (`A`, `B`, `C`, `D`, `E`, `F`, `Pass`, `Fail`, `None`)
2. So, along with the override management command, The grade can come as `None` from edX as well.
3. I think we'll need to update validation on letter grade as defined [here in the PR](https://github.com/mitodl/mitxonline/pull/1767/files#diff-1891631991481dca5fef7d88592f36f41fe1422ddc3f13e172d8973bc77c8da6R30-R32)
4. Usually, The `Pass`/`Fail` comes when there is a 50/50 grading policy set which is also the default in edX.


See some screenshots below:
<img width="973" alt="image" src="https://github.com/mitodl/mitxonline/assets/34372316/be2c534b-c844-46f2-bc3e-d593fc9514b3">
<img width="960" alt="image" src="https://github.com/mitodl/mitxonline/assets/34372316/fddaa59b-9bac-495e-9c6a-861c84983dbf">

**Comment by annagav** [comment]
@pdpinch @arslanashraf7 The problem we are having is not about all grades, but about grades that we have to show on the Program Records page. Those grades only belong to a program and those grades are only for certificate track learners. We need to have these letter be consistently A-F.

**Comment by pdpinch** [comment]
I'm OK with omitting the pass/fail option if it's a big lift. I think it's unlikely that we will need it. And I assume we can add it if/when we do.

**Comment by annagav** [comment]
@arslanashraf7 In what scenario would letter_grade come from edx as None?

**Comment by annagav** [comment]
Given that we don't have a clear direction with this, I will create a migration to populate only DEDP grades that were set by admin.

**Comment by arslanashraf7** [comment]
> @arslanashraf7 In what scenario would letter_grade come from edx as None?

I believe that happened in cases when the completion of the course by the user is not done e.g. in a Self-paced course and in instructor-paced courses when the grades are not finalized and persisted.

**Comment by annagav** [comment]
We populated all DEDP grades and we set a restriction on the management command to provide letter_grade
