### ISSUE TITLE
Design regression on Authentication, Registration Profile forms

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/mitxonline#178]
### Steps to Reproduce
- Visit any of these links ([Sign In](https://rc.mitxonline.mit.edu/signin/), [Register](https://rc.mitxonline.mit.edu/create-account/), [Forgot Password](https://rc.mitxonline.mit.edu/signin/forgot-password/)) in Mobile view
- You can check that the form width matches the window and it gives non-card look and feel
- You can see the screenshots below

**Note:**
- I suspect that this issue will also be on settings, profile pages as well, so you might want to take a look at them too.
- I couldn't find a related Invision design so I didn't add a link to that.

### Expected Behavior
- There should be some horizontal margin to the forms container so that it gives a card like look & feel similar to the desktop

### Actual Behavior
- The container matches the width of the window and it loses the card like feel

### Screenshot or Screencast
<img width="508" alt="Screenshot 2021-09-10 at 7 42 35 PM" src="https://user-images.githubusercontent.com/34372316/132872948-02cfa41c-fde0-42bd-b601-ed8c2b242a86.png">
<img width="564" alt="Screenshot 2021-09-10 at 7 42 55 PM" src="https://user-images.githubusercontent.com/34372316/132872956-fb552f9d-2009-4abc-964a-495faa1a43ee.png">
<img width="521" alt="Screenshot 2021-09-10 at 7 44 15 PM" src="https://user-images.githubusercontent.com/34372316/132872962-b0f7490b-7816-491c-91d6-3a574a168be2.png">

**Comment by arslanashraf7** [comment]
@pdpinch created the relevant issue based on https://github.com/mitodl/mitxonline/pull/169#pullrequestreview-751157845.

**Comment by gsidebo** [comment]
FYI I'm taking care of this as part of #175 since I'm already updating a lot of this code
