### ISSUE TITLE
Profile Page form validation—invalid regex

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mitxonline#1788]
### Steps to Reproduce

1. Visit https://mitxonline.mit.edu/profile/
2. View console logs, and observe:
```
mitxonline.mit.edu/:1 Pattern attribute value ^(?![~!@&)(+:'.?,-]+)([^/\^$#*=[\]`%_;<>{}"|]+)$ is not a valid regular 
expression: Uncaught SyntaxError: Invalid regular expression: /^(?![~!@&)(+:'.?,-]+)([^/\^$#*=[\]`%_;<>{}"|]+)$/v: Invalid 
character in character class
```

_Tested in Chrome_

### Expected Behavior

No error in console; form gives useful error for bad 

### Actual Behavior

Form submits, backend errors, no visible error message, form resets

**Comment by rachellougee** [comment]
This is the same issue as https://github.com/mitodl/mitxonline/issues/1813 that I am looking at
The [NAME_REGEX](https://github.com/mitodl/mitxonline/blob/main/frontend/public/src/components/forms/ProfileFormFields.js#L26)  is not valid regular expression per RegExp v flag, but there are also other issues on this form

**Comment by pdpinch** [comment]
@rachellougee @ChristopherChudzicki can this be closed?

**Comment by ChristopherChudzicki** [comment]
Yes.
