### ISSUE TITLE
Implement basic site footer content

### ISSUE THREAD

**Issue by gsidebo** [mitodl/mitxonline#18]
Design: https://projects.invisionapp.com/share/KH11D3ZN53GC#/screens/455535008 (featured on all pages)

**Acceptance criteria:**
- Footer appears on all pages
- Footer contains logo and all relevant text, and matches the designs at all screen widths

**Not needed:**
- Working links to the resource pages (about us, terms of service, etc.)
- "Sign up" text input and button (this section can be left out completely

**Comment by umarmughal824** [comment]
@pdpinch I need the logo being used in the footer in the invision deisgn.

**Comment by pdpinch** [comment]
It should be in InVision. If you can't get it from there, can you get it from the xPRO site?

**Comment by pdpinch** [comment]
Nevermind, I can see the image file is missing from InVision. I left a note for the designer.
