### ISSUE TITLE
regex error on create-account/details form

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1813]
### Steps to Reproduce

1. Create a new account at https://rc.mitxonline.mit.edu/create-account/
2. Click on the link in the verification email
3. Start typing in the form.

### Expected Behavior

Shouldn't get any errors in the console. 

### Actual Behavior

In Firefox, I get the error: 

`Unable to check <input pattern='^(?![~!@&)(+:'.?,-]+)([^/\^$#*=[\]`%_;<>{}"|]+)$'> because the pattern is not a valid regexp: invalid character in class in regular expression`

It does not prevent me from submitting the form, but we have a [ticket](https://odl.zendesk.com/agent/tickets/211525) (browser unknown) from a user saying that the continue button doesn't function.

**Comment by collinpreston** [comment]
Possibly related to https://github.com/mitodl/mitxonline/issues/1788
