### ISSUE TITLE
Some images are being loaded from github

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1815]
### Steps to Reproduce

1. Visit a page on production open edx, like https://courses.mitxonline.mit.edu/learn/course/course-v1:MITxT+14.310x+3T2022/home

### Expected Behavior

All MIT-specific resources should be loaded from mitxonline.mit.edu or the CDN. 

### Actual Behavior

logo.png and favicon.ico are loading from **_githubusercontent.com!_**

### Screenshot or Screencast

<img width="1422" alt="image" src="https://github.com/mitodl/mitxonline/assets/430126/3f081eeb-8d1d-4415-8896-1449a858216c">

**Comment by pdpinch** [comment]
Once we figure out how this is happening, we should take a look at xPRO and Residential as well.

**Comment by asadali145** [comment]
These images are kept in our code base as static assets https://github.com/mitodl/mitxpro-theme/tree/master/lms/static/images. Actually, we have just overridden it. This is how edX does https://github.com/mitodl/edx-platform/tree/master/lms/static/images and we cannot do anything about this. If we still want to do something about it please let me know.

CC: @pdpinch

**Comment by pdpinch** [comment]
I understand these are the correct images, but the URLs are wrong. End-users shouldn't be getting these images via github.com URLs. They should be coming from courses.mitxonline.mit.edu, or maybe the CDN. 

@mitodl/devops is there something wrong with our configuration, or the deployment of this theme? 

I did a [quick search of the theme repo](https://github.com/search?q=repo%3Amitodl%2Fmitxonline-theme+raw.githubusercontent.com&type=code) and didn't see any hard-coded links to raw.githubusercontent

**Comment by asadali145** [comment]
This happens for the learning MFE only. For all the other tabs like progress, the URL is https://courses.mitxonline.mit.edu/static/mitxonline/images/logo.0a44f80f6467.png. Not really sure what's wrong with the learning MFE. Digging a bit more into the Learning MFE.

**Comment by asadali145** [comment]
logo.png and favicon.ico are set in .env and are coming from https://github.com/mitodl/ol-infrastructure/blob/c30a498638c6f2cfda797724f579e91687e76c33/src/ol_concourse/pipelines/open_edx/mfe/values.py#L10. @mitodl/devops | @blarghmatey Could we change this?

**Comment by shaidar** [comment]
This can be changed and will require us to update the pipeline to push those images to S3 and then load them through Fastly instead of GitHub.

**Comment by pdpinch** [comment]
> update the pipeline to push those images to S3 and then load them through Fastly instead of GitHub.

@blarghmatey how big of an effort is this?  

We're updating the logos now in https://github.com/mitodl/ol-infrastructure/pull/2270 and it just seems wrong to me to serve them from raw.githubusercontent.com!

**Comment by asadali145** [comment]
> We're updating the logos now in https://github.com/mitodl/ol-infrastructure/pull/2270 and it just seems wrong to me to serve them from raw.githubusercontent.com!

@pdpinch Tobias was suggesting the use of `raw.githubusercontent.com` in https://github.com/mitodl/hq/discussions/3778#discussioncomment-8801934. I think he missed your above comment. Should I use GitHub for MITx or should I wait?

@blarghmatey FYI

**Comment by blarghmatey** [comment]
@pdpinch is this ready to be closed now?

**Comment by pdpinch** [comment]
I'm still seeing the logo and two (?) requests for the favicon going to raw.githubusercontent.com from the page at https://courses.mitxonline.mit.edu/learn/course/course-v1:MITxT+14.310x+3T2022/home

https://raw.githubusercontent.com/mitodl/mitxonline-theme/main/lms/static/images/logo.png
https://raw.githubusercontent.com/mitodl/mitxonline-theme/main/lms/static/images/favicon.ico

<img width="1608" alt="image" src="https://github.com/mitodl/mitxonline/assets/430126/6634aa93-74ea-4410-bc6d-2e7b3ad15b25">

On the Studio side, everything seems to come from courses.mitxonline.mit.edu, which is better. I tested an [MFE page](https://studio.mitxonline.mit.edu/course-authoring/course/course-v1:MITxT+14.310x+3T2022/pages-and-resources) and a [legacy theme page](https://studio.mitxonline.mit.edu/home/).

**Comment by blarghmatey** [comment]
The corresponding logos in QA are loading from the theme rather than GitHub, so I am going to close this as all of the necessary configuration changes have been made. We are just waiting on a production deploy of edX and MFEs for MITx Online.
