### ISSUE TITLE
Add ability to create and associate a department with a course/program using create_courseware command

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mitxonline#1836]
As an administrator, I would like to be able to create and/or associate a Department with a Course or Program when creating a new Course or Program using the create_courseware command.
#### Acceptance Criteria:

- [ ] When creating a Course using the create_courseware command, an existing Department can be associated with the new Course.
- [ ] When creating a Course using the create_courseware command, a new Department can be created and associated with the new Course
- [ ] - [ ] When creating a Program using the create_courseware command, an existing Department can be associated with the new Course.
- [ ] When creating a Program using the create_courseware command, a new Department can be created and associated with the new Course

**Comment by jkachel** [comment]
closing this as resolved by https://github.com/mitodl/mitxonline/pull/1887
