### ISSUE TITLE
Homepage 500s due to using the python sdk rather than initializing at the app level

### ISSUE THREAD

**Issue by JenniWhitman** [mitodl/mitxonline#1850]
### Steps to Reproduce

When installing initially, we had used the python SDK rather than the Django implementation. This is causing 500 errors on RC now.

[more context](https://mitodl.slack.com/archives/C02649X2P1V/p1693507094521869)

**Comment by pdpinch** [comment]
I think this is the relevant sentry error: https://mit-office-of-digital-learning.sentry.io/issues/4443267622/?referrer=github_integration
