### ISSUE TITLE
Apply new classnames to the course about page

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#1862]
This is mostly for me from the discussion in the planning meeting this (9/5) morning.

### Actual Behavior

The course about page reuses some class names between the new design and the old. These should be separated out and redone so that they don't step on each other anymore, allowing us to include both CSS files in the built stylesheet. 

### Related Issues

#1838 
#1840 
#1773 
https://github.com/mitodl/hq/issues/1542

**Comment by pdpinch** [comment]
Is this still an issue?

**Comment by jkachel** [comment]
Closing this as it's not a thing anymore.
