### ISSUE TITLE
Add customer support footer

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#188]
As a user, I'd like to be able to easily find answers to FAQs and contact customer support. 

Once an mitxonline help center is setup in ZenDesk, we can add a footer similar to the ones we have on xPRO and Bootcamps, with a FAQ link and a Contact Us Link

#### Designs and Mockups

Use the xPRO version as a model
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/430126/133181601-d45f2d4c-8b53-44d0-ba1e-9b7b743459e8.png">

#### Acceptance Criteria:

- [x] Position footer directly above the general site footer (on all MITx Online pages)
- [x] Link to Help & FAQ - https://mitxonline.zendesk.com/hc/en-us
- [x] Link to Contact Us - https://mitxonline.zendesk.com/hc/en-us/requests/new
- [x] Update fonts to match the MITx Online fonts
- [x] Background color of the customer support footer should be ![#FFFFFF](https://via.placeholder.com/15/FFFFFF/000000?text=+) `#FFFFFF`
- [x] Add a horizontal rule above the customer support footer (similar to the [Zendesk page](https://mitxonline.zendesk.com/hc/en-us)) of color ![#C2C2C2](https://via.placeholder.com/15/C2C2C2/000000?text=+) `#C2C2C2` 

![Screen Shot 2022-01-11 at 12 16 57 PM](https://user-images.githubusercontent.com/21342568/148990743-5a3e62b0-38b1-4851-96b9-0efe070ee3ea.png)

#### Related Issues

- [x] #189

**Comment by pdpinch** [comment]
@arslanashraf7 I think we can close this now?

**Comment by arslanashraf7** [comment]
Yes, This has been deployed on production & I've also verified it.
