### ISSUE TITLE
Dropdown menu does not open

### ISSUE THREAD

**Issue by annagav** [mitodl/mitxonline#1896]
This issue is on https://rc.mitxonline.mit.edu/. This issue seems to be independent of the `mitxonline-new-header
` feature flag.
## Expected Behavior
When I click the arrow dropdown menu should open
<img width="205" alt="Screen Shot 2023-09-18 at 9 27 36 AM" src="https://github.com/mitodl/mitxonline/assets/7574259/3c28bb10-8ca9-4584-aed0-cfd87e268558">

## Current Behavior
The arrow flips but no menu is opened.
<img width="204" alt="Screen Shot 2023-09-18 at 9 28 40 AM" src="https://github.com/mitodl/mitxonline/assets/7574259/efbaa07a-667e-4c8d-b07d-cf40584397b9">

**Comment by collinpreston** [comment]
Appears the cause is: https://github.com/mitodl/mitxonline/blob/c3fbddebfe11bfdb6f4ad018d23ecc5b41d4ca13/frontend/public/scss/home-page/home-page-hero.scss#L9

**Comment by JenniWhitman** [comment]
@collinpreston  This makes more sense than what I was thinking - can remove that and see if it still sits above the featured carousel, if not, drop that number back... more than a bit.

**Comment by JenniWhitman** [comment]
@collinpreston you're correct. I have a literal one line PR from me testing that locally
