### ISSUE TITLE
Allow new users to choose username when creating account

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#191]
As a user, I'd like to be able to choose my username when I create an account, instead of having one autogenerated using my name. This will allow me to control my identity on open edX discussions forums, and allow course teams to connect users without sharing my PII. 

#### Designs and Mockups

Design (elements): https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/458325008/preview?scrollOffset=1869.5999755859375

#### Acceptance Criteria:

- [ ] Add a field to the account creation form for setting username
- [ ] validate that the username is unique when creating an account. 
  - [ ] for this issue, it's OK if validation is on submit only. We may do a follow up later to validate uniquess on the front-end. 
  - [ ] If it is unique on mitxonline, it should also be unique on edx-platform
- [ ] we should do some manual integration testing with MicroMasters before releasing this, but I would be very surprised if there are any issues

#### Out of Scope

- Auto-generate suggestions for a username. To do this right, we really need a way to do front-end validation on uniqueness, so we're not auto-generating suggestions that are not unique. 
- We should consider allowing users to change their username, but that's out of scope for now. We can handle username changes as a customer service request.

**Comment by gsidebo** [comment]
@pdpinch Will it be OK to validate the username uniqueness on submit (as opposed to validating on key press)?

**Comment by pdpinch** [comment]
Validating on submit is going to be a lot easier, isn’t it? I’m fine starting with submit and then we can consider validation on keypress later.

**Comment by gsidebo** [comment]
@pdpinch What do you think of auto-generating a username on the front end based on the full name? I was thinking something like this: as the user enters their full name (on each key press), that input value is slug-ified and set as the value of the username field, but _only_ if the user has not manually entered anything in the username field. If the user _has_ entered something there, any further input in the full name field will not update the username field. 

This would make it easier for the user in 2 ways: (1) potentially one less input to fill out, and (2) less likely to enter an invalid username which they would then have to fix.

I'm guessing you'd want to put that in a separate issue if you like the idea, but thought it was worth pitching here

**Comment by pdpinch** [comment]
I updated the description with a link to the design. To be clear, the design includes features that we aren't implementing at this time. Namely: front-end validation of uniqueness and auto-generating suggested usernames.
