### ISSUE TITLE
Learners that completed DEDP before the split need to see their certificate

### ISSUE THREAD

**Issue by annagav** [mitodl/mitxonline#1934]
14.009x used to be one of the electives for DEDP. Now that the Program was split into 2 programs 14.009x belongs only to one of the programs. So now the user has one elective passed in one program, and one in the other.
 
Based on the rules from before the separation the learner would have earned the program certificate.

Related issues:
https://github.com/mitodl/hq/issues/1861
https://github.com/mitodl/hq/issues/2501
https://github.com/mitodl/hq/issues/2499
https://github.com/mitodl/hq/issues/2685
https://github.com/mitodl/hq/issues/2681
https://github.com/mitodl/hq/issues/2680
https://github.com/mitodl/hq/issues/2678
https://github.com/mitodl/hq/issues/2699
https://github.com/mitodl/hq/issues/2696

## Expected Behavior
Learner that completed requirements for old program should receive their certificate.

## Current Behavior
The learner does not receive a program certificate.

**Comment by annagav** [comment]
What needs to be done:

1. Create a new hidden program.
2. Enroll select users in the program. I think the title would need to change not to confuse it with current DEDP program.
3. Make sure that program shows on their dashboard.
4. Generate certificates for this program.
5. Make sure they can see the certificate on their dashboard.

**Comment by pdpinch** [comment]
Can we try this on RC first?

**Comment by pdpinch** [comment]
We can give the "legacy" program an id of `program-v1:MITx+DEDP+2T2023` because these were folks who passed 14.009x in 2T2023

**Comment by annagav** [comment]
I tested this on RC, everything seems to have worked 👍 
I am ready to do this in production.

**Comment by pdpinch** [comment]
Great, thanks. What's the process for generating a certificate for a learner? 

Can you give me some links to take a quick look at? I'd like to see what the program looks like in django admin, and also what a certificate looks like.

**Comment by annagav** [comment]
I just created a certificate manually in the django admin for my user https://rc.mitxonline.mit.edu/admin/courses/programcertificate/. You can then view the certificate on the user's dashboard. You can view my users certificate `annagav2`.

**Comment by pdpinch** [comment]
Ok, so in production, we would create ~7 certificates manually and we're done?

**Comment by annagav** [comment]
Here is what the dashboard looks like for these users:
No certificate yet:
<img width="1498" alt="Screen Shot 2023-10-18 at 12 51 13 PM" src="https://github.com/mitodl/mitxonline/assets/7574259/5c553bbf-4ec0-427e-8b95-3f4178ec4b6e">
Earned a certificate
<img width="1438" alt="Screen Shot 2023-10-18 at 12 58 16 PM" src="https://github.com/mitodl/mitxonline/assets/7574259/540c95fe-6f05-4eb7-bc0f-84bc7c2c4920">

**Comment by annagav** [comment]
Another ticket https://github.com/mitodl/hq/issues/3161

**Comment by annagav** [comment]
Another ticket https://github.com/mitodl/hq/issues/2615
