### ISSUE TITLE
Integrate Keycloak authentication

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mitxonline#2049]
Implement a functional Keycloak authentication, this should be an MVP implementation - manual navigation to a django-social-auth URL is adequate for now.

Requirements
User can login to Open Discussions via Keycloak in QA and CI environments.
Out of Scope
UI/UX customizations on either this app or Keycloak

**Comment by pdpinch** [comment]
replaced by https://github.com/mitodl/hq/issues/5664
