### ISSUE TITLE
Remove usages of EDX_API_KEY

### ISSUE THREAD

**Issue by asadali145** [mitodl/mitxonline#2102]
Open edX is going to remove the EDX_API_KEY. Details can be found at https://github.com/openedx/edx-platform/issues/34039. We have a couple of stale usages that we want to remove. We are using the EDX_API_KEY with the token authentication and we can safely remove EDX_API_KEY as per [initial R&D](https://mitodl.slack.com/archives/G72L6SNHH/p1705391842381199?thread_ts=1704997677.222519&cid=G72L6SNHH).

Here are the usages:

- https://github.com/mitodl/mitxonline/blob/3ca0128d969cb179fa4afa31a8c998f50df96e76/openedx/api.py#L490
- https://github.com/mitodl/mitxonline/blob/3ca0128d969cb179fa4afa31a8c998f50df96e76/openedx/api.py#L509
- Settings and docker-compose

#### Acceptance Criteria:

- [ ] Usage of EDX_API_KEY is removed
- [ ] No impact on any of the features or management commands

#### Similar Issues
https://github.com/mitodl/mitxpro/issues/2872
https://github.com/mitodl/edx-api-client/issues/103

#### Out of Scope

- Changes in [edx-api-client](https://github.com/mitodl/edx-api-client) are out of scope

**Comment by mudassir-hafeez** [comment]
Closing [#2102](https://github.com/mitodl/mitxonline/issues/2102) as https://github.com/mitodl/mitxonline/pull/2217 and https://github.com/mitodl/edx-api-client/issues/103 have been deployed to production.
