### ISSUE TITLE
Implement logged-in UI in the site header

### ISSUE THREAD

**Issue by gsidebo** [mitodl/mitxonline#22]
Related: #21 

**Acceptance criteria:**
- When logged-in, the user's first name with a downward arrow are shown in the site header in non-mobile widths, and they match the designs
- Clicking the logged-in user's name or the arrow reveals a dropdown with working links that match the designs (with the exception of "Change password")
  - *NOTE:* For now, the look and feel of the dropdown can be the same for desktop and mobile views

**Not needed:**
- "Change password" link – Right now, this form is included in the Settings page. If we implement this as a separate page, that can be done in a separate issue
- "Help" link – This can be done in a separate issue
- Fixing the styling of the hamburger menu or overlay menu options in mobile view (https://github.com/mitodl/mitxonline/issues/23)

**Comment by umarmughal824** [comment]
@arslanashraf7 this is related to what you are doing in #23 so it would be quick for you.

**Comment by pdpinch** [comment]
Does PR https://github.com/mitodl/mitxonline/pull/37 fix this?

**Comment by arslanashraf7** [comment]
> Does PR #37 fix this?

I believe this ticket points to the other iteration of the top bar design as mentioned in the ticket acceptance criteria:
>When logged-in, the user's first name with a downward arrow are shown in the site header in non-mobile widths, and they match the designs

I assume this ticket points towards the TopBar design of this [Invision Screen](https://projects.invisionapp.com/share/KH11D3ZN53GC#/screens/455498561), In which case this is not fixed/closed by #37 .
