### ISSUE TITLE
Link users to edX from product detail if run is in progress

### ISSUE THREAD

**Issue by gsidebo** [mitodl/mitxonline#222]
### Steps to Reproduce

- Log in
- Enroll in a course run
- Set the course run dates so that the enrollment period is in the past, but the run is in progress according to the start and end dates
- Visit the product detail page for that run

### Expected Behavior

The UI shows the "Enrolled" UI and links the user to the course in edX

### Actual Behavior

If a future course run exists, the "Enroll Now" button is shown for that future course run. Otherwise, the button is omitted completely

### Related Issues

#187 
#207 
#221 

### Background

We migrated a lot of code from mitxpro for this app. In this app, we want the product detail page to link to edX for logged-in users if they are enrolled in an in-progress run, and in mitxpro we either weren't using the product detail page for that purpose, or the bug exists there as well.

**Comment by briangrossman** [comment]
I tested this on xPRO and did not see this problem. 👍
