### ISSUE TITLE
Enrollment issue when user unenrolls and enrolls again and pays

### ISSUE THREAD

**Issue by annagav** [mitodl/mitxonline#2225]
Related to this issue https://github.com/mitodl/hq/issues/4367

the user has enrolled in audit then unenrolled from the run, then they enrolled in verified. As a result their status in the courseware is verified, but active is False.
### Expected Behavior
When user pays and enrolls in verified track the enrollment in edx should be active.

### Current Behavior
The user can't access the course bc their enrollment is not active.

**Comment by collinpreston** [comment]
@annagav, where you able to reproduce this issue locally or in RC?

**Comment by annagav** [comment]
no, I don't think so

**Comment by collinpreston** [comment]
I have not been able to reproduce this bug following the steps in this issue.

**Comment by annagav** [comment]
If a user has paid for a course run and they want to unenroll:

1. Don't allow. Need to contact CS.
2. Allow to unenroll. Decide what to do with the payment: Order, PaidCourseRun, etc.
