### ISSUE TITLE
Catalog shows "Started November 9th" when course is actually archived

### ISSUE THREAD

**Issue by annagav** [mitodl/mitxonline#2357]
Here is the course https://mitxonline.mit.edu/courses/course-v1:MITxT+24.118x/

Here is the Catalog: https://mitxonline.mit.edu/catalog/courses/linguistics-and-philosophy

Instead the catalog should say "Start Anytime"

**Comment by annagav** [comment]
If the course is self-paced then we show "Start anytime". If the course is archived but is not self-paced we show the start date.

**Comment by pdpinch** [comment]
@annagav can I get some more detail here about what the issue was and how it was fixed? This is for our future selves, when a question comes up about this in the future.
