### ISSUE TITLE
Post save CourseRunCertificate signal doesn't work

### ISSUE THREAD

**Issue by annagav** [mitodl/mitxonline#2365]
The program certificates don't get created for DEDP (maybe other programs too) as a result of a post_save signal from CourseRunCertificate.
Related issue https://github.com/mitodl/hq/issues/5287

### Expected Behavior
Program certificates should get generated automatically for all live programs.

### Current Behavior
Users not getting their program certificates.

### Steps to Reproduce
Get certificates for all course requirements in the program. On creation the signal should call generate_program_certificate, but it doesn't.

**Comment by pdpinch** [comment]
Can signals log errors?

**Comment by annagav** [comment]
Yes, I can have a signal log something, but not if it never gets called.

I played around with this and it looks like when I manually import the signal in the django shell then it seems to work fine.
