### ISSUE TITLE
CI failing on main branch (Python tests)

### ISSUE THREAD

**Issue by pt2302** [mitodl/mitxonline#2382]
### Expected Behavior
Python tests should be passing.

### Current Behavior
Python tests are failing with this error:

`
/home/runner/work/mitxonline/mitxonline/frontend/staff-dashboard/build System check identified some issues: WARNINGS: ?: (urls.W005) URL namespace 'v1' isn't unique. You may not be able to reverse all URLs in this namespace cms.CoursePage.topics: (fields.W340) null has no effect on ManyToManyField. Migrations for 'courses': courses/migrations/0055_alter_program_availability.py - Alter field availability on program
`

Just attempting to apply migrations does not resolve this issue.

**Comment by pdpinch** [comment]
I thought maybe https://github.com/mitodl/mitxonline/pull/2367 would have fixed this?
