### ISSUE TITLE
open edX: Enable Video Uploads in Content menu in Studio

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#27]
Please enable `Video Uploads` in the `Content` menu in Studio. 

#### Designs and Mockups

Menu in MITx Online
![Screen Shot 2021-07-21 at 3 59 11 PM](https://user-images.githubusercontent.com/21342568/126554288-335e00f9-5ace-4064-8f7f-3ae56304a46b.png)

Menu in xPRO
![Screen Shot 2021-07-21 at 3 59 45 PM](https://user-images.githubusercontent.com/21342568/126554384-bd9378e2-68b5-4936-ac6d-6750809fc947.png)

**Comment by blarghmatey** [comment]
@shaidar this is likely just a configuration change, but it may require the addition of an S3 bucket as a destination.

**Comment by pdpinch** [comment]
To be clear, the goal here is the same functionality as xPRO. In other words, there is no video upload from this UI, just a list of existing videos in the course and the ability to upload thumbnails and caption files.

**Comment by pdpinch** [comment]
This is working now, for example, at https://studio-qa.mitxonline.mit.edu/videos/course-v1:UGross+BrianCourse+R1
