### ISSUE TITLE
Enable all course staff to be able to download grade and ORA reports

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#275]
As a member of the course staff team (e.g. course data researchers), I'd like to have access to the grade and ORA reports on the `Data Download` tab in the `Instructor Dashboard` in the LMS. Current these reports are not available to everyone. 

#### Details

Peter did some fine sleuthing and it looks like these reports are toggled conditionally using a variable: `ALLOW_COURSE_STAFF_GRADE_DOWNLOADS` ([code](https://github.com/edx/edx-platform/blob/master/lms/templates/instructor/instructor_dashboard_2/data_download.html#L95-L108)). This likely needs to be set to `true`.

#### Designs and Mockups

Tabs
![image](https://user-images.githubusercontent.com/21342568/139496769-7fa2e164-53d3-4c0e-90bc-cb63854bf69d.png)

Data Download Page
![c44adb80-318e-11ec-8501-5b3cf78bc20b](https://user-images.githubusercontent.com/21342568/139496889-d771a0ef-9476-46e8-8ec6-14a8d60fadde.png)

#### Acceptance Criteria:

- [ ] Confirm that `ALLOW_COURSE_STAFF_GRADE_DOWNLOADS` is responsible for the reports not appearing
- [ ] Determine where the variable is set and set it to true

**Comment by Wassaf-Shahzad** [comment]
I have done the required R&D and as expected the environment variable `ALLOW_COURSE_STAFF_GRADE_DOWNLOADS` does enable/disable the download of grades and ORA reports, Provided the access role of the staff user is  `data researcher`. However on going through mitodl/salt-ops repository we discovered the value of `ALLOW_COURSE_STAFF_GRADE_DOWNLOADS`  has already been set to true
This can be viewed on the following files

- pillar/devstack.sh
- pillar/edx/ansible_vars/cloud_deployment.sls

**Comment by pdpinch** [comment]
Is the ALLOW_COURSE_STAFF_GRADE_DOWNLOADS variable set in ol-infrastructure?

We use the ol-infrastructure repo to build open edx for mitxonline. We are phasing out salt-ops, but it is still used for Residential MITx, and xPRO.
