### ISSUE TITLE
Accessibility: Created account initial form submission not apparent to screen readers

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#276]
### Steps to Reproduce

When a screen reader user submits the first account creation form (where they enter their email), they do not get an alert to know that a message "We've sent you email" appears. They do not know that the text on the screen has been updated.

### Expected Behavior

The focus should shift when the page changes to the new content such that the screen reader is redirected to the correct element to read it. In this case, one could shift focus to the h1 "thank you etc" followed by instructions to check eMail, etc. That should be enough.

From a tester:

> So, what seems to happen is that when you press continue, the view is refreshed via javascript in the browser. This means that the screen reader will not react unless pushed. In normal web interactions (well, what is normal these days is up for debate), a request is made to the server, and the server responds with a bunch of HTML, and the browser erased the current document and refreshed it with the stuff just sent from the server. Often times, a lot of the stuff is the same as what was already on screen, so when you look at the result only part of the page has changed. In reality, the entire thing has been refreshed. In many apps / websites today, instead of making the round trip to the server, the browser itself, via the javascript running as part of the page, responds locally and manipulates only the part of the page that needs to change. This saves bandwidth and time, but the screen reader has no idea that this took place.
> 
> Easiest way to fix that is to shift focus to something on the page. I would just:
> 
> mark the h1 as focusable by adding tabindex="-1" to it;
> shift focus to it once the conformation message has been posted to the view;

### Actual Behavior

Nothing is spoken. No indication is given to the user that the screen has changed.

### Related Issues

https://github.com/mitodl/mitxonline/issues/153 (potentially related)

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/21342568/139499554-8ad44bcc-5d13-480c-8676-dd73e1d1d9ca.png)

**Comment by briangrossman** [comment]
@asadiqbal08 
I'm reopening this issue. It was just tested for accessibility and there was a request for some improvement. I'm copying the feedback in here to ensure the details aren't lost:

> this is not quite fixed. the thank you page comes up, but focus goes to the body element, rather than the h1.
> 
> Rich shares: The solution that seemed to work most consistently on both Firefox and Chrome with NVDA is:

```
<div autofocus tabindex="0">
<h1>Thank you</h1>
<p>Thank you for creating an account.
If you don't get your confirmation eMail ...
</p></div>

```

> The autofocus attribute should focus the div which is focusable because of the tabindex. Since the entire div is focused, all its contents are read. This should avoid timing issues due to an explicit focus shift via javascript not happening on page load for some reason. However, we'd need to test again after implementation in case there is something that interferes with the autofocus. Another option would be, instead of autofocus, to use a setTimeout() to set focus to the div after 1 millisecond. Again testing is necessary, but one of those two options really should work.

**Comment by asadiqbal08** [comment]
@briangrossman I looked around the suggestion and came to know, `authFocus` not worked on `<div>` element. The code is written in React that need a bit different solution. 

What I am trying to understand they need the heading `<h1>` to be focusable like shown in the image when user press the tab button. Can you please confirm that ? 


<img width="1680" alt="Screenshot 2021-12-09 at 3 46 01 PM" src="https://user-images.githubusercontent.com/7334669/145385753-eef55867-025a-4df3-95c6-e5a7a15b57e7.png">

**Comment by briangrossman** [comment]
@asadiqbal08 
Here's a high level overview of what we're trying to accomplish, just to make sure we're both clear.

- This fix is for users who are using a [screenreader](https://en.wikipedia.org/wiki/Screen_reader) to use  the site.
- After the user clicks `Continue` to start creating their account, the `Thank You!` message (above) appears, but there is no page refresh.
- We need to ensure that focus switches to the `Thank You!` message automatically, otherwise users using the screenreader won't know that the content on the page has updated. 
- The focus should be switched immediately to the `Thank You!` message, it shouldn't require clicking tab.

In looking at your feedback and doing some research, I'm seeing somewhat unclear information about whether the `<div>` element supports `autofocus`. [w3schools](https://www.w3schools.com/tags/att_autofocus.asp) implies it's specifically for form elements. But these sites: [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus) and the [HTML Living Standard](https://html.spec.whatwg.org/multipage/interaction.html#dom-fe-autofocus) seem to imply that it's a global attribute that can be applied to any element. 

If you discover that `autofocus` will indeed work with the `<div>`, you can just proceed with your PR: https://github.com/mitodl/mitxonline/pull/328. If you don't think it will work, you could consider setting the `tabindex` to `-1` and setting the focus via Javascript (if possible). Here's a [simple example](https://dev.to/robdodson/managing-focus-64l) of that approach.

**Comment by asadiqbal08** [comment]
@briangrossman Thanks for the prompt reply and I dug into this problem again and let me share few findings for your reference. 

> If you discover that autofocus will indeed work with the <div>, you can just proceed with your PR: #328. If you don't think it will work, you could consider setting the tabindex to -1 and setting the focus via Javascript (if possible). Here's a simple example of that approach.

1- Firstly @briangrossman , the code is written in React.js instead of pure Javascript so the way that [document solution](https://dev.to/robdodson/managing-focus-64l) you referred is bit different than the way we need to do in React side. 

2- I tried to implement an approach through we can focus the `<h1>Thank You! </h1>` via using the `ref` property but it is **not** actually highlighting the header **but I believe, the heading dom control has gotten the focus at that point**

So I am expecting something like that:

<img width="740" alt="Screenshot 2021-12-10 at 6 51 31 PM" src="https://user-images.githubusercontent.com/7334669/145584302-96ae82f2-d2c7-4ba5-b7c9-5d78a94390be.png">

**but that actually show the blue highlight when I press any key from the board.**

Here is the code sample for testing.

```
export class RegisterConfirmSentPage extends React.Component<Props> {

  constructor(props) {
    super(props);
    this.thanksRef = React.createRef();
  }

  componentDidMount() {
    this.thanksRef.current.style.background = "red";
  }

  render() {
    ...
    return (
      <DocumentTitle
        title={`${SETTINGS.site_name} | ${REGISTER_CONFIRM_PAGE_TITLE}`}
      >
        <div className="std-page-body container auth-page">
          <div className="auth-card card-shadow auth-form">
            <div className="auth-header">
              <h1 tabIndex="-1" ref={this.thanksRef} autoFocus>Thank you! asad</h1>
            </div>
       .....
       .....
```

3- As a testcase, I tried to change the background colour to `red` then the change has reflected when the user lands on the `Thank You` page after clicking the `Create Account` button. 

<img width="701" alt="Screenshot 2021-12-10 at 6 53 47 PM" src="https://user-images.githubusercontent.com/7334669/145584620-adc2f54f-28f3-4f59-8eb3-e9aa8a04e0e6.png">

By doing the following change in code. 

```
componentDidMount() {
    this.thanksRef.current.style.background = "red";
  }
```
Can you tell me the above suggested code in **point#2** ok for you to accept or we need to play with styling for this ?

**Comment by briangrossman** [comment]
@asadiqbal08 

This looks promising. Thanks for the information about how you had to implement this given our environment. I'm hopeful that what you've done will shift the focus to `Thank You!` automatically. We should test it with a screen reader.

Suggestions:
- It would be ideal if you were able to run a screenreader on your computer to test this. This way we won't need to go back and forth to resolve it. (I've included details in the video below.) Both Mac and Windows has built in screenreaders:
   - Mac: [VoiceOver](https://support.apple.com/guide/voiceover/turn-voiceover-on-or-off-vo2682/mac)
   - Windows: [Narrator](https://support.microsoft.com/en-us/windows/complete-guide-to-narrator-e4397a0d-ef4f-b386-d8ae-c172f109bdb1)
- It would also be good if you could post this to a CI build so that I could test it myself with a screenreader. 

Here is a video ([link](https://www.dropbox.com/s/37f3ph0bnjeifzc/MITxAccessibility.mov?dl=0))I made that takes you through how to test it with a screenreader. I think it should help with testing so we can better resolve this issue.

**Comment by asadiqbal08** [comment]
@briangrossman Is it possible for you to test the branch [changes](https://github.com/mitodl/mitxonline/pull/328) locally ? I mean, do you have setup ?

**Comment by briangrossman** [comment]
@asadiqbal08 I don't have a local build that I can run. You could possibly post a video... or if you feel confident that it's working, we can get it retested by our accessibility testers.

**Comment by asadiqbal08** [comment]
@briangrossman please take a look over this [video](https://watch.screencastify.com/v/jtcAhrIX6LWbx4mrZBq7)

**Comment by briangrossman** [comment]
@asadiqbal08 That looks like it's working to me. It looks like it started reading `Thank You!` automatically. 

Great!

Also, I like the way the screenreader pronounces your name. :)

**Comment by asadiqbal08** [comment]
hahaha. @briangrossman should I merge it ?

**Comment by briangrossman** [comment]
@asadiqbal08 
Looks like Umar just approved it. Great. 
Once it's in production, I'll have the accessibility testers take a look.

Thanks for the effort you put in testing with the screen reader.
