### ISSUE TITLE
Allow users to unsubscribe from course emails from the dashboard

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#288]
As an MITx Online learner who doesn't want to receive course emails, I should be able to opt out. To address this, we should add an option to unsubscribe/subscribe from/to course emails.

#### Designs and Mockups

![137545549-6ae58d86-039a-4eed-abca-bc9f45bba683](https://user-images.githubusercontent.com/21342568/140984777-249cbc22-ccb1-44b8-8ff8-d65e82a45ea1.png)

#### Acceptance Criteria:

- [x] If the user is subscribed to course emails, `Unsubscribe from emails` option added to the course kebab menu on the dashboard. 
- [x] If the user is not subscribed to course emails, `Subscribe to emails` option added to the course kebab menu on the dashboard. 
- [x] Clicking `Unsubscribe from emails` unsubscribes the user from course emails and toggles the menu item to `Subscribe to emails`
- [x] Clicking `Subscribe to emails` subscribes the user to course emails and toggles the menu item to `Unsubscribe from emails`
- [x] Determine the appropriate API endpoint, add it to our edx-api-client library, and hook it up to the interface
- [ ] Update the course email template to link to the API to allow users to unsubscribe ([link](https://courses.mitxonline.mit.edu/admin/bulk_email/courseemailtemplate/))

**Comment by pdpinch** [comment]
Is the pop-up necessary?

**Comment by briangrossman** [comment]
@pdpinch - per our discussion, I updated the description above.
