### ISSUE TITLE
Update Zendesk theme footer to match the MITx Online site

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#292]
As an MITx Online user I'd like a consistent footer throughout the entire site. 

#### Designs and Mockups

![image](https://user-images.githubusercontent.com/21342568/141605665-4f06ceb7-0966-4977-bc79-8ee626c6d7a9.png)

#### Acceptance Criteria:

- [ ] Issue details here: https://github.com/mitodl/mitxonline-zendesk-theme/issues/1

**Comment by arslanashraf7** [comment]
Closed via https://github.com/mitodl/mitxonline-zendesk-theme/pull/4
