### ISSUE TITLE
don't allow users to register via open edX

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#294]
### Steps to Reproduce

1. Log out of open edX and mitxonline
2. Log into mitxonline
3. Follow a link from the dashboard to open edX, for example https://courses.mitxonline.mit.edu/learn/course/course-v1:MITxT+14.100x+3T2021/home

### Expected Behavior

- User should be logged in to open edX
- User should see the course outline for a course they are enrolled in (because it was on their dashboard) 

### Actual Behavior

- User is not logged in
- User sees links to sign in (good)
- User sees link to register (not good) 

### Related Issues

- Can we ensure that the user is logged into open edX when they log into mitxonline? I believe that's what we do in xPRO
- Is there a way to globally remove the register option from these screens and messages?
- in mitxonline-theme, we should override the template for the [registration page](https://courses.mitxonline.mit.edu/register) to encourage users to sign in via the mitxonline app, and obscure the registration form -- as we do in xPRO. 

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/430126/141999267-1e200cf4-35a9-443d-ad60-df4371586e89.png)

![image](https://user-images.githubusercontent.com/430126/141999455-de61ed3f-952f-486e-b522-282a01e06a1c.png)

**Comment by rhysyngsun** [comment]
https://github.com/mitodl/mitxpro-openedx-extensions was implemented to solve this, so i think this comes down to that being installed & configured.

**Comment by pdpinch** [comment]
I see there are a bunch of settings for mitxpro-openedx-extensions, but we only seem to have one of them set -- for xPro or for mitxonline. 

Which setting do you think it relevant to this issue?

**Comment by pdpinch** [comment]
@rhysyngsun It looks like mitxpro-openedx-extensions is installed with mitxonline: https://github.com/mitodl/ol-infrastructure/blob/ef1917b472bc8f7a0cd955d5621033d4d8e7ac7c/src/bilder/images/edxapp/group_data/all.py#L31

Looking at the settings from https://github.com/mitodl/mitxpro-openedx-extensions/blob/master/mitxpro_core/settings/production.py only one of these seems to be set in ol-infrastruture:

- no setting for [MITXPRO_CORE_REDIRECT_ENABLED](https://github.com/mitodl/ol-infrastructure/search?q=MITXPRO_CORE_REDIRECT_ENABLED)
- not setting for [MITXPRO_CORE_REDIRECT_LOGIN_URL](https://github.com/mitodl/ol-infrastructure/search?q=MITXPRO_CORE_REDIRECT_LOGIN_URL)
- this one is set: [MITXPRO_CORE_REDIRECT_ALLOW_RE_LIST](https://github.com/mitodl/ol-infrastructure/blob/12627b7c3f301da469d6aa750efd12c01d33be51/src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml.tmpl#L345)
- not setting for [MITXPRO_CORE_REDIRECT_DENY_RE_LIST](https://github.com/mitodl/ol-infrastructure/search?q=MITXPRO_CORE_REDIRECT_DENY_RE_LIST)

Don't we need settings to MITXPRO_CORE_REDIRECT_ENABLED and MITXPRO_CORE_REDIRECT_LOGIN_URL ?

**Comment by rhysyngsun** [comment]
@pdpinch yes those two are the minimum ones are required to turn on that behavior. `MITXPRO_CORE_REDIRECT_ALLOW_RE_LIST` is optional.
