### ISSUE TITLE
Strengthen validation requirements for course pages

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#304]
As a user of the MITx Online site, I want to learn all the details about a course before I enroll. Additionally, I want the course pages to be well-designed and attractive.

#### Acceptance Criteria:

Update requirements for the course pages:

- [ ] Make `Description` a required field
- [ ] Make `Length` a required field
- [ ] Make `Price` a required field
- [ ] Make `Feature Image` a required field
- [ ] Display a warning when the user enters a faculty `Description` larger than 1000 characters:
   - `You have reached the recommended character limit of 1000 characters. Longer entries may not display nicely on the page.`

**Comment by umarmughal824** [comment]
@briangrossman regarding that warning. Let me tell you that we don't put any such warning but we could show it in the help_text that adds a hint for the user to follow that. It looks like

<img width="1244" alt="Screenshot 2021-11-29 at 16 45 45" src="https://user-images.githubusercontent.com/4043989/143862476-216c3c99-fefb-4fe5-905e-182d07b00fc1.png">

**Comment by briangrossman** [comment]
> @briangrossman We don't put any such warning but we could show it in the help_text that adds a hint for the user to follow that. It looks like
> 
> <img alt="Screenshot 2021-11-29 at 16 45 45" width="1244" src="https://user-images.githubusercontent.com/4043989/143862476-216c3c99-fefb-4fe5-905e-182d07b00fc1.png">

This works for me. Thanks!
