### ISSUE TITLE
MicroMasters Auth: update documentation to describe how to configure the system

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#31]
Update documentation to describe how to configure mitX Online + MicroMasters to work together.

_Note:_
I suspect locally we might hit some issues here with devstack - specifically for the case that the user already has an account created in devstack for MicroMasters (or xPro for that matter), and they try to add an mitX Online authentication they will probably see an error back from OpenedX and their account creation will fail. This might require some hackery to get around but we should be clear in distinguishing that this is a local dev issue because in deployed environments MicroMasters and mitX Online won’t be running against the same (Open)edX deployment.

**Comment by pdpinch** [comment]
Note that we were tripped up by the lack of clarity about email validation. It needs to be turned off, possibly in both the django admin and in the edX feature settings. See https://mitodl.slack.com/archives/C02649X2P1V/p1629405256202900

**Comment by rhysyngsun** [comment]
We should note this in the xpro docs too.
