### ISSUE TITLE
Add annotations for REGISTRATION_RATELIMIT and RATELIMIT_RATE

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#324]
When we launched mitxonline, we discovered edX has built-in rate limits on user registrations and oauth logins. We increased the  limits by setting the keys REGISTRATION_RATELIMIT and RATELIMIT_RATE. 

https://github.com/mitodl/ol-infrastructure/commit/fc88b8a8dff275b52048abb89819030870603986
https://github.com/mitodl/ol-infrastructure/commit/217ba2428883382ead7abd9b9908392f027aa20d

These keys don't appear to be documented in https://edx.readthedocs.io/projects/edx-platform-technical/en/latest/index.html as they should be. 

We should add appropriate annotations for the keys.

**Comment by MAbdurrehman12** [comment]
Closed by https://github.com/edx/edx-platform/pull/29545
