### ISSUE TITLE
open edX: redirect from: /courses/ to: https://mitxonline.mit.edu/

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#332]
### Steps to Reproduce

- Go to /courses/ on Open edX
- Note that the page displays a list of all the courses 

### Expected Behavior

- This should redirect users to the MITx Online home page: https://mitxonline.mit.edu/

### Actual Behavior

- Learners can see all the courses in Open edX and are able to enroll from this page
   -  This is undesirable behavior

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/21342568/145642974-7aa44747-7456-4ca3-a9f5-92170d6707e0.png)

**Comment by briangrossman** [comment]
@blarghmatey has turned on a setting that will block this page from non-staff users.

Ideally it will still be redirected to the /catalog/ page. This will be handled in Fastly. We'll address after the new year. 

On hold for now.

**Comment by briangrossman** [comment]
> @blarghmatey has turned on a setting that will block this page from non-staff users.

Setting:
- https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml#L206
- https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml#L209

**Comment by pdpinch** [comment]
Be sure to test account creation and login.

**Comment by asadali145** [comment]
FYI @pdpinch 

We can add redirects in edX using the Django Admin site.
To add a redirect a URL:

- Visit `admin/redirects/redirect/`
- Add old and new URLs.
- Visit the old URL and it should redirect to the new URL.

Tested the following things and are working fine:

- User Creation & Login.
- Tried to access the URL directly.
- Access from the User profile dropdown.

**Comment by pdpinch** [comment]
We made this change in production last week ~9/27 and it's working well.
