### ISSUE TITLE
Research: Investigate how to upgrade learners when they pay for a course

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#340]
- [ ] How does edx/openedx prompt learners to upgrade to verified
  - Is this done with an MFE, xblock, edx-platform, or other?
  - How is the user navigated to checkout / where is this url specified/generated?
- [ ] How do we change the learner's course mode / track after they have enrolled?

**Comment by arslanashraf7** [comment]
@pdpinch, @rhysyngsun FYI, Let me know if anything is unclear or need more explanation

The overall scope of what we are looking at here revolves around `edx-platfrom, frontend-app-learning,edX's ecommerce service, frontend-app-payment`. So, I would try to add references from all/any of these while answering the above questions.

_For TLDR_, In the scenario mentioned, We have course modes for a course that a learner can avail while taking the course. Some of the common of these are `verified`, `audit`. These modes define the details such as SKUs, Upgrade deadlines, and associated courses. Whenever a course is being enrolled, the mode decides either to take the user to eCommerce for payment or let the user enroll and get the payment later.


_Answering the questions:_

**_1 ) How does edx/openedx prompt learners to upgrade to verified?_**

It does the decisions based on the mode enrollment and the availability of the `verified` course mode. e.g If a user has enrolled in a course in `audit` mode, an enrollment entry would be created with `audit` mode. So, when a user loads the dashboard or opens a course he sees the `Upgrade` button. These prompts depend upon a `verified` course mode.

**_1.1 ) Is this done with an MFE, xblock, edx-platform, or other?_**
There are two places for a user gets the prompts. (Learning MFE, Legacy Courseware)

**In the MFE:** 
It hits [course_outline api](https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/course_home_api/outline/views.py#L72) and in response it gets `enrollment_mode` and `verified_mode` values along with the outline.  This can be seen in the course outline API class. Learning MFE then decides to show the prompt to the user or not. [Ref](https://github.com/openedx/frontend-app-learning/blob/master/src/generic/upgrade-notification/UpgradeNotification.jsx#L239)

**In the legacy view**:
In the legacy view, the upgrade button would show based on a [few conditions](https://github.com/openedx/edx-platform/blob/master/lms/templates/dashboard/_dashboard_course_listing.html#L46) regarding eCommerce, verified SKU availability.


_**1.2 ) How is the user navigated to checkout / where is this URL specified/generated?**_

For the frontend, the checkout URL is part of the `verified_mode` object returned in the course_outline API response. A sample response:
```
{
	"dates_banner_info": {...},
	"can_show_upgrade_sock": false,
	"verified_mode": {
		"access_expiration_date": null,
		"currency": "USD",
		"currency_symbol": "$",
		"price": 149,
		"sku": "8CF08E5",
		"upgrade_url": "http://localhost:18130/basket/add/?sku=8CF08E5"
	},
	"access_expiration": null,
	"cert_data": {...},
	"course_blocks": {
		"blocks": {...},
        }
	"enroll_alert": {...},
	"enrollment_mode": "audit",
}...
```

In the above response, the checkout URL in verified_mode is being generated at runtime based on the eCommerce service integrated. [see the implementation here](https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/commerce/utils.py#L103-L132). However, the eCommerce as of now redirects the user to the [frontend-app-paymemt](https://github.com/openedx/frontend-app-payment) for the payment processing.

**_2 ) How do we change the learner's course mode / track after they have enrolled?_**

I was trying to set up the paypal payment method to test this part happening after the payment completion but i couldn't. However. I found an [Enrollment Support API](https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/support/views/enrollments.py#L185-L239) that can be used to change the enrollment mode for a learner if that's what we need. This API can only be used by users with `staff` access.

I'm unaware of the exact usecase, probably we are thinking of offering `audit` courses and then upon payment we take the users back to our marketing site and on successful payment, we update their enrollment mode to `verified` without using edX's e-commerce?

**Comment by pdpinch** [comment]
Thanks Arslan. This is really helpful. 

> I'm unaware of the exact usecase, probably we are thinking of offering audit courses and then upon payment we take the users back to our marketing site and on successful payment, we update their enrollment mode to verified without using edX's e-commerce?

Yes, this is exactly our plan. Based on your findings so far, it seems like we need (at least):

1. A way to override the `upgrade_url` returned by open edX's course outline API
2. A reliable endpoint for changing the enrollment mode from `audit` to `verified` (or other suitable enrollment modes)

Have you found the enpoint that edX's ecommerce app uses to change the enrollment mode? The Support API seems like a bit of a backdoor, designed for the customer support team.

**Comment by arslanashraf7** [comment]
@pdpinch I think I can answer the possible solutions for our needs as you mentioned above:

> A way to override the upgrade_url returned by open edX's course outline API

As I mentioned earlier the checkout/upgrade URL is being [generated dynamically](https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/commerce/utils.py#L103-L132). But i was able to generate a checkout URL that might be something we are looking at. I'm going to mention the configurations that i changed in order to generate it for xPRO e.g. are as below:

1. `ECOMMERCE_PUBLIC_URL_ROOT = 'https://xpro-rc.odl.mit.edu/'`
2. Added an eCommerce configuration in [django admin](http://localhost:18000/admin/commerce/commerceconfiguration) with `basket_checkout_page=/checkout/`

With the above configuration, i was able to generate a. URL that looks like `https://xpro-rc.odl.mit.edu/checkout/?sku=8CF08E5` and opens our checkout page. What is not configurable is the `sku` query param but i think we can make our marketing site checkout logic to cater for this param upon checkout.


>A reliable endpoint for changing the enrollment mode from audit to verified (or other suitable enrollment modes)

While looking at how the current eCommerce implementation is changing the mode I was able to identify the API. that the commerce service calls.
The eCommerce users [post enrollment](https://github.com/openedx/ecommerce/blob/f37e406888efdf7199d2b8792cd01011e2145732/ecommerce/extensions/fulfillment/modules.py#L337) API to update the. mode for a learner. The implementation of this enrollment API from edx-platform can be seen [here](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/enrollments/views.py#L446). This API is based on `EDX_API_KEY` which I think we are already doing in our [edx-api-client](https://github.com/mitodl/edx-api-client).

Let me know if this helps.

**Comment by rhysyngsun** [comment]
> @pdpinch I think I can answer the possible solutions for our needs as you mentioned above:
> 
> > A way to override the upgrade_url returned by open edX's course outline API
> 
> As I mentioned earlier the checkout/upgrade URL is being [generated dynamically](https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/commerce/utils.py#L103-L132). But i was able to generate a checkout URL that might be something we are looking at. I'm going to mention the configurations that i changed in order to generate it for xPRO e.g. are as below:
> 
>     1. `ECOMMERCE_PUBLIC_URL_ROOT = 'https://xpro-rc.odl.mit.edu/'`
> 
>     2. Added an eCommerce configuration in [django admin](http://localhost:18000/admin/commerce/commerceconfiguration) with `basket_checkout_page=/checkout/`
> 
> 
> With the above configuration, i was able to generate a. URL that looks like `https://xpro-rc.odl.mit.edu/checkout/?sku=8CF08E5` and opens our checkout page. What is not configurable is the `sku` query param but i think we can make our marketing site checkout logic to cater for this param upon checkout.

I think we should actually deal with this on the OpenedX side, because otherwise we're forced to map the SKUs on MITx Online via either a data mapping or an API call. Instead I think adding a new view (e.g. `/checkout-external?sku=abc`) via a plugin, which maps the sku to the course run id and then redirects over the the mitx online checkout page with the existing url structure. Then update the `basket_checkout_page` to point to this.

> 
> > A reliable endpoint for changing the enrollment mode from audit to verified (or other suitable enrollment modes)
> 
> While looking at how the current eCommerce implementation is changing the mode I was able to identify the API. that the commerce service calls. The eCommerce users [post enrollment](https://github.com/openedx/ecommerce/blob/f37e406888efdf7199d2b8792cd01011e2145732/ecommerce/extensions/fulfillment/modules.py#L337) API to update the. mode for a learner. The implementation of this enrollment API from edx-platform can be seen [here](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/enrollments/views.py#L446). This API is based on `EDX_API_KEY` which I think we are already doing in our [edx-api-client](https://github.com/mitodl/edx-api-client).
> 
> Let me know if this helps.

I think this is fine and in fact this is good design on OpenedX's part.

**Comment by pdpinch** [comment]
@arslanashraf7 @rhysyngsun one concern I have about the [post enrollment](https://github.com/openedx/ecommerce/blob/f37e406888efdf7199d2b8792cd01011e2145732/ecommerce/extensions/fulfillment/modules.py#L337) API is that it's part of the ecommerce app which, as far as I know, we aren't installing/using.

Or to be more explicit:
- Does  [post enrollment](https://github.com/openedx/ecommerce/blob/f37e406888efdf7199d2b8792cd01011e2145732/ecommerce/extensions/fulfillment/modules.py#L337) API require the ecommerce app?
- Is that API already available on mitxonline?

**Comment by arslanashraf7** [comment]
@pdpinch 

> @arslanashraf7 @rhysyngsun one concern I have about the [post enrollment](https://github.com/openedx/ecommerce/blob/f37e406888efdf7199d2b8792cd01011e2145732/ecommerce/extensions/fulfillment/modules.py#L337) API is that it's part of the ecommerce app which, as far as I know, we aren't installing/using.
> 
> Or to be more explicit:
> 
> * Does  [post enrollment](https://github.com/openedx/ecommerce/blob/f37e406888efdf7199d2b8792cd01011e2145732/ecommerce/extensions/fulfillment/modules.py#L337) API require the ecommerce app?
> * Is that API already available on mitxonline?

1) The post enrollment API doesn't need ecommerce. The [post emnrollment](https://github.com/openedx/ecommerce/blob/f37e406888efdf7199d2b8792cd01011e2145732/ecommerce/extensions/fulfillment/modules.py#L337) API reference above refers to how it's being called/used from eCommerce. The actual enrollment API lies in the [enrollment app](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/enrollments/views.py#L446) in Openedx Core.
2) I think we already have the enrollment API configured in our [edx-api-client](https://github.com/mitodl/edx-api-client/blob/master/edx_api/enrollments/__init__.py#L21). And we are using it in our [mitxonline](https://github.com/mitodl/mitxonline/blob/main/openedx/api.py#L492-L520) implementation too.
