### ISSUE TITLE
open edx: dates tab doesn't show all course dates by default

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#342]
### Steps to Reproduce

- View a course in Open edX LMS
- Click on the dates tab

### Expected Behavior

- The page will display all important dates in the course including start/end dates and deadlines by default without having to set a flag for each course (see notes below)

### Actual Behavior

- By default, the dates page will only list the start and end dates
- We are currently overriding this functionality by setting a waffle flag as follows:
   - Go to waffle flag course overrides in the LMS admin: `/admin/waffle_utils/waffleflagcourseoverridemodel/`
   - Click `Add Waffle Flag Course Override`
   - Add a new flag
      - Waffle flag: `course_experience.relative_dates`
      - Course id: [the course id]
      - Note: [optional]
      - Override Choice: `force on`
      - Enabled: [checked]
   - Once set, all dates will appear on the dates tab

### Related Issues

https://github.com/mitodl/mitxpro/issues/2330

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/21342568/146622588-79ce5066-b2fa-496d-9056-1b5929c65fd4.png)

**Comment by umarmughal824** [comment]
@briangrossman could you please add more details about it? I have tried out different things but could not find that which dates are you referring to here except start or end dates.

**Comment by briangrossman** [comment]
@umarmughal824 

Sure. Here's some additional info. 

In the screenshot above (in the overall description), you can see that the only dates that are shown on the dates tab are the start and end dates. 
![image](https://user-images.githubusercontent.com/21342568/148005738-13b87419-98d4-434a-8b05-19095992b8b4.png)

Here's a screenshot for a date tab for a course that has the `course_experience.relative_dates` flag (mentioned above) set. Note that it includes the start date, end date, and all the due dates in the course.

![image](https://user-images.githubusercontent.com/21342568/148006179-3c3d2e89-3649-4021-a2f9-722bf775bfb9.png)

Due dates can be set for subsections by clicking on the settings gear for a subsection in the course outline
![image](https://user-images.githubusercontent.com/21342568/148006515-4d160397-16a1-4afc-975d-d7436214eabf.png)


The key point is that these due dates are not appearing on the dates tab by default. We need to set the `course_experience.relative_dates` for each course to get them to appear. Ideally, this would work by default without having to set a flag for each individual course.

Hope this helps!

**Comment by umarmughal824** [comment]
@briangrossman we can define a globa waffle flag for all the courses where it will automatically shows all the dates against each course.

For global waffle, we could go to `admin/waffle/flag/`

<img width="1440" alt="Screenshot 2022-01-04 at 18 48 19" src="https://user-images.githubusercontent.com/4043989/148068607-be801d84-793b-4323-88fa-0ed0bf74ef43.png">

**Comment by briangrossman** [comment]
@umarmughal824 Sorry it took me so long to test this. It works great!

I'm closing this. Thanks!
