### ISSUE TITLE
open edx: users can't update their names for proctored exams by themselves

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#343]
### Steps to Reproduce

- Create an account using a name that doesn't match your id
- Complete the onboarding process for a course that has a Proctortrack exam
   - You may need to be added at a Beta Tester to the course, depending on the setup
- View the `Special Exams` tab in the `Instructor` tab
    - In the `Review Dashboard` section, note your name
    - In the `Student Special Exam Attempts` section, click `Reset` to remove your exam attempt
- In the MITx Online profile page `https://mitxonline.mit.edu/profile/`, update your `First Name`, `Last Name`, and `Full Name`
- Complete the onboarding process for the course again
- Return to the `Special Exams` tab in the `Instructor` tab
    - In the `Review Dashboard` section, note your name has not been updated

### Expected Behavior

- When a learner modified their name, Proctortrack gets the updated name
- This will allow learners to update their names to match their IDs

### Actual Behavior

- Proctor track doesn't get the updated name, it keeps the original name
- Note that a record is created in the `Edx Name Affirmation` => `Verified Names` section `/admin/edx_name_affirmation/verifiedname/` that reflects the original name
   - This value can be updated to modify the name that is submitted to Proctortrack
- We would like to circumvent the verified names functionality to enable learners to update their names if necessary without support

### Screenshot or Screencast

Verified Names
![image](https://user-images.githubusercontent.com/21342568/146624911-dc6e06a7-424d-40db-a321-0a0dbc52072c.png)

Special Exams Section
![image](https://user-images.githubusercontent.com/21342568/146624948-085b6258-addb-48d7-837d-bee178d2ccb1.png)

**Comment by briangrossman** [comment]
Here is the repo for [edx-name-affirmation](https://github.com/edx/edx-name-affirmation)

**Comment by briangrossman** [comment]
There was discussion about this issue in [the Open edX slack channel](https://openedx.slack.com/archives/CD506K945/p1640187669001300). We were able to work around this by deleting verified name records from the edX admin to reset learners. This ensured that learner's name changes were sent to Proctortrack for approval. 

The Open edX team is looking into the possibility of making verified names optional, allowing us to turn it off if desired. 

On hold

**Comment by pdpinch** [comment]
Do you think we could delete the verified name record when a user changes their name in mitxonline?

**Comment by briangrossman** [comment]
Oh... interesting... like some sort of trigger that would clear it out automatically. It's an interesting idea.

For now, I'm leaning toward waiting to see if Open edX actually makes it optional, as that would be cleaner... and we didn't run into too much trouble with it this last set of exams.
