### ISSUE TITLE
Past courses are no longer available on dashboard 

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#346]
### Steps to Reproduce

- Enroll in a course
- View the course in your MITx Online dashboard - note that there is an active link to the course in Open edX
- Update the end date for the course to be in the past
- View the course in your MITx Online dashboard - note that there is no longer and active link to the course in Open edX

### Expected Behavior

- If the learner is enrolled in the course, they should be able to continue to view the content, even after the course has ended.

### Actual Behavior

- Once the course has ended, learners are no longer able to access the course from their MITx Online dashboard
- Note that this is working properly in the [edX dashboard](https://courses.mitxonline.mit.edu/dashboard)

### Screenshot or Screencast

Active Link
![image](https://user-images.githubusercontent.com/21342568/147139854-2d8c58a7-6325-4552-91f4-5254c9a77194.png)

Disabled Link
![image](https://user-images.githubusercontent.com/21342568/147139887-52cf02c1-1052-4580-8f2f-ae66385d5d8d.png)

**Comment by arslanashraf7** [comment]
Closed via #349
