### ISSUE TITLE
open edx: breadcrumb trail links occasionally fails 

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#347]
### Steps to Reproduce

- View a course as a non-staff user (e.g. [link](https://courses.mitxonline.mit.edu/learn/course/course-v1:MITxT+21A.819.1x+3T2021/home))
- View a page in the course (e.g. [link](https://courses.mitxonline.mit.edu/learn/course/course-v1:MITxT+21A.819.1x+3T2021/block-v1:MITxT+21A.819.1x+3T2021+type@sequential+block@08bf5f489b884c49b63b52fa571cc405/block-v1:MITxT+21A.819.1x+3T2021+type@vertical+block@8b4f929c3c9343718106fb76a2f1f441)). It should load
- Click on the item in the breadcrumb right next to the `Content` link
![Screen Shot 2021-12-22 at 12 52 39 PM](https://user-images.githubusercontent.com/21342568/147142526-7a54bf62-6f44-463a-b03e-2c1f95af96bf.png)

### Expected Behavior

- It should load the appropriate page (which may be the page you're on already)

### Actual Behavior

- It displays `There was an error loading this course` 
![image](https://user-images.githubusercontent.com/21342568/147142719-4536d927-e7f6-4c34-a31e-6f55c5e29ee8.png)
- A few things to note:
   - The page will load correctly if you reload
   - The page will load correctly if you open it in a new tab
   - The last link (on the right) in the breadcrumb will load correctly
   - See the video posted below for a run-through

### Related Issues

- This is very much tied to: https://github.com/mitodl/mitxonline/issues/345
   - The changes for the Learning MFE were launched into production earlier today
- This may be generating [this error](https://sentry.io/organizations/mit-office-of-digital-learning/issues/2878375253/?project=5939801&query=is%3Aunresolved)
- Given that the page loads properly when accessed directly initially, devops is assuming this is not server-side

### Screenshot or Screencast

[Video](https://www.dropbox.com/s/igtziodtni38mc1/MITxOnline_Breadcrumb_Fail.mov?dl=0) capturing the issue

**Comment by pdpinch** [comment]
This may be fixed when we upgrade to the latest MFE which includes:

https://github.com/openedx/frontend-app-learning/commit/907892e7bb1263d6b9b56d8acc7fe57abd34cbdd

and the latest edx-platform, which includes: 

https://github.com/edx/edx-platform/commit/712380713b8fc3f46bcef1360fdbcf8c3b468208

**Comment by pdpinch** [comment]
The upgrade seems to have worked!

**Comment by pdpinch** [comment]
Now the update needs to be deployed to production.

**Comment by asadiqbal08** [comment]
@pdpinch it is added in Arbisoft board. Is it correct ?

**Comment by pdpinch** [comment]
@briangrossman do you think we can close this?

I'm going to remove it from the board in the meantime.

**Comment by briangrossman** [comment]
@pdpinch Yes. Thanks. This has been working. Closing.
