### ISSUE TITLE
Make readable_id searchable in CMS

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#351]
### Steps to Reproduce

- In the CMS, search for a readable_id in the search field (e.g. `course-v1:MITxT+14.310x`)

### Expected Behavior

- `course-v1:MITxT+14.310x | Data Analysis for Social Scientists` will be returned in the search results

### Actual Behavior

- No results are returned. 
- The search is not searching the readable_id field

### Related Issues

https://github.com/mitodl/mitxonline/issues/322

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/21342568/147685510-9b436a65-a5af-4e47-8e17-f05e11b69f48.png)

**Comment by arslanashraf7** [comment]
@briangrossman Can we close this? Just checking in to make sure that we've verified this in production as well since it has a prerequisite, which is to run `./manage.py wagtail_update_index`. However, there a many details on https://github.com/mitodl/mitxonline/pull/352.

**Comment by briangrossman** [comment]
@arslanashraf7 
Thank you for the reminder to run this! I just ran it. The search it working.
