### ISSUE TITLE
Email Subscription Updates

### ISSUE THREAD

**Issue by umarmughal824** [mitodl/mitxonline#366]
- [ ] Instead of "unsubscribe" change the menu item to "email settings" 
- [ ] When email settings is selected, show a pop-up with:
   - [ ] a title of "Email settings for <course number>" (or course name if course number isn't an option right now)
   - [ ] a checkbox labelled "Receive course emails" 
   - [ ] a save button
 
Aside from the UI change, I think everything else you've already done should be fine. 

Here's a screenshot of the pop-up on edX:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/430126/148602366-f6e5a128-4446-4aa8-b874-4aff7950448b.png">

_Originally posted by @pdpinch in https://github.com/mitodl/mitxonline/issues/329#issuecomment-1007713228_

**Comment by pdpinch** [comment]
Thanks for opening this @umarmughal824. I accidentally opened another one #369, but it has more details.
