### ISSUE TITLE
Change "unsubscribe" UI to "email settings" 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#369]
In #329 we added the feature to allow users to unsubscribe from course emails, but "unsubscribe" is not very clear to users. Instead, we'd like to use the same UI that edX does in edx-platform:

#### Designs and Mockups

Here's a screenshot of the pop-up on edX:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/430126/148602366-f6e5a128-4446-4aa8-b874-4aff7950448b.png">

#### Acceptance Criteria:

- [ ] Instead of "unsubscribe" change the menu item to "email settings" 
- [ ] When email settings is selected, show a pop-up with:
   - [ ] a title of "Email settings for <course number>" (or course name if course number isn't an option right now)
   - [ ] a checkbox labelled "Receive course emails" 
   - [ ] a save button
- [ ] When the pop is displayed, the state of the checkbox should reflect the state of the user's subscription, i.e. it should be checked if they are currently subscribed and unchecked if they are not. 
 #### Out of Scope

- We need a way for users to unsubscribe from all emails, including marketing emails

**Comment by arslanashraf7** [comment]
I think @umarmughal824 opened a similar one. https://github.com/mitodl/mitxonline/issues/366
