### ISSUE TITLE
Signing into MITx Online doesn't automatically sign you in to edX

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#393]
### Steps to Reproduce

- Ensure you are signed out of MITx Online and MITx Online's edX
- Sign in to MITx Online
- Open your dashboard
- Click on a course in the dashboard

### Expected Behavior

- You will automatically be signed in to edX and can view the course immediately
- Note that this works in xPRO (see related issue below)

### Actual Behavior

- You need to sign in to edX separately (see the video below)

### Related Issues

https://github.com/mitodl/mitxpro/issues/103 - this worked before with xPRO, prior to the MFE. 

### Screenshot or Screencast

https://www.dropbox.com/s/2by741oh50lo67w/Signin_Doesnt_Sign_into_edX.mov?dl=0

**Comment by asadiqbal08** [comment]
After looking around the Learning MFE code and MitxOnline structure. It seems to me, In order to fix this, 

- We need to create an upstream PR in Learning MFE that will accommodate the toggle for `requireAuthenticatedUser` from the environment configuration as per @rhysyngsun suggestions, which states that: 

>> If true, turns on automatic login redirection for unauthenticated users.  Defaults to false, meaning that by default the application will allow anonymous/unauthenticated sessions.

Learning MFE, just act as a frontend wrapper to OpenEdx so I believe, If we have Configured the Open edX to support `OAuth2 authentication` from MITx Online as described [HERE](https://github.com/mitodl/mitxonline/blob/main/docs/source/configuration/open_edx.rst#configure-open-edx-to-support-oauth2-authentication-from-mitx-online) then redirection should follow the `Oauth2 authentication` mechanism of OpenEdx. 

Thoughts ?

**Comment by rhysyngsun** [comment]
@asadiqbal08 looks good to me

**Comment by asadiqbal08** [comment]
Created an [upstream PR](https://github.com/openedx/frontend-app-learning/pull/827) to take further input over it.

**Comment by asadiqbal08** [comment]
@briangrossman the [comment](https://github.com/openedx/frontend-app-learning/pull/827#issuecomment-1042997733) from MFE group. 
@rhysyngsun fyi.

**Comment by briangrossman** [comment]
@asadiqbal08 
I did some testing and found it was working on xPRO RC. Here's a video ([link](https://www.dropbox.com/s/0scb28zxqkvm1xt/AutoLogInOpoenEdx.mov?dl=0)) that shows that this works correctly on xPRO RC for URLs that are formatted a particular way.

- `/courses/course-v1:xPRO+TestCourse2+R1/course/` - behaves correctly and logs learner into Open edX
- `/learn/course/course-v1:xPRO+TestCourse2+R1/home` - doesn't behave correctly, learner needs to log in

Note that this solution doesn't work correctly on xPRO production. Instead of logging the learner in and redirecting them to the Learner MFE, it just sends them to the legacy version of the course. It would be good to understand why it's working on xPRO RC so we can make it work in all environments.

**Comment by briangrossman** [comment]
@pdpinch 
Good call!

> 1. Behavior for course staff and for learners is different. Were you testing learners on both deployments?

I think I was testing on production using my staff account. I was able to reproduce the same behavior (where I was logged in automatically on production). See below.

> 2. Similarly, behavior could be different if you are enrolled or not.

I was enrolled in all case. 

> 3. Are there any relevant waffle flags set differently on each deployment?

RC has a `courseware.courseware_mfe` flag set that production does not. That being said, it may not be relevant due to item 1 above
![image](https://user-images.githubusercontent.com/21342568/158893917-254f6d2e-9e59-4510-8c58-7052d64e1892.png)

-----

I did an experiment on xPRO with the course: Leadership for Technical Professionals Demo

- Current `Courseware url path`: `/learn/course/course-v1:DEMO+EngLeadxDEMO+DEMO/home`
   - Learner is asked to Sign in to continue to the course: 
<img width="275" alt="image" src="https://user-images.githubusercontent.com/21342568/159215494-3791283b-ba3c-4687-bc52-542ec371feb2.png">

- Updated `Courseware url path`: `/courses/course-v1:DEMO+EngLeadxDEMO+DEMO/course/`
   - Learner is signed in to edX and redirected to the Learning MFE appropriately (`https://courses.xpro.mit.edu/learn/course/course-v1:DEMO+EngLeadxDEMO+DEMO/home`) 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/21342568/159215994-a03efa77-7a58-4639-b8d4-9656470484e1.png">

-----

I was able to replicate this behavior on `rc.mitxonline.mit.edu` by changing a url from`/learn/course/course-v1:MITx+14.100x+1T2022/home` to `/courses/course-v1:MITx+14.100x+1T2022/course/`. I assume it will work on MITx Online production as well.

-----

@asadiqbal08 
It appears as though if I change the links to the courses to be of the format: `/courses/[course id]/course/` instead of `/learn/course/[course id]/home`, it will sign the learner into edX and redirect them appropriately. 

Do you know why this is working? I am happy to update the links as needed (on xPRO and MITx Online) to fix this.

**Comment by asadiqbal08** [comment]
@briangrossman Yeah, That was my findings that I shared. The reasons is that the `learn` part is including the Learning MFE to come in b/w `Mitx-AppInstance` and `OpenEdx`. 
In the [PR](https://github.com/openedx/frontend-app-learning/pull/827), I introduced a flag that allow the Learning MFE to follow the auto redirection flow but the change set is not in favour of Learning MFE group (As they are expecting, some unusual behaviour can occur if we use this [change](https://github.com/openedx/frontend-app-learning/pull/827) in current structure of MFE).

**Comment by asadiqbal08** [comment]
One thing more to add, Updating the URL to legacy view would not be ideal as we are migrating to use Learning MFE. I am thinking to keep the behaviour as it is as Learning MFE is following and keep this issue on hold. 
As the MFE team is not in favour at the moment for such [change](https://github.com/openedx/frontend-app-learning/pull/827)
@pdpinch thoughts ?

**Comment by briangrossman** [comment]
Note that I updated all the URLs to the form `/courses/[courseId]/course/` which seems to fix this problem... though I'm still not sure why.

Note that for staff, these links will take you to the legacy UI, but for non-staff learners, this will log them into edX and take them to the new learner MFE.

**Comment by asadiqbal08** [comment]
The [PR](https://github.com/openedx/frontend-app-learning/pull/827) seems me closed by edX that chance seems me in a little scope much

**Comment by briangrossman** [comment]
This seems to be working now. Closing.
