### ISSUE TITLE
User remains subscribed to course emails after unenrolling

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#400]
### Steps to Reproduce

- Enroll in a course on MITx Online
- From the dashboard, unenroll from the course

### Expected Behavior

- Learner will be unsubscribed from course emails.

### Actual Behavior

- Learner's enrollment record still shows them subscribed to edX emails for the course (see image below)

### Related Issues

- https://github.com/mitodl/mitxonline/issues/288
- https://github.com/mitodl/mitxonline/pull/329
- https://github.com/mitodl/edx-api-client/pull/83
- Note: We may have to think about this when we implement deferrals, transfers, and refunds in the future

### Screenshot or Screencast

![Screen Shot 2022-02-07 at 2 19 01 PM](https://user-images.githubusercontent.com/21342568/152856775-5e246545-659c-4dc1-8dcf-5eb0c56e4df3.png)

**Comment by umarmughal824** [comment]
@briangrossman I guess if a user is unenrolled from edx, it would not be able to receive any emails against that course. Anyway, I have put up a PR for it
