### ISSUE TITLE
UI: Apply discount to basket/order

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#431]
### Designs

https://projects.invisionapp.com/share/KH11D3ZN53GC#/screens/462885073
https://projects.invisionapp.com/share/KH11D3ZN53GC#/screens/462972188
https://projects.invisionapp.com/share/KH11D3ZN53GC#/screens/462972599

Requirements

- [ ] Allow the user to apply at most one discount (we should make sure the backend enforces this if it doesn't yet)
- [ ] Discount computation should occur only on the backend, this might require some API updates.
- [ ] User can remove the discount (I don't think the designs have this, but it really should be allowed)
- [ ] Ensure the discounted price is applied to checkout

**Comment by jkachel** [comment]
Question: for the one-discount-per-order rule: should the customer be able to apply a discount over an already applied discount (i.e. I have discount code "halfoff" and try to apply "differentcode"; should "differentcode" overwrite "halfoff")? Or should it present an error and request that the user hit the clear button before applying another discount?

**Comment by rhysyngsun** [comment]
@jkachel I'd say just let the new code override the previous one
