### ISSUE TITLE
Update footer layout and styling

### ISSUE THREAD

**Issue by gsidebo** [mitodl/mitxonline#49]
Related: #41 
Desktop design: https://projects.invisionapp.com/d/main/#/console/21535972/455477372/preview
Mobile design: https://projects.invisionapp.com/d/main/#/console/21535972/455488637/preview

In #41 we updated the site footer and added resource pages to the CMS, but the footer still needs some layout and styling updates to match the designs. 

**Acceptance criteria:**
- Footer matches layout and styling of designs in all screen widths

**Out of scope:**
- Mailing list sign up text input and button (this can just be a blank space)

**Comment by arslanashraf7** [comment]
Closed via #129
