### ISSUE TITLE
Videos on course pages need closed captioning option available in controls

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#490]
### Steps to Reproduce

- Go to a course page. E.g.: https://mitxonline.mit.edu/courses/course-v1:MITxT+JPAL102x/
- Click play on the video

### Expected Behavior

- There should be a closed captioning value (CC) available in the video controls
- For reference, look at the video controls on [xPRO](https://xpro.mit.edu/)
- Please use the same controls that we use for xPRO
![image](https://user-images.githubusercontent.com/21342568/160133630-08edf4a0-ae32-4007-b796-3d843a7b4a13.png)

### Actual Behavior

- There is no closed captioning option on the videos
![image](https://user-images.githubusercontent.com/21342568/160133736-63cc276d-3118-46cc-98ee-c2ba6504538c.png)

### Related Issues
- https://github.com/mitodl/mitxonline/issues/80
   - PR: https://github.com/mitodl/mitxonline/pull/95

**Comment by pdpinch** [comment]
Can this be closed?

**Comment by arslanashraf7** [comment]
Yes, the ticket has made it to the end-user and deployed on prod.
