### ISSUE TITLE
Dashboard: don't allow paid learners to unenroll 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#534]
As a paid learner, I want a refund when I unenroll from a course. But getting a refund requires contacting customer support. 

#### Designs and Mockups

tbd

#### Acceptance Criteria:

- [ ] If a learner has paid for a course, don't let them unenroll themselves
- [ ] If a paid learner clicks on the unenroll menu item in the dashboard, display a message with a link to contact customer support 

#### Related issues 

- block learners from unenrolling in open edX

**Comment by pdpinch** [comment]
This is on hold until I can confirm a policy question about the relationship between enrollment and payment.

**Comment by pdpinch** [comment]
Ok, I confirmed a few things:

- getting a refund always requires contacting customer service
- when a user gets a refund, we will always unenroll them (in some cases, they can enroll again if they like)

**Comment by jkachel** [comment]
This has been on production for a bit; closing.
