### ISSUE TITLE
Story: As a Learner I want to be able to receive flexible pricing for a program

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#539]
Learners want to be able to apply for and receive flexible pricing for a given program

### Issues
- [x] https://github.com/mitodl/mitxonline/issues/573
- [x] https://github.com/mitodl/mitxonline/issues/542
- [x] https://github.com/mitodl/mitxonline/issues/541

**Comment by jkachel** [comment]
Do flexible pricing submissions need to be tied to a specific course/program (i.e. should that be part of the data captured in the form)? Should there also be an access flow to the flexible pricing form from the individual product page (like the widget we have for certificate upgrades now)?

**Comment by rhysyngsun** [comment]
@jkachel for now, lets tie them to a specific program, meaning the form would need to live on a page on or under a program page in the catalog. 

In terms of the link, I think Wagtail supports linking to pages in the rich text editor, so that is covered. If there's a need for a more prominent CTA we can probably deal with that separately. Plus, we won't need that until we're ready to flip the switch on this.

**Comment by briangrossman** [comment]
@rhysyngsun 
I just wanted to call to your attention the fact that a price is displayed within the course in the upgrade panel:
![image](https://user-images.githubusercontent.com/21342568/170297859-6e5e3e54-6c59-40b5-8d36-53aaaa83a2f8.png)

This value is set along with the verified course mode in `/admin/course_modes/coursemode/` (a separate location than where we set the price for a product)

We should consider if we need to do anything special for this.

**Comment by rhysyngsun** [comment]
> @rhysyngsun I just wanted to call to your attention the fact that a price is displayed within the course in the upgrade panel: ![image](https://user-images.githubusercontent.com/21342568/170297859-6e5e3e54-6c59-40b5-8d36-53aaaa83a2f8.png)
> 
> This value is set along with the verified course mode in `/admin/course_modes/coursemode/` (a separate location than where we set the price for a product)
> 
> We should consider if we need to do anything special for this.

Oh...that's a bit complicated... hiding the amount is probably going to be the immediate option to address this, I think because OpenedX has one price per course mode, we'd need to have multiple course modes to be able to show whatever price the learner has been given.

**Comment by rhysyngsun** [comment]
Closing this as we've completed the bulk of the work
