### ISSUE TITLE
Flexible Pricing: Automatically approve if the Learner is elligible when they request it

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#542]
We want to be able to automatically approve learners for flexible pricing based on their income and location. This should occur immediately when the learner submits their income information.

There is a preexisting implementation of this in MicroMasters that we should pull in: https://github.com/mitodl/micromasters/blob/master/financialaid/api.py#L45

This diagram roughly illustrates the way we want our models setup:

```mermaid
flowchart LR
    Course1 --> Program
    Course2 --> Program
    Course3 --> Program

    Product1 --> Course1
    Product2 --> Course2
    Product3 --> Course3

    FlexiblePriceTier1[Tier: Full Price]
    FlexiblePriceTier2[Tier: 50% Off] --> Discount2[Discount: 50% Off] --> Product1 & Product2 & Product3
    FlexiblePriceTier3[Tier: 75% Off] -->  Discount3[Discount: 75% Off] --> Product1 & Product2 & Product3

    FlexiblePriceTier1 & FlexiblePriceTier2 & FlexiblePriceTier3 --> Program

    Learner1[Sally Ride] --> FlexiblePrice1["Flexible Price Request (High Income)"] --> FlexiblePriceTier1 & Program
    Learner2[Ada Lovelace] --> FlexiblePrice2["Flexible Price Request (Medium Income)"] -->FlexiblePriceTier2 & Program
    Learner3[Marie Curie] --> FlexiblePrice3["Flexible Price Request (Low Income)"] -->FlexiblePriceTier3 & Program

    linkStyle 6,7,8,9 stroke:#3ff
    linkStyle 10,11,12,13 stroke:#f3f
    
    linkStyle 14,15,16,17,18,19,20,21,22,23,24,25 stroke:#999

```

- [x] https://github.com/mitodl/mitxonline/issues/596
- [x] https://github.com/mitodl/mitxonline/issues/597
- [x] https://github.com/mitodl/mitxonline/issues/598

**Comment by asadiqbal08** [comment]
@rhysyngsun I noticed an [issue](https://github.com/mitodl/mitxonline/issues/559) created by @umarmughal824 for introducing financial aid model. Let me know, is there any other issue where user will enter some data as happening in micromaster something like that or this issue actually implements this flow ? pointing out to [FinancialAidRequestView](https://github.com/mitodl/micromasters/blob/master/financialaid/urls.py#L30)
![Screenshot 2022-05-13 at 5 21 34 PM](https://user-images.githubusercontent.com/7334669/168282042-c2060a3d-939c-41e1-956c-8b2be3cd0130.png)

**Comment by rhysyngsun** [comment]
@asadiqbal08 this would be done on top of the work for #573. In the process of submitting that form, this logic should be done.

**Comment by umarmughal824** [comment]
@asadiqbal08 as per our conversation, I am assigning that ticket as it's a pre-requisite of my ticket.

**Comment by umarmughal824** [comment]
@pdpinch / @rhysyngsun aren't we going to add Tier and Tier Program here? If we are going to add, a brief introduction about them would be good to know.

**Comment by rhysyngsun** [comment]
@umarmughal824 Yes, I think you're right that we need something similar to that, but I'm not certain we want to duplicate it exactly. I'm going to think on this a bit and get back to you with an answer before Monday here.

**Comment by rhysyngsun** [comment]
@umarmughal824 I've updated the description on this, since the pricing form is merged I think you're unblocked.

**Comment by umarmughal824** [comment]
@jkachel I have created the form on wagtail under the course.  But I have visited every single page but could not any link for the flexible pricing form. Could you please let me know where could I see it or do I need to enable any feature flag? But if I directly hit the Live View on the page it shows an error

<img width="1440" alt="Screenshot 2022-05-27 at 16 21 52" src="https://user-images.githubusercontent.com/4043989/170690216-9e472150-ac93-4cd0-ad65-20980bcb16c4.png">

**Comment by jkachel** [comment]
@umarmughal824 the link to the Flexible Pricing form for the course needs to be added to the course page - it doesn't do it automatically. (You can have multiple forms attached to a course so it doesn't make a judgement about which one should be displayed on the course page.) The field error you're getting there is probably because you don't have any exchange rates in the database (the Country field type builds its option list out from that table). That could probably fail more gracefully, though; I'll take a look at that separately. Finally, you can make a form without the required fields - there didn't seem to be a good way to validate that but will look at that separately as well.

**Comment by umarmughal824** [comment]
@rhysyngsun I am still confused what's the criteria for auto-approval. If it's less than the threshold should it be eligible for auto-approval?

**Comment by rhysyngsun** [comment]
@umarmughal824 I've cleaned up this issue and added a diagram that illustrates the relationships between the data models, I hope that helps you a bit.

In terms of the logic, yes, if the learner's income is less than the threshold for the country they are auto-approved. Specifically, the code for this is [here](https://github.com/mitodl/micromasters/blob/fbff5299e71bf12e1a4ed03c5620d92c49f559da/financialaid/api.py#L45) in MicroMasters.
