### ISSUE TITLE
OpenedX: upgrade/pay messsage for courseware sidebar

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#556]
We [previously implemented](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_checkout_external) a plugin for OpenedX that sets up an appropriate redirect to MITx Online when a learner attempts to pay.

We need to follow up to make sure the user experience is correct. We're expecting it to look like this:

![Screenshot 2022-05-12 at 21-07-40 Course - Upgrade Without Cert Graphic](https://user-images.githubusercontent.com/28598/168191473-a76f284a-8c6b-405c-8df0-94ea029726cb.png)

NOTE: the wording in this screenshot is placeholder, I have the final wording somewhere I believe but can't find it as of this writing.

If it doesn't, we need to determine how to change the look of this component and implement that.

**Comment by arslanashraf7** [comment]
Update:

So while looking at the issue I identified the following things:

1) The upgrade functionality for a course is visible not in one but two places [the Dashboard](https://courses-qa.mitxonline.mit.edu/dashboard) & [the MFE outline](https://courses-qa.mitxonline.mit.edu/learn/course/course-v1:Arbisoft+ARB_TEST_CKT_001+1/home)
2) We should be able to update the dashboard design through our theme at https://github.com/mitodl/mitxonline-theme (Or not since we have a redirect in place I think)
3) However, [the implementation in the MFE](https://github.com/openedx/frontend-app-learning/blob/master/src/generic/upgrade-notification/UpgradeNotification.jsx#L348-L505) is not directly/easily overridable and we could go with following ways

    3.1 ) The short and easy way of getting what we want can be done in [our fork of frontend-app-learning](https://github.com/mitodl/frontend-app-learning) where we could do something like we [did for footer](https://github.com/mitodl/frontend-component-footer-mitol/pull/1) in past.

    3.2 ) We go for upstreaming, As seen in the above implementation link, the upgrade functionality would not just need architectural changes in the labels but the HTML itself where the custom text might come from an API call/or environment. This change might require a longer time and effort.

In addition to the above, The upgrade card in the MFE is preconditioned based on FBE([Feature Based Enrollment](https://github.com/openedx/frontend-app-learning/blob/master/src/generic/upgrade-notification/UpgradeNotification.jsx#L361)) & [Non-FBE](https://github.com/openedx/frontend-app-learning/blob/master/src/generic/upgrade-notification/UpgradeNotification.jsx#L442). so whichever option we follow we will need to check if we will be providing FBE courses or not.


@pdpinch @rhysyngsun what is your opinion on this?

**Comment by pdpinch** [comment]
What does it currently display, on the learner MFE and the dashboard?

**Comment by arslanashraf7** [comment]
> What does it currently display, on the learner MFE and the dashboard?


@pdpinch Attaching the screenshots below, Also i created [this test course](https://rc.mitxonline.mit.edu/courses/course-v1:MITx+CHECKOUT/) in which you can enroll and explore more.

**On Dashboard**
<img width="1341" alt="Screenshot 2022-05-20 at 7 42 56 PM" src="https://user-images.githubusercontent.com/34372316/169552906-ac82e72e-82a1-4a26-80d2-aa03d6bbdd7f.png">

**On MFE**
<img width="1668" alt="Screenshot 2022-05-20 at 7 43 08 PM" src="https://user-images.githubusercontent.com/34372316/169552928-0ef2dbaf-525f-47e5-850d-383857f9095b.png">

**Comment by pdpinch** [comment]
@arslanashraf7 why can't we use your plugin to overide the message?

**Comment by rhysyngsun** [comment]
@pdpinch the plugin just handles the redirection of the link provided in app so the learner ends up on MITx Online. I think modifying the theme is the main way to do this on the frontend.

@arslanashraf7 I think if we already have a fork of the MFE for UI adjustments, just continuing to work with that is probably our best option. Were something to be done upstream, I think we'd want it to be a broader conversation with OpenedX around theming MFEs. Same for the theme since we should have that all in one place too.

**Comment by arslanashraf7** [comment]
@rhysyngsun Thanks for the insight, I think as of now the most reasonable would be to do this change in our fork. 
However, I think of a few things alongside. I don't see any custom changes merged in this Fork, which makes me curious if we are running any of our instances from this fork. 
For this, I think we can check with @blarghmatey if we are using our [frontend-app-learning](https://github.com/mitodl/frontend-app-learning) fork.

Although I've started working on a PR for this design change in the fork just in case.

**Comment by pdpinch** [comment]
> In addition to the above, The upgrade card in the MFE is preconditioned based on FBE([Feature Based Enrollment](https://github.com/openedx/frontend-app-learning/blob/master/src/generic/upgrade-notification/UpgradeNotification.jsx#L361)) & [Non-FBE](https://github.com/openedx/frontend-app-learning/blob/master/src/generic/upgrade-notification/UpgradeNotification.jsx#L442). so whichever option we follow we will need to check if we will be providing FBE courses or not.

We were not planning on providing FBE courses. Is that a problem? I don't really understand why the upgrade card would be conditional on the FBE feature.

**Comment by arslanashraf7** [comment]
> > In addition to the above, The upgrade card in the MFE is preconditioned based on FBE([Feature Based Enrollment](https://github.com/openedx/frontend-app-learning/blob/master/src/generic/upgrade-notification/UpgradeNotification.jsx#L361)) & [Non-FBE](https://github.com/openedx/frontend-app-learning/blob/master/src/generic/upgrade-notification/UpgradeNotification.jsx#L442). so whichever option we follow we will need to check if we will be providing FBE courses or not.
> 
> We were not planning on providing FBE courses. Is that a problem? I don't really understand why the upgrade card would be conditional on the FBE feature.

>We were not planning on providing FBE courses. Is that a problem?

No, If we were using FBE courses we might need to make changes in a couple of different code blocks for the Upgrade message. More details in the next answer.

>I don't really understand why the upgrade card would be conditional on the FBE feature.

- So, they show different types of messages title/description for [course upgrades when a course is FBE based](https://github.com/openedx/frontend-app-learning/blob/master/src/generic/upgrade-notification/UpgradeNotification.jsx#L361-L442). These messages include offers, offers expiration time/days based messages, etc.

- There is only [one message for the Non-FBE](https://github.com/openedx/frontend-app-learning/blob/master/src/generic/upgrade-notification/UpgradeNotification.jsx#L442-L450). 

So if we are not planning on using FBE-based courses we might need to make changes in one place only.

**Comment by arslanashraf7** [comment]
@pdpinch What's your opinion on changing something similar for the dashboard (Screenshot in the above comment) in [MITxOnline-theme](https://github.com/mitodl/mitxonline-theme).

Although, for the dashboard in the edx-platform we have a redirect in place that takes the user to the dashboard of MITxOnline marketing site. A user can only see the edx-platform dashboard when he/she enters the URL manually.

**Comment by pdpinch** [comment]
We would like users to go to the mitxonline dashboard instead of the open edX dashboard, so we don't need to override the dashboard template. 

If we have some users still landing on the open edX dashboard, our time would be better spent stopping that.

**Comment by arslanashraf7** [comment]
@pdpinch I was able to verify this on https://courses-qa.mitxonline.mit.edu/learn/course/course-v1:MITx+14.750x+3T2021/home, Should we close this ticket, or maybe if you'd like to have a look and then decide.

**Comment by pdpinch** [comment]
I'm satisfied, esp. since this is working in production now.
