### ISSUE TITLE
Ecommerce: Support for free courses

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#561]
### Steps to Reproduce

On RC:
- Create a test course in studio (e.g. https://studio-qa.mitxonline.mit.edu/course/course-v1:MITx+0.00x+0T0000)
- Create an associated `course` and `course run` in the Django admin
   - Do not create a product for now
- Create a page for the course in the CMS (e.g. https://rc.mitxonline.mit.edu/cms/pages/20/edit/) 
- Go to the product page: (e.g. https://rc.mitxonline.mit.edu/courses/course-v1:MITx+0.00x/)
- Click `Enroll Now`

### Expected Behavior

- The learner will be able to enroll in the course

### Actual Behavior

- The `Enroll now` button doesn't enroll the learner in the course

### Additional Details

Alternatively, we could create a product for the course for a price of $0.00. Currently, if we create a product for $0.00, we get a situation where the learner is asked to pay $0.00 to get a certificate for a free course:
![image](https://user-images.githubusercontent.com/21342568/168134301-3112cd73-4ef2-420d-946b-6dd1c6a677fa.png)
This is confusing.

Note: Based on discussion, we would never have a case where we would issue a certificate for a free course.

**Comment by pdpinch** [comment]
I'm a bit confused by the circumstances that led to this. If a course is audit-only (and thereby, enrollment is free). I don't think it should have a product at all. It certainly shouldn't require or encourage the user to go through a check-out process.

**Comment by jkachel** [comment]
The underlying issue is that the button just toggles the upgrade dialog, which then returns null if there's no product to upgrade with, so you get a button that does nothing. It really should just POST to the enrollment form in that case (like it did before ecommerce). PR #564 should fix that.
