### ISSUE TITLE
Refunds: Port Google Sheets refund integration from xPro project

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#572]
The reference implementation for google sheets is [here](https://github.com/mitodl/mitxpro/tree/master/sheets) in xPro.

This implementation has many features we don't want to carry over because we won't use them:

- Coupon requests
- Deferral requests
- B2B enrollment code requests

We'll implement these in `ol-django`:

- [x] https://github.com/mitodl/ol-django/issues/67
  - [x] https://github.com/mitodl/ol-django/issues/68
  - [x] https://github.com/mitodl/ol-django/issues/69

**Comment by rhysyngsun** [comment]
@annagav I think this would be a good issue for you to take next. Let me know if I can clarify anything here.

**Comment by briangrossman** [comment]
@rhysyngsun 

I'm glad that @annagav will be looking at this functionality. 

Can you clarify what exactly we don't need to carry over? There's enough ambiguity in some of the terms that I want to make sure we know what's what.

You said we shouldn't bring over: 

> - Coupon requests
> - Deferral requests
> - B2B enrollment code requests

The core components of the [Google Sheets functionality](https://github.com/mitodl/mitxpro/blob/master/sheets/README.md) are:

1. Enrollment Code Request sheet
   - Someone places an order for a number of enrollment codes for a given product
   - This is entered in a Google form which generates an entry in the Enrollment Code Request sheet
2. Enrollment Code Assignment sheet
   - After the order is placed above, we create an Enrollment Code Assignment sheet which contains a row for each enrollment code.
   - We add emails to the assignment sheets which automatically sends enrollment invitations to those learners
   - The sheet tracks who has enrolled in the course / program
3. Change of Enrollment Request sheet
   - Customer support is able to request refunds and deferrals through a Google form
   - This generates a row in the appropriate tab in the Change of Enrollment Request sheet
   - For refunds, finance enters data in the finance columns
   - These rows are processed to automatically kick off the refund or deferral

Related functionality:

- Bulk Credit Card purchase
   - Sort of related, we have the bulk credit card purchase functionality ([link](https://xpro.mit.edu/ecommerce/bulk/))
   - Learners can place bulk orders on their own. 
   - They can download a .csv that has URLs to distribute to learner for enrollment

Do you mind clarifying which functionality will and won't be brought over to MITx Online? 

Thanks.

**Comment by rhysyngsun** [comment]
@briangrossman it's most likely only the third one, I wasn't aware it also did deferrals too I thought it was refunds only which is maybe why there's a disconnect here.
