### ISSUE TITLE
Flexible Pricing: Staff UI: A button to reset the flexible pricing request (this should allow the learner to submit another request).

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#577]
### Acceptance Criteria

- [ ] This button should ask for confirmation of the action about to be taken.
- [ ] Once confirmed, the UI should make the appropriate API request to remove the flexible pricing request.
- [ ] The UI should be updated to reflect this and the staff user given a toast alert confirming it.

**Comment by jkachel** [comment]
Bit of a cheatsheet for this (most of this from #576 except the very last bit):

* This would be added as actions to the list page - `pages/flexible_pricing/list.tsx`. This doesn't have any existing actions, but there are some in the Discounts list page (`pages/discounts/list.tsx`). These would be a good example of how this generally works.
* There's a couple things in the docs to look at:
   * There's a DeleteButton component in there that you might be able to extend for this: https://refine.dev/docs/ui-frameworks/antd/components/buttons/delete-button/ This specifically pops up a modal for confirmation. This is a Refine component so looking at the source for it would be informative. 
   * There's also [Custom Pages](https://refine.dev/docs/guides-and-concepts/custom-pages/) which would be useful for putting the confirmation on a separate page. The Example in there specifically uses `useUpdate` (internal to Refine) to approve/deny a blog post, so the workflow there is pretty similar to approving Flexible Pricing here. 
   * Personally, I'd go with the modal option.

In terms of the API side of this, should be pretty simple to just flip the FlexiblePrice record to "reset". The `FlexiblePricingRequestForm` model in `cms` will also need updating; right now, it checks for the existance of a FlexiblePrice record at all so it should be changed to also filter out records in status "reset".
