### ISSUE TITLE
Load currency exchange rate

### ISSUE THREAD

**Issue by umarmughal824** [mitodl/mitxonline#589]
Load currency exchange rate

#### Acceptance Criteria:

- [x] management command to load currency rate
- [x] celery task

**Comment by umarmughal824** [comment]
@pdpinch there is a difference between the current currency rate and the saved values on micromasters RC.

- AFN (Current: 89, but saved is 90.5)
- XOF (Current: 611, but save is 612)
- INR (Current: 77.61, but saved is 77.52)
- etc

So, instead of fetching from the model, I think we should keep fetching through the exchange rate API as in micromasters.

@rhysyngsun what do you suggest?

**Comment by rhysyngsun** [comment]
@umarmughal824 there's [a task in MicroMasters](https://github.com/mitodl/micromasters/blob/master/financialaid/tasks.py#L13) that does that. I'd thought we'd brought it over but if we haven't that would need to be done.
