### ISSUE TITLE
Flexible Pricing:  Add data model for `FlexiblePriceTier`

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#596]
We need to add a data model that represents the income thresholds needed to receive a given discount. This will enable us to then create a corresponding `UserDiscount` record that officially assigns the discount to a given user.

```python
class FlexiblePriceTier(TimestampedModel):
    """
    The tiers for discounted pricing
    """
    discount= models.ForeignKey(Discount, null=True, related_name="flexible_price_tiers", on_delete=models.PROTECT)
    courseware_content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)  # add a filter to limit this to program/course contenttypes
    courseware_object_id = models.PositiveIntegerField()
    courseware_object = GenericForeignKey('courseware_content_type', 'courseware_object_id')
    current = models.BooleanField(null=False, default=False)
    income_threshold_usd = models.IntegerField(null=False)
```
- A record with `discount=None` will be the full price tier
- The `courseware_object` relation will allow us to look up pricing tiers that a `FlexiblePrice` has been submitted for

**Comment by pdpinch** [comment]
Do you mean an mitxonline version of this ? 

<img width="1042" alt="image (18)" src="https://user-images.githubusercontent.com/430126/170785154-c8181197-7f32-4c31-828e-e17aab9f3c51.png">

(screenshot from `/admin/financialaid/tier/`)

**Comment by rhysyngsun** [comment]
@pdpinch no, those records are purely textual descriptions and it's a bit overdesigned so I wasn't planning on having us mirror that. The record that's comparable is `ProgramTier`.

**Comment by umarmughal824** [comment]
closed as already done in https://github.com/mitodl/mitxonline/pull/580
