### ISSUE TITLE
Flexible Pricing: Add additional relationship columns to `FlexiblePrice`

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#597]
We need to be able to associate a learner's request for flexible pricing to a specific program or (at a later date) course. Since these are two different tables, we need to use Django's `contenttypes` framework to accomplish this. We also need to be able to associate a`FlexiblePrice` record with the [`FlexiblePriceTier`](https://github.com/mitodl/mitxonline/issues/596) that they are assigned.

- Add a `GenericForeignKey` to `FlexiblePrice` that can point at either a `Program` or a `Course`.
- Add a nullable, null by default, `ForeignKey` column to `FlexiblePrice` that points to `FlexiblePriceTier`.

**Comment by asadiqbal08** [comment]
There is a confusion over this point. 
>> Add a GenericForeignKey to FlexiblePrice that can point at either a Program or a Course.

`FlexiblePrice` model do not have any `courseware_object_id` field but we introduced a GenericForeignKey `courseware_object = GenericForeignKey('courseware_content_type', 'courseware_object_id')` in `FlexiblePriceTier`. 

Can you tell me do we need GenericForeignKey to FlexiblePrice model ?

**Comment by umarmughal824** [comment]
@asadiqbal08 please take  a look on my PR https://github.com/mitodl/mitxonline/pull/580

**Comment by umarmughal824** [comment]
https://github.com/mitodl/mitxonline/pull/580
