### ISSUE TITLE
Update Text on Exam Submission

### ISSUE THREAD

**Issue by sfrucht** [mitodl/mitxonline#604]
As a learner, I'd like to be less confused when I see the text when I submit my exam.

Currently, when you submit a proctored exam, the text that appears (prior to the due date) is: "Proctoring results are usually available within 5 business days after you submit your exam." (See screenshot).

Learners associate this to mean that they will receive their grades within this amount of time so I am wondering if we can update the text to make it clear that this is only about the video review.

#### Designs and Mockups
<img width="1258" alt="Screen Shot 2022-06-02 at 11 10 04 AM" src="https://user-images.githubusercontent.com/899424/171664559-2330ec06-bbcc-4579-9eff-96bafa876e13.png">

#### Acceptance Criteria:

- [ ] Requirement

#### Out of Scope

- Not going to do

**Comment by sfrucht** [comment]
Just updating here... Not only does this text appear with submission, but the learner also receives an email saying "You should receive an email with your exam status within 5 business days." (see attached) I think this is where the learners are getting confused and sending in emails after 5 days asking about their grades.
[Proctoring Review In Progress For Political Economy  Economic Development  PROCTORED EXAM Proctored Exam.pdf](https://github.com/mitodl/mitxonline/files/8825960/Proctoring.Review.In.Progress.For.Political.Economy.Economic.Development.PROCTORED.EXAM.Proctored.Exam.pdf)

**Comment by pdpinch** [comment]
@sfrucht would you mind opening this on https://github.mit.edu/mitxonline/mitxonline-issues/issues instead of here?
