### ISSUE TITLE
Flexible Pricing Staff UI: A button to deny the flexible pricing request

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#607]
As a staff member, I'd like to be able to deny an incoming request for Flexible Pricing. 

### Acceptance Criteria

- [ ] The button should ask for confirmation of the action to be taken, similar to how the Reset and Approve buttons work. 
- [ ] Once confirmed, the UI should make the appropriate API call to deny the request. 
- [ ] The UI should update once the API call returns and a toast should display.
- [ ] The learner should *not* be able to re-request Flexible Pricing for given course.

**Comment by jkachel** [comment]
@asadiqbal08 we're using the "skipped" status for this. The form code already checks for a request in the "skipped" state and won't display the form if it finds one so just verifying functionality on that part of it.

**Comment by asadiqbal08** [comment]
Thanks for answering yes I up a PR and the code id placed already that check for `skipped` state.
