### ISSUE TITLE
Flexible Pricing Staff UI: Capture a justification for Flexible Pricing request status changes

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#608]
As a staff member, when I change the status of a Flexible Pricing request, I'd like to provide a justification of why I am changing the status of the request. The justification should be one from a set of pre-defined justifications available in the app. 

### Acceptance Criteria
- [ ] The justification field should appear in the confirmation modal that's displayed when the status buttons are activated.
- [ ] The options in the justification field should mirror the ones in MicroMasters (see [this blob](https://github.com/mitodl/micromasters/blob/7546f4e962bd65b5a341351bf47f411b3d9d9084/financialaid/constants.py#L9-L19))
- [ ] If the user confirms the change, the justification should be sent as part of the payload and should be captured in the appropriate column in the database.
- [ ] Justifications should be shown (but not editable) ~~when the request is in the Approved state~~ in the table.

This should work much like it does in MicroMasters. I think issue #607 should be done before this.

**Comment by jkachel** [comment]
Question for @pdpinch / @rhysyngsun regarding placement of the justification field: In MicroMasters, the justification field is in the table. However, since we're using a modal for confirmation in the Refine admin, we can potentially have that field be there. (MM uses an `alert` for this.) Having it in the confirmation modal keeps it out of the table (and makes it less cramped looking, especially with the search pane on the left and/or the nav expanded) and would give us the potential to filter the justification list by status. Thoughts on this?

**Comment by pdpinch** [comment]
@jkachel I like the idea of having it in the confirmation modal, if it's not too much work.

**Comment by asadiqbal08** [comment]
@jkachel regarding this
>> Justifications should be shown (but not editable) when the request is in the Approved state.

I guess, we should show the justification in the `Admin JS <Table/>` there whatever the state regardless of showing just in case of "Approved" status ? thoughts ?
