### ISSUE TITLE
Receipt page is empty when there is no discount code

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#619]
### Steps to Reproduce

1. Purchase a course on RC, using the instructions at https://docs.google.com/document/d/1JUMIABviilgnctn9mJcrFdlw8xzd0HUyn9kXNg4Xvts/edit#
2. You should get an email with a link to your receipt
3. View the receipt

### Expected Behavior

- receipt should display, with all the relevant info 
 
### Actual Behavior

- page is empty 

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/430126/173445744-aecbaa5f-b458-4b7b-9189-5a052443bb50.png)

**Comment by jkachel** [comment]
In testing, this appears to be an issue with the code that displays the discounts codes on the page. 
* Testing with a user that has used (method doesn't matter) a discount code: receipt displays fine
* Testing with a user that has not used a discount code: blank page

Relevant test transactions on RC: orders 263 and 264

**Comment by pdpinch** [comment]
I'm reopening this because it's still happening. I'm not sure if it was a regression or if the fix was incomplete. 

I just tested this on RC, and my email receipt comes with a link to just https://rc.mitxonline.mit.edu/orders/receipt/ which seems incomplete to me. I think the link should have been https://rc.mitxonline.mit.edu/orders/receipt/302/

**Comment by jkachel** [comment]
Yup, closing this
