### ISSUE TITLE
Disable automatic Cybersource emails on purchase 

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#637]
As a purchaser of an MITx Online course, I'd like to receive a single, clear receipt. By default, learners are emailed a receipt from Cybersource as well as our custom receipt from MITx Online. 

#### Designs and Mockups

Cybersource Receipt
![image](https://user-images.githubusercontent.com/21342568/175108694-646b1890-872b-4418-a5ad-7abdf6f97e9d.png)

Custom Receipt:
![image](https://user-images.githubusercontent.com/21342568/175108604-829263fe-74a0-4815-9f9c-3bbb9cb3f3b9.png)

#### Acceptance Criteria:

Disable the Cybersource receipt from the Cybersource admin under Notifications
![image](https://user-images.githubusercontent.com/21342568/175108952-fd461ea8-9093-4447-a167-3ce231ed3cf4.png)

- [x] RC
- [ ] Production - once ecommerce for MITx Online has launched to production

**Comment by pdpinch** [comment]
This is moot, now that we have separate profiles for micromasters and mitxonline
