### ISSUE TITLE
Validation error for readble ID with a dot in it

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#64]
### Steps to Reproduce

1. add a course at /admin/courses/course/add/
2. set the "Readable Id" to a value with a `.` (dot) in it, like `course-v1:MITx+14.100x`
3. click save

### Expected Behavior

Course saves.

### Actual Behavior

Validation Error: `This field is used to produce URL paths. It must contain only characters that match this pattern: [\w\-+:]
`

It's not even clear to me what URL this ID is being used for, because the corresponding course detail page is at  https://mitxonline-rc.mitxonline.mit.edu/microeconomics/

**Comment by umarmughal824** [comment]
@pdpinch I did not either see any corresponding link in the project against that uses the `readable_id`. I don't have much context about `mitx-online` so I can't say anything.
