### ISSUE TITLE
Flaky test in `ecommerce/views_test.py`

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#643]
See the log output from this:

https://github.com/mitodl/mitxonline/runs/7026103146?check_suite_focus=true#step:14:321

This is occasionally failing on github actions.

**Comment by rhysyngsun** [comment]
As a temporary workaround I added the `flaky` package and annotated this test so that if it fails once it doesn't require a rerun of the entire test suite: https://github.com/mitodl/mitxonline/blob/main/ecommerce/views_test.py#L184

**Comment by jkachel** [comment]
Think this is OK now with the rework done in #653.
