### ISSUE TITLE
MM Data Migration: Migrate Learner orders from MicroMasters

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#657]
Summary
---

We need historical purchase data to be brought over from MicroMasters. There are some aspects of this that are a bit complicated, we should address them individually though:

- Historically DEDP learners were permitted to take 2 exams for every purchases
- Recently, we shifted this to 1 exam per purchase
- Some learners have purchased exams, but not taken them yet. MicroMasters limits learners to 1 unused purchase per course.

##### Order

This is pretty straightforward since most of the fields are identical.

##### Line

Line is a little trickier, but maps 1 to 1:

- `quantity=1`
- `purchased_content_type` - you'll need to join on the contenttypes table and get the id that represents course runs
- `purchased_object_id` - this will be the course run id, which we'll need to make a best guess on. Is it possible to select the run that meets the criteria of having been made after `enrollment_start` but before `upgrade_deadline`? I'm not sure if that will work without conflicts or not.
- `product_version` - TBD???
- 

##### Transaction

Transaction will get derived from `Receipt`:

- `data` is the same
- `amount` should come from the order's `total_price_paid`
- `transaction_type="payment"`
- `reason=""`

**Comment by rachellougee** [comment]
@rhysyngsun I plan to work on https://github.com/mitodl/mitxonline/issues/702 first as this one is marked as blocked. Could you give some details like what tables are involved and the business logic with this order migration?

**Comment by rhysyngsun** [comment]
@rachellougee I updated the description with what I think the mappings will be

@pdpinch:
 - Could you sanity check those?
 - MM has a `partially_refunded` state, any thoughts on what to do with those as we never implemented them in xPro or MITx Online? I see 3 orders in this state in production.
- In MITx Online we record refund `Transaction` records, should we create equivalents here? The cybersource `data` would have to be empty or better have some kind of marker json to indicate that it's generated. Not sure how this would be affected by partial refunds as I'm guessing we probably don't have data on it, although if we do we could mark those transactions somehow and then manually repair them since they're only 3 orders.
- I have a question about order numbers, but I'm having trouble describing it in text so we should chat tomorrow

**Comment by pdpinch** [comment]
Regarding migrating lines:

> `purchased_object_id` - this will be the course run id, which we'll need to make a best guess on. Is it possible to select the run that meets the criteria of having been made after enrollment_start but before upgrade_deadline? I'm not sure if that will work without conflicts or not.

I don't understand why this would be ambiguous. In MicroMasters we have a string`ecommerce_line.course_key` which should be equivalent to (post-migration) mitxonline's `courses_courserun.courseware_id`. I think we should be able to look up the appropriate `purchased_object_id`. 

I do think there's a question about `product_version` -- Is is necessary to create products for each course run?

**Comment by pdpinch** [comment]
regarding refunds, I'd like to talk to you a bit about this. There are some real use case for partial refunds. Even if we can't support the feature for some time, it would be good to lay out a plan for how to do so in the future. Maybe these 3 records are a place to start.

**Comment by rhysyngsun** [comment]
> Regarding migrating lines:
> 
> > `purchased_object_id` - this will be the course run id, which we'll need to make a best guess on. Is it possible to select the run that meets the criteria of having been made after enrollment_start but before upgrade_deadline? I'm not sure if that will work without conflicts or not.
> 
> I don't understand why this would be ambiguous. In MicroMasters we have a string`ecommerce_line.course_key` which should be equivalent to (post-migration) mitxonline's `courses_courserun.courseware_id`. I think we should be able to look up the appropriate `purchased_object_id`.

Sounds good, I didn't realize we stored anything related to the run since learners purchase courses instead of runs. :upside_down_face: 

> I do think there's a question about `product_version` -- Is is necessary to create products for each course run?

The products in theory would already exist, but the reason that points to product version is because that's a point-in-time snapshot of the product. I think our options are to either a) point this at the current product version or b) create some legacy products for each course and point the legacy purchases at those.

The difference between these would probably be if there was a historical price change at some point because if there are historical prices at different points it would cause the receipt to display conflicting information on the line item.

**Comment by rachellougee** [comment]
@rhysyngsun @pdpinch  I have two questions for you:

1. Could you confirm the order status we should be bringing over? (I briefly asked both of you about this)

Order status on MM | Order state on MO | Import 
-- | --|--
fulfilled | fulfilled| Yes
refunded | refunded| Yes
partially_refunded | ? | Yes
failed | errored | No?
created | ? | No

2. The product_version mapping seems a bit complicated, not sure if I am missing anything
   - product_version refers to reversion_version.id, not directly to a product
   - See some sample orders to be migrated from MicroMaster RC
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/3138890/184708518-b72c33e7-1ab5-400a-a27c-512dea04616a.png">

For example to import the above orders for 'Microeconomics' courserun_id =10 (2 different prices users paid at MicroMaster -$250, $100)
-   I would need to first look up ecommerce_product for this courserun by running the query 
  ```SELECT * FROM ecommerce_product WHERE object_id = 10 and content_type_id = 60; ```
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/3138890/184711246-aa6987d0-c343-4263-aa32-781b4c17aa0d.png">

-  From the above query, I got back id = 6 from ecommerce_product, then I need to find out what product versions are available for this product 
   ```SELECT * FROM reversion_version where object_id = '6' AND content_type_id = 79)```

![Screen Shot 2022-08-15 at 4 23 55 PM](https://user-images.githubusercontent.com/3138890/184713353-05bf4069-f217-465d-8b6f-58e2fcdbf07a.png)
 - As you can see, there are 5 versions of this product, but we don't have one for $250 yet. How should we handle it?

**Comment by rhysyngsun** [comment]
- @pdpinch mentioned to me that we do want to bring over those partial refunds, so we probably need to add that as a state. We need to decide how to fill in other information, but it may be a case of "don't worry about having an accurate transaction history for legacy partial refunds"
- In terms of product versions, it looks like this is going to be a bit tricky - the price on the line item isn't the price of the course run it's the price the learner _paid_ after discounts, so the computation of that was destructive.

**Comment by rhysyngsun** [comment]
Based on our meeting - we'll use the latest product version of the course run's product:

```sql
SELECT MAX(v.id)
FROM reversion_version as v
WHERE v.content_type_id IN (
        SELECT id
        FROM django_content_type
        WHERE model = 'product'
    )
GROUP BY v.object_id
ORDER BY v.object_id;
```

Also, since we'll be using the full price for the line item we'll need to account for the discounts that were applied  so that the receipt page displays correctly. This might involve creating some discounts to match historical ones.

**Comment by rachellougee** [comment]
@rhysyngsun Thank you. Just so I understand the correct logic to import MicroMaster courserun order to MITxOnline
1. Use the current version of the course-run product as you mentioned
2. If the learner paid less than the current course-run product (e.g. The current price is $999, learner paid $249 on MM), We then need to add a row to ecommerce_discountredemption
  - If there isn't a discount of $750 in ecommerce_discount, then first add a row to ecommerce_discount, finally reference it to ecommerce_discountredemption
  -  If there is a discount of $750 in ecommerce_discount, then just add a row to ecommerce_discountredemption with the existing discount_id

If that's what we want to do, it would be complicated to do all that in pure SQL. Is the discount part something we have to implement now?

**Comment by rhysyngsun** [comment]
For now, I think we'll just deal with bringing the orders over with the line items having the full price, same as any new orders done on MITx Online. Let's deal with the discounts separately - at this point their utility is in an accurate receipt and it would be ideal to be able to attribute these to financial aid pricing that was applied at the time, but I need to research this a bit to see if that's even feasible. If not, we'll just make a best effort of at least associating discounts so that the receipt page represents amounts correctly, even if we can't do the attribution accurately - if we don't have the info I think it's reasonable to say that historical DEDP orders just lack that context.

**Comment by rachellougee** [comment]
@rhysyngsun Ahh, there are a couple of issues discovered while testing it:
1. No unique Key on ecommerce_line and ecommerce_transaction, so line and transaction could be imported with duplicates if we run the import script multiple times. so we might need to add uniqueness for these two tables

2. Not all the course runs have the corresponding product on RC. I can add these on RC, but not sure how we are going to handle it on production
```
SELECT * FROM courses_courserun AS run 
LEFT JOIN public.ecommerce_product AS product
 ON run.id = product.object_id AND product.content_type_id = 60
 WHERE product.id is NULL
```

**Comment by rhysyngsun** [comment]
> @rhysyngsun Ahh, there are a couple of issues discovered while testing it:
> 
>     1. No unique Key on ecommerce_line and ecommerce_transaction, so line and transaction could be imported with duplicates if we run the import script multiple times. so we might need to add uniqueness to these two tables.
>        Actually, If these migrated orders only have 1 record per order in line/transaction tables, I could just add a left join to check if it's already imported

Yeah, I noticed this the other day as well but didn't realize it was going to affect your work. We probably need to unique on the transaction id from cybersource. For the line it'd probably be unique'd on the product.

> 
>     2. Not all the course runs have the corresponding product on RC. I can add these on RC, but not sure how we are going to handle it on production
> 
> 
> ```
> SELECT * FROM courses_courserun AS run 
> LEFT JOIN public.ecommerce_product AS product
>  ON run.id = product.object_id AND product.content_type_id = 60
>  WHERE product.id is NULL
> ```

Yeah, we'll need to create those. That might be reasonable to write a django management command or query to generate those - they're all a standard price and are probably easy to derive from existing data.
