### ISSUE TITLE
MM Data Migration: legacy final grades from MicroMasters

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#658]
We need to bring over the legacy grades for DEDP, these are spread out over a couple different models on MicroMasters:

- `FinalGrade`: the grade for a course run
- `ProctoredExamGrade`: the grade for an exam a learner sat for

Whenever a learner gets a new record of for either model, a `CombinedFinalGrade` is created or updated (https://github.com/mitodl/micromasters/blob/40deb7afba5cc93b2514fc2dfa050fdb96b1df54/grades/api.py#L299-L326). The combined grade is only at the `Course` level and it's continuously updated so it's not useful in populating historical grades. It's mentioned here for context and because we'll use a similar algorithm.

So the main problem we face here is that historically when a learner takes an exam and when they take a course run are not guaranteed to intersect however in MITx Online they _always_ will, so we need to figure out a reasonable way to map these over.

I think what is probably the most accurate would be to walk the learner's `FinalGrade` and `ProctoredExamGrade` records and compute what their `CombinedFinalGrade` would've been calculated as at that point in time and give them a grade for the most recent run combining the best of both in MITx Online.

#### Use Cases

- Learners that have taken at least one course run and one exam
  - We'll use an adapted version of the algorithm for `CombinedFinalGrade` to import these
- Learners that have taken at least one course run but no exams
  - We need to decide how to treat these grades as there's no exam grade to account for. 

#### Approach

We need to decide how to create `CourseRunGrade` records in MITx Online. Since these are rooted in runs we need to make sure that these records match up to enrollments. `FinalGrade` in MicroMasters follows this convention as well, so that's what we'll end up basing our approach off of.

**Comment by rachellougee** [comment]
@pdpinch @Ferdi I've run the number for DEDP program grades on production (related to the second use case described in the above issue)

- There are 40955 learners who have taken at least one course run but never taken the exam
- There are 2264 learners who have _paid_ for at least one course run (enrollment mode is either _verified_ or _honor_), but never taken the exam

Per discussed with @rhysyngsun last week, we are currently only bringing in DEDP grades in the first use case in the ticket

> Learners that have taken at least one course run and one exam

**Comment by Ferdi** [comment]
>  There are 40955 learners who have taken at least one course run but never taken the exam

Can we get a distribution by year ?  

> There are 2264 learners who have paid for at least one course run (enrollment mode is either verified or honor), but never taken the exam

I thought the DEDP courses from edx.org where all "audit" mode.    I'm curious to know where "verified" / "honor" comes from.   Are these from old days, before we accepted payment on mm.mit.edu ?

**Comment by rachellougee** [comment]
- Here is the distribution by year.
  (not sure what date this should be based on, but the following number is based on the learner's graded date for course run)
  (The sum of these numbers is more than 40955 as learners can be double counted in year distribution)

graded_year | Learner count
-- | --
2017 | 9,963
2018 | 7,438
2019 | 8,033
2020 | 12,054
2021 | 8,555
2022 | 4,416

query used for reference in case I miss something
```        
SELECT EXTRACT(YEAR FROM DEDP_grades.created_on) AS graded_year, COUNT(DISTINCT DEDP_grades.user_id) FROM 
(
    SELECT grade.user_id, grade.course_run_id, courserun.course_id, grade.created_on
    FROM grades_finalgrade as grade
    JOIN dashboard_cachedenrollment AS enrollment ON grade.course_run_id = enrollment.course_run_id AND grade.user_id = enrollment.user_id
    JOIN public.courses_courserun AS courserun ON grade.course_run_id = courserun.id
    JOIN public.courses_course AS course ON course.id = courserun.course_id
    WHERE course.program_id =2 
) AS DEDP_grades
LEFT JOIN 
(
    SELECT examgrade.user_id, examgrade.course_id
    FROM grades_proctoredexamgrade as examgrade 
    JOIN exams_examrun AS exam ON examgrade.exam_run_id = exam.id
    JOIN courses_course  AS course ON exam.course_id = course.id
    WHERE course.program_id =2 
) AS DEDP_exam
  ON DEDP_grades.user_id = DEDP_exam.user_id AND DEDP_grades.course_id =DEDP_exam.course_id
WHERE DEDP_exam.user_id IS NULL
GROUP BY graded_year;
```


- The following DEDP courses have enrollment modes 'verified' and 'honor', these look like old days, but Peter and Nathan know better what these courses are

title | edx_course_key | start_date | end_date | courseware_backend
-- | -- | -- | -- | --
Data Analysis for Social Scientists | course-v1:MITx+14.310x+3T2016 | 2016-09-16 15:00 | 2016-12-18 00:00 | edxorg
Foundations of Development Policy: Advanced Development Economics | course-v1:MITx+14.740x+3T2016 | 2016-09-16 04:00 | 2016-12-11 23:59 | edxorg
Foundations of Development Policy: Advanced Development Economics | course-v1:MITx+14.74x+3T2015 | 2015-09-21 15:00 | 2015-12-10 15:00 | edxorg
Microeconomics | course-v1:MITx+14.100x+3T2016 | 2016-09-16 04:00 | 2016-12-15 15:00 | edxorg
The Challenges of Global Poverty | course-v1:MITx+14.73x_1+1T2016 | 2016-02-22 15:00 | 2016-05-15 15:00 | edxorg
The Challenges of Global Poverty | course-v1:MITx+14.73x+3T2016 | 2016-09-16 04:00 | 2016-12-11 15:00 | edxorg
The Challenges of Global Poverty | MITx/14.73x_1/1T2015 | 2015-02-03 15:00 | 2015-05-03 04:00 | edxorg
The Challenges of Global Poverty | MITx/14_73x/1T2014 | 2014-02-04 15:00 | 2014-05-11 15:00 | edxorg

![image](https://user-images.githubusercontent.com/3138890/187469886-70508078-4a15-49c9-8dd3-68abf47c879e.png)

**Comment by pdpinch** [comment]
@rachellougee can you exclude people who have not passed the course from these counts? I think there's a boolean on the final grade model that you could use. 

I think that will give us a better picture of how many people in group 2 are likely to want to pay for an exam.

**Comment by rachellougee** [comment]
@pdpinch I updated my last comment. These numbers are only for people who passed the course but not taken the exam

**Comment by rachellougee** [comment]
There are slack conversations related to enrollment and grade. I will post it here for reference.

>  I believe what we wanted to do was only bring in enrollments and grades for learners who had taken an exam, does that sound right? Meaning:
If a learner has taken at least one exam, we'll bring over course run grades weighted w/ the best exam grade
If they haven't taken an exam:
If they've paid for the course, the course team will manually import their best legacy grade from MicroMasters into a future course run and the learner will use a coupon to "purchase" that course again.
If they've never paid, nothing to do here, they'll need to retake the course and pay on MITx Online to earn credit going forward.

@pdpinch Per discussion with Nathan yesterday, we want to make sure the migrated enrollments have a matching grade. If we are only bringing over grades in group 1, we would want to do the same thing for enrollment. your thought?

> Learners that have taken at least one course run and one exam
