### ISSUE TITLE
MM Data Migration: Transform user data into the form expected by MITx Online

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#660]
Summary
---
We have several tables that are related to user/account data that we want to bring over. The goal is that we transform the source data from MicroMasters into the same format as in MITx Online so that we can simply import that data once we're ready.

We'll be using Airbyte + dbt to perform these transformations, this is probably helpful documentation: https://docs.airbyte.com/operator-guides/transformation-and-normalization/transformations-with-sql

- `User`
  - MITx Online Equivalent: `User`
  - Notes:
    - MicroMasters uses the built in django user model but MITx Online defines a custom one. There are some fields that don't exist in MITx Online (e.g. `first_name` and `last_name`) and there are some new fields that exist and are required (e.g. `name`).
    - The username that we use should *not* be the MM one but instead it should be the `uid` in the social auth table associated with the `mitxonline` provider. If a user doesn't have a social auth record for `mitxonline` we should skip that record (and accordingly any other data like grades, enrollments, etc). Later we'll look into adding a mapping table to bring over other users after the transition to MITx Online as the needs arise.
- `Profile`
  - MITx Online Equivalent: `LegalAddress`
  - Notes:
    - We have a very small amount of this data represented in MITx Online, so we'll just bring over what's there for now

#### Out of Scope
- Importing any of this data into MITx Online

**Comment by rachellougee** [comment]
For the custom transformation step, here are the raw SQLs to transform users table from MicroMaster into the same format as MITxOnline

- User

```
SELECT 
au.id,
social.uid AS username, 
au.email,
concat(profile.first_name, profile.last_name) AS name,
au.is_staff,
au.is_active,
au.password,
au.last_login,
au.is_superuser,
profile.date_joined_micromasters as created_on,
profile.updated_on
FROM auth_user as au
JOIN social_auth_usersocialauth AS social ON social.user_id=au.id
JOIN profiles_profile AS profile on au.id = profile.user_id
WHERE social.provider = 'mitxonline'; 
```

- Profile (This transformation seems straightforward unless I am missing something?
```
SELECT 
id, 
user_id,
first_name,
last_name,
country, 
date_joined_micromasters as created_on, 
updated_on  
FROM profiles_profile;
```

I will continue looking into the integration with dbt for the custom transformation

**Comment by rachellougee** [comment]
Per chat with Nathen, we will not use AirByte + dbt to transform the user data for now. It will be later if we have more time. Closing it
