### ISSUE TITLE
Flexible Pricing: Add additional data to Approve dialog and to request table

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#664]
As a course team member, I'd like to be able to see for what program or course a learner has applied for flexible pricing, and to be able to see (and optionally override) the tier that the learner has been placed in.

#### Designs and Mockups

The data should be added in two places:
* _In the list view:_ 
   * Add a column to the table that displays the current tier/discount. This should be read-only. In the MicroMasters dashboard, this is after Date Calculated: 
![image](https://user-images.githubusercontent.com/945611/177611022-5af522ea-f246-4fd8-8ef0-eaf7513e2a76.png)
   * Add a column to the table that displays the courseware object associated with the request (this will be either a course or a program). I think this should go before the Income column but ultimately it should just make sense. 
* _In the status change dialog:_
   * Add an item with the tier data for the courseware object. This will require a new API; we don't expose the tier data in any way right now. If the status of the request will be Approved, this should be a dropdown that is changeable; otherwise, it should be static. I think this should go above the Justification field (but again am open to suggestions here): 
![image](https://user-images.githubusercontent.com/945611/177611898-97cdde67-e151-41d2-8808-7fa549ff44a6.png)
   * Add a description of the courseware item. This should be at the top of the data elements, I think (around Current Status). 

#### Acceptance Criteria:

- [ ] Can see the request's associated courseware object in the Flexible Pricing dash
- [ ] Can see the learner's assigned tier in the Flexible Pricing dash
- [ ] Can adjust the learner's assigned tier when approving the request
   - [ ] Resulting approval email reflects the selected tier discount
   - [ ] Checkout reflects the selected tier discount
- [ ] Can see the request's associated courseware object in the status change dialog 
- [ ] Can see the learner's assigned tier in the status change dialog, but not change it if Denying or Resetting the request

**Comment by asadali145** [comment]
@jkachel @pdpinch I have a few queries about this ticket. Can you please explain a bit more?

> Add a column to the table that displays the courseware object associated with the request (this will be either a course or a program). I think this should go before the Income column but ultimately it should just make sense.

- I am assuming that we will display the title of Course/Program.

> Add a column to the table that displays the current tier/discount. This should be read-only. In the MicroMasters dashboard, this is after Date Calculated.

- What do we want to display in this case? Adjusted cost (Will be calculated using product price and discount type etc) OR the discount that is applicable like ($100 off or 10% off etc)?

> Add an item with the tier data for the courseware object. This will require a new API; we don't expose the tier data in any way right now. If the status of the request will be Approved, this should be a dropdown that is changeable; otherwise, it should be static. I think this should go above the Justification field (but again am open to suggestions here):

-  What kind of tier data do we want to display here? I assume it's something similar to the above tier/discount.
- Displaying a dropdown when the status is approved. Data for the dropdown? I think we want to display a list of discounts available maybe?

**Comment by pdpinch** [comment]
> Add a column to the table that displays the courseware object associated with the request (this will be either a course or a program). I think this should go before the Income column but ultimately it should just make sense.
>
> I am assuming that we will display the title of Course/Program.

I think the readable id would be better and take less space, i.e. program-v1:MITxT+DEDP or course-v1:MITxT+14.750x

> Add a column to the table that displays the current tier/discount. This should be read-only. In the MicroMasters dashboard, this is after Date Calculated.
> What do we want to display in this case? Adjusted cost (Will be calculated using product price and discount type etc) OR the discount that is applicable like ($100 off or 10% off etc)?

I think adjusted cost will be better. Takes up less space, and is less ambiguous. Currently all our flexible price discounts are fixed price discounts. In the future we will like have a percent off. Displaying the adjust cost makes for a nice consistent presentation. 

> Add an item with the tier data for the courseware object. This will require a new API; we don't expose the tier data in any way right now. If the status of the request will be Approved, this should be a dropdown that is changeable; otherwise, it should be static. I think this should go above the Justification field (but again am open to suggestions here):

> -  What kind of tier data do we want to display here? I assume it's something similar to the above tier/discount.

Again, I think the adjusted cost is most understandable. Take a look at the micromasters implementation for reference: 

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/430126/183080801-f52744cb-e5c1-4916-ad67-351fe6768511.png">

> - Displaying a dropdown when the status is approved. Data for the dropdown? I think we want to display a list of discounts available maybe?

same, a list of available adjusted costs.

**Comment by asadali145** [comment]
That makes sense. Will do it this way. Thanks for the details.

**Comment by asadali145** [comment]
Is there a way to fetch the `CourseRun` || `ProgramRun` associated with a financial assistance request? Currently, `Course/Program` is associated with a financial assistance request. I am assuming that we will be having multiple course runs available at a time, so, user can opt for any of the available course runs. Also, course runs can have different pricing.

As per my understanding:
- We can have multiple course runs at a time for a course.
- Similarily, `Product` is attached to a `Run` object. So, we can have multiple prices maybe for multiple course runs of a single course.
- `FlexiblePrice` and `FlexiblePriceTier` is associated with `Course` || `Program`.
- So, How do we fetch the `CourseRun/Program || Product` using `FlexiblePrice || FlexiblePriceTier || Discount`?

@jkachel Maybe you have a better idea of what I am talking about.
@pdpinch Maybe you can answer as well.

**Comment by pdpinch** [comment]
Instead of displaying the adjusted cost (which requires the price from the product), let's display the discount. The discount will be consistent for all courses in the program.
