### ISSUE TITLE
Flexible Pricing: display personalized price 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#670]
As a user, I'd like to see my personalized price, including financial assistance, in every place where I see a course price. 

In particular, I'd like to see it on the course about page.  

#### Designs and Mockups

<img width="1532" alt="image" src="https://user-images.githubusercontent.com/430126/177823073-df78f574-a167-46d7-a0a8-46994820e033.png">

#### Acceptance Criteria:

- [ ] For logged in users whose financial assistance has been approved, display their personalized price instead of the undiscounted price. 

#### Out of Scope

- we don't want to change the link labelled "personalized pricing" in the screenshot at this time. The link text and its destination are managed in the CMS.

**Comment by collinpreston** [comment]
@pdpinch - on the page shown in the issue description, what should the `Personal pricing` hyperlink direct to?

**Comment by pdpinch** [comment]
That link is specified in the CMS. 

In production ([for example](https://mitxonline.mit.edu/courses/course-v1:MITxT+JPAL102x/)), it links to a FAQ about how personal pricing works. The text and link is set in the CMS -- in this example, at https://mitxonline.mit.edu/cms/pages/11/edit/

On RC, you can see that we've changed the destination of that link to be the form for requesting financial aid.
