### ISSUE TITLE
Flexible Pricing: display (editable) price in admin

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#671]
As a course admin who is reviewing financial assistance requests, I'd like to be able to see, and modify, users' personal prices. 

- I'd like to see them the personal price so I don't have to memorize the income tiers. 
- From time to time, I might need to modify a price for special circumstances

#### Designs and Mockups

No design. It seems like the easiest thing is to add this to the pop-up window when approving a flexible pricing request. 

#### Acceptance Criteria:

- [ ] admin can see user's price before approving a flexible pricing request.
- [ ] admin can change the price when necessary.

**Comment by jkachel** [comment]
@pdpinch I opened https://github.com/mitodl/mitxonline/issues/664 yesterday that covers this as part of it - should that be simplified?
