### ISSUE TITLE
Order History: unauthenticated user can view (empty) order history page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#673]
### Steps to Reproduce

1. Log out. 
2. visit /orders/history/ 

### Expected Behavior

1. User should be redirected to login page, i.e. /signin
2. After successful authentication, user should be returned to /orders/history

### Actual Behavior

- user can view an order history page, but with 0 orders

<img width="1115" alt="Screen Shot 2022-07-06 at 3 21 12 PM" src="https://github.mit.edu/storage/user/5/files/5572da00-fd3f-11ec-82b1-26b080b336bc">

### Related Issues

- In the future, we would like to be able to support customer support team members being able to view learner's order history

**Comment by collinpreston** [comment]
@pdpinch can this issue be closed since https://github.com/mitodl/mitxonline/pull/681 was merged?

**Comment by jkachel** [comment]
Closing this; the cart routes are PrivateRoutes as of #681 so this'll redirect to the login screen as expected.
