### ISSUE TITLE
Flexible Pricing: learners shouldn't be able to enter flexible pricing codes

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#674]
Summary
----

Currently because we use discounts as the abstraction to provide flexible pricing, these discounts have discount codes that are able to be manually entered by a learner. Since these codes show up on the checkout page when a learner gets their flexible pricing applied, they're easily discoverable.

![Image](https://user-images.githubusercontent.com/28598/177838161-27224e26-ecf1-4b50-8e46-e18b0eed653a.png)

#### Acceptance Criteria

- [ ] I'd suggest adding a boolean field to `Discount` that indicates whether it can be manually applied on the checkout page. Default it to `False` for some added safety.
- [ ] Update the discount APIs to reject discount codes that can't be manually applied
- [ ] Update the frontend to display an appropriate error message

**Comment by pdpinch** [comment]
Instead of adding a flag, could we make the flexible pricing coupon unique per user?
