### ISSUE TITLE
Flexible Pricing: indication on dashboard that flexible pricing is available

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#677]
Summary
---
We should have an indication to the learner that flexible pricing is available for a course on the dashboard. This will probably be associated with the "Get a Certificate" button.

#### Designs

1. "financial assistance?" link on the dashboard: https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468431706/preview?scrollOffset=0
2. "Need financial assistance?" link on the upgrade card on the about page: https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/462502739/preview
3. "Need financial assistance?" link on the upgrade modal: https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/455477372/preview
4. "Need financial assistance?" link on the checkout page

#### Acceptance Criteria

- [ ] The link should only be available when the course in question offers flexible pricing / financial assistance
- [ ] The link should not display if the learner has already been approved for financial assistance
- [ ] The link should go to the appropriate flexible pricing form for the current course

**Comment by pdpinch** [comment]
I'm unblocking this because we have designs now.
