### ISSUE TITLE
Flexible Pricing: flexible pricing requests should be applied to programs instead of courses

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#678]
Summary
---

Right now flexible pricing is using the course that the learner has linked from, we'd rather this be program-based so that learners don't have to apply to every course because this would be burdensome and confusing.

We also need a way to apply program-level discounts to the courses. This issue is blocked until we determine how to do that.

#### Acceptance Criteria

- [ ] The flexible pricing page should probably be hosted under the program instead
- [ ] The flexible pricing link on the course page should still link to this page
- [ ] When the learner submits their request the program should be associated with that program
- [ ] When the request is approved the learner should get a discount on the program

**Comment by pdpinch** [comment]
Is there a particular issue blocking this?

**Comment by jkachel** [comment]
I don't think there's an issue that's blocking this (at this point in time) but there's some thought that needs to go into how this will be implemented. This is my thinking on the subject:

The link between a flexible pricing request (a `FlexiblePricingFormSubmission`) and the courseware object that it is associated to is weak. There's not an FK in there for this; it just has a helper function to figure out what the parent page is and grabs the courseware object it is associated with. (This is why the flexible pricing form itself needs to be a child page of the course - it's how the `FlexiblePrice` model figures out what courseware object it needs to be associated with.) That's only courses at the moment as we don't have a way to add a page for a program into the CMS. Expanding that to work with programs can be done in one of two ways:
1. We can add program pages into the CMS (I'd think in the same way the course pages are done up now). Then, the Flexible Pricing request forms can be updated slightly to allow having a program page as a parent. Any Flexible Pricing request form that's created underneath a program's page, then, would be able to grab the program as the courseware object for submitted requests. 
2. We can add a dropdown to set the courseware object for the Flexible Pricing request forms, similar to how the courses are set for course pages. Then, the form itself would be explicitly linked to the courseware object whether or not it's a program or a course. 
Doing both here is also a viable option - I'm thinking we need program pages in general anyway so the question is really whether or not we also do the second one. 

Flexible pricing tiers and products can be established now for programs (or program runs, in the case of products - we only sell runs). So, they're already set up right. We would need to amend the code that applies flexible pricing discounts to consider a couple new scenarios:
1. If the product being purchased is a program run, then it should look for tiers that are associated with the underlying program. (Right now it's hard-coded to look for courses.) 
2. If the product being purchased is a course run, it should also look for a tier that matches on the course's program membership. This would handle the case where the learner's applied for flexible pricing for Program X on Jan 1; then Course R is added to the program Feb 3; and the learner then needs to go buy access to the course on Mar 5 - the flexible pricing that was set up for the course should then also automatically apply even though there's nothing specifically linked to Course R. 

There is separate code that looks for and applies the flexible pricing discount depending on whether or not the learner has an approved flexible pricing request for the courseware object, so this would all go in there. I think this would be pretty straightforward to do. 

The link is probably the easiest part of this. It's just a link in the course page so it can link to whatever flexible pricing request form is required, which can definitely be the one for the program once those can be made. (It was going to Zendesk.) There's nothing automatic about this - I didn't want to programmatically make a determination about which form might or might not be valid for the course and there's nothing limiting you from having more than one FP request form for a course (so you can do drafts or different forms for special purposes or marketing reasons, etc.).

**Comment by pdpinch** [comment]
Is this still blocked?
