### ISSUE TITLE
Ecommerce: ability to limit discounts to only apply to specific products

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#687]
Summary
---
This seems to have been missed somewhere, but as we have it in our other products we will very likely need it for MITx Online as well. Right now discounts work globally on all products. This is a good option to have but it's more likely that discounts will be applicable for a handful of courses.

#### Acceptance Criteria

- [ ] Ability to specify zero or more products as applicable for the discount
- [ ] If at least one product is specified, limit usage of that discount based on that (in APIs, UI, backend code, etc)

**Comment by pdpinch** [comment]
@jkachel @rhysyngsun can this be closed, now that #708 is merged?
