### ISSUE TITLE
Certificates: Investigate updating MITx Online data based on webhooks from OpenedX

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#690]
Summary
---

For certificates we need to be able to generate certificates automatically within a short time of a learner completing a course and exam. Current we use a polling mechanism and a blocking call when the learner loads the dashboard. The former causes a delay and the latter isn't great for performance and requires a learner to actually visit the dashboard.

To accomplish this, we need to investigate utilizing OpenedX's hooks infrastructure to send webhooks based on certain events  to be able to reflect updates on the MITx Online side.

#### References

[OEP-50: Hooks extension framework](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0050-hooks-extension-framework.html)
[`openedx-events` Github](https://github.com/openedx/openedx-events)
[`openedx-events` Docs](https://openedx-events.readthedocs.io/en/latest/getting_started.html)

#### Tasks

Investigates the OpenedX infrastructure above and determine if it is the kind of mechanism we're looking for here:

- Does it provide an ability to make webhook calls (either natively or via additional code)?
- Does it provide hooks for the events we need (course grade updates, course completion)? 
- Would this require our own plugin?
- If none of the above is viable, propose an alternative that you feel would work for our requirements

**Comment by arslanashraf7** [comment]
Posting initial update:

While looking at a lot of documentation in various different places there are a things that i can mention regarding the ticket tasks:

The hooks from Open edX are provided and can be used in two ways,
1- [Filters](https://github.com/openedx/edx-platform/blob/master/docs/guides/hooks/filters.rst), The package implementation can be seen [here](https://github.com/openedx/openedx-filters). The filters generally allow us to manipulate/update some data through a pipeline before it's passed to the actual functionality.
2- [Events](https://github.com/openedx/edx-platform/blob/master/docs/guides/hooks/events.rst), The package implementation can be seen [here](https://github.com/openedx/openedx-events). Events are just a piece of information to whoever is listening to them and don't allow us to update the data before it gets used in the functionality itself. 


>Does it provide hooks for the events we need (course grade updates, course completion)?

- The provided list of filters is [here](https://github.com/openedx/edx-platform/blob/master/docs/guides/hooks/filters.rst#index-of-filters)
- The provided list of events is [here](https://github.com/openedx/edx-platform/blob/master/docs/guides/hooks/events.rst#index-of-events)

As seen in the above lists, Both filters and events don't provide the specific hooks that we need but there are some regarding certificates that we might dig around more for our use case.


>Does it provide an ability to make webhook calls (either natively or via additional code)?
> Would this require our own plugin?

Per my initial research, we will need to create a plugin for whatever we use (Events or Filters).

An implementation reference for `Filters` can be seen [here](https://github.com/openedx/openedx-filters/blob/main/docs/decisions/0002-hooks-filter-config-location.rst) and it looks like we will need to inject a custom filter function through a plugin in settings.

An implementation detail for `Events` can be seen [here](https://github.com/openedx/openedx-events/blob/main/docs/decisions/0001-purpose-of-this-repo.rst) and for this we would need a plugin and register to the signals/events the platform would emit.

The above is kind of initial details but I just wanted to share anyway. It's possible that these might change with some more research.

FYI, @rhysyngsun @pdpinch

**Comment by pdpinch** [comment]
Can use the filter CertificateCreationRequested <https://github.com/openedx/openedx-filters/blob/main/openedx_filters/learning/filters.py#L142> to send a webhook to mitxonline which can take care of actually creating the certificate? 

> The provided list of filters is here <https://github.com/openedx/edx-platform/blob/master/docs/guides/hooks/filters.rst#index-of-filters>

**Comment by pdpinch** [comment]
> Q: Currently, for someone who completes a course do we generate two certificates (one in edX and the other one in MicroMasters)?

In mitxonline, we only need to generate a certificate in mitxonline. This is similar to xPRO. 

> We will also need an API in MITxOnline that creates a certificate for a user.

Yes. Can you open an issue for that?

**Comment by rhysyngsun** [comment]
So I discovered that openedx has _another_ event dispatch mechanism: https://github.com/openedx/event-tracking

It's mean to route events to external systems so this actually seems like pretty much exactly what we'd want. We'd be able to implement a backend for this that does what we want. We'd want to filter to `edx.course.grade.now_passed` and there are others in `grades/events.py` we'll probably want to use eventually.

I'd also suggest that instead on making a certificates-specific API that we actually create a webhook endpoint and send well-structured events. There may be other things besides generating certificates that we want to do when a learner passes a course in the future so it would be good to keep this generalized. I'm thinking of a payload like this:

```
{
  "event_type": "edx.course.grade.now_passed",
  "event_id": "<event_transaction_id>",
  "event_created: <timestamp>,
  "data": {
    // relevant data
  }
}
```

And we'd have the eventtracker backend send these to a webhook endpoint like `/api/v0/openedx-webhooks/` which would route according to `event_type` and execute the relevant code (e.g. generate a certificate when a learner passes).

What do we think of this?
