### ISSUE TITLE
MM Data Migration: Provision MM data into Airbyte

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#695]
We need MM data provisioned into Airbyte so that we can set up pipelines to bring that data over to MITx Online.

- [ ] Provision with RC data
- [ ] Provision with Production data (this can be done at a later date)

**Comment by pdpinch** [comment]
@rhysyngsun should we close this?

**Comment by rhysyngsun** [comment]
If it's serving as a distraction sure, but I think it's something we'll want to do eventually.

**Comment by pdpinch** [comment]
If we ever get to this, it will part of the data platform project, and the steps required will be laid out in much more detail.
