### ISSUE TITLE
Ensure that footer renders at the bottom of page

### ISSUE THREAD

**Issue by gsidebo** [mitodl/mitxonline#70]
When there is little content in the body of the page, the footer is rendered directly beneath that content and leaves a significant space underneath. The footer should render at the bottom of the page when there is not enough content to fill the screen, but should not be pinned to the bottom regardless of scroll position

![ss 2021-08-06 at 16 51 35 ](https://user-images.githubusercontent.com/14932219/128574554-b49b97b9-6747-47af-9e8e-ed7bff84da71.png)

**Comment by arslanashraf7** [comment]
@gsidebo I'm assigning it to you since you have associated a PR that fixes this issue.
