### ISSUE TITLE
Story: legacy MM users course enrollment on dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#701]
As a returning DEDP MicroMasters learner, I can see my past edx.org course enrollment on my dashboard. 

For example, on RC my user has enrollments in 14.100x+2T2017. I expect to see that enrollment on my dashboard on mitxonline as well. 

#### Designs and Mockups

no change

#### requires the following MM data:

- [ ] Course runs
- [ ] Course run enrollments

| MicroMasters (Model/Table) | MITx Online (Model/Table) |
| --- | --- |
| `CourseRun` / `courses_courserun` | `CourseRun` / `courses_courserun` 
| `CachedEnrollment` / `dashboard_cachedenrollment` | `CourseRunEnrollment` / `courses_courserunenrollment`

These should be separate SQl queries and will need to be run in the sequence above. 

We'll join on those social auth `uid as username` for determining the user.

- `CourseRun`: the `edx_course_key` / `courseware_id`
- `CachedEnrollment`: the combination of `user_id` and `run_id`

Note: the `Course` data model is going to be manually generated on our systems (they should already be in place). These will get mapped.

#### Out of Scope

- grades and certificates are not required for this issue

**Comment by rachellougee** [comment]
@rhysyngsun @pdpinch I am not sure the best place to put up the queries for review, but I've saved it on BI https://bi.odl.mit.edu/queries/1161/source#2017 
I tested the courseRun/Enrollment migration from MicroMaster RC to my local MITxOnline postgres DB using postgres_fdw https://www.postgresql.org/docs/current/postgres-fdw.html per suggested.
I verified Peter's enrollments and can see 14.100x+2T2017 on my test
```----Peter's enrollment On MITxOnline after migration from MicroMaster
SELECT run.courseware_id
FROM public.courses_courserunenrollment as enroll
JOIN public.users_user AS users on enroll.user_id = users.id
JOIN public.courses_courserun as run ON enroll.run_id = run.id 
where users.username ='pdpinch';

        courseware_id          
--------------------------------
 course-v1:MITx+14.100x+2T2017
 course-v1:MITx+14.310x+3T2021
 MITx/14.73x_1/1T2015
 course-v1:MITx+JPAL102x+3T2021
 course-v1:MITx+14.740x+2T2022
 course-v1:MITx+14.100x+1T2022
(6 rows)
```
if you want to take a look at it, that'd be great. The queries probably need some tweaks. Nathan is building the django command to run these queries. we should be able to test it once its all set
