### ISSUE TITLE
Story: legacy DEDP financial assistance state on mitxonline 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#702]
As a returning DEDP learner, I expect that my financial assistance price and status is the same on mitxonline that it was on micromasters.  

for example, on MM RC, my personal price is $250 per course. It should be the same on mitxonline RC.

Configuration of financial assistance should be the same in both applications, i.e. the number and value of tiers.

#### Designs and Mockups

no change

#### required MM data:

- [ ] financial aid

**Comment by rachellougee** [comment]
@pdpinch @rhysyngsun I have a couple of questions:

- Do we want to bring in only approved/pre-approved financial aid records or all of them? 
> https://micromasters-rc.odl.mit.edu/admin/financialaid/financialaid/235/change/

- Where should these imported financial aid records be displayed on the frontend UI? 
> In admin, I assume it will be here https://rc.mitxonline.mit.edu/admin/flexiblepricing/flexibleprice/ as DEDP 'program' flexible price

**Comment by pdpinch** [comment]
Here are my thoughts on what statuses to import: 

Financial Aid status on MM | Flexible price status on MO | drop or import? 
-- | -- | -- 
approved | approved | import
auto-approved | auto-approved | import 
created | created | import 
docs-sent |  pending-manual-approval | import 
pending-docs |  pending-manual-approval | import 
pending-manual-approval | pending-manual-approval | import 
reset | reset | drop 
skipped |  | drop 
  | denied | n/a

I'll follow up with a proposal about tier mapping.

**Comment by pdpinch** [comment]
Rachel and I discussed tier mapping a bit on Zoom. Coming from Micromasters, we only want to bring in `tier` and `tier_program` where the program is DEDP and`tier_program.current = true`.

**Comment by rachellougee** [comment]
@jkachel @rhysyngsun I am working on the migration detail from MicroMaster to MITxOnline. I've discussed with Peter a bit about tier mapping, but would like to check in with two of you on two open questions I have:

1. For CMS submission on MITxOnline FlexiblePrice, should we leave it blank when we migrate MM Financial Aid https://micromasters-rc.odl.mit.edu/admin/financialaid/financialaid/235/change/ to flexible price on MITxOnline? or create each submission on MITxOnline, which seems complicated?  It's not a required field
2.  We will have a mapping table on MITxOnline to handle the primary key mapping from the MicoMaster Financial Aid tier program to MITxOnline Flexible price tie. Here are the **current** tier program mapping based on my understanding, please let me know if this is correct. if not, what's the correct mapping?  Should we create the 2021 tier program on MITxOnline first?

Tier Program | MicroMaster (current) | MITxOnline (current)
-- | -- | --
Tier 1 | https://micromasters-rc.odl.mit.edu/admin/financialaid/tierprogram/51/change/ (discount: 650) | https://rc.mitxonline.mit.edu/admin/flexiblepricing/flexiblepricetier/38/change/ (discount:250)
Tier 2 | https://micromasters-rc.odl.mit.edu/admin/financialaid/tierprogram/52/change/ (discount: 650) | https://rc.mitxonline.mit.edu/admin/flexiblepricing/flexiblepricetier/39/change/ (discount:350)
Tier 3 | https://micromasters-rc.odl.mit.edu/admin/financialaid/tierprogram/53/change/ (discount: 500) | https://rc.mitxonline.mit.edu/admin/flexiblepricing/flexiblepricetier/40/change/ (discount: 500)
Tier 4 | https://micromasters-rc.odl.mit.edu/admin/financialaid/tierprogram/54/change/ (discount:0) | https://rc.mitxonline.mit.edu/admin/flexiblepricing/flexiblepricetier/41/change/ (discount: 0)

**Comment by jkachel** [comment]
The tier mappings look OK to me. 

The CMS submission can be left blank in this case. It's more of a nice to have; all the pertinent data is captured in the FlexiblePrice object. In this case, leaving it blank might be useful as a way to identify requests that have been migrated, since they won't have form submissions.

**Comment by rhysyngsun** [comment]
Agree w/ James.

**Comment by pdpinch** [comment]
Just to clarify something in the tier mapping table. In MicroMasters, the discount is "dollars off". In MITx Online we're using "fixed price". So a $1000 starting price, with $750 off is the same as a fixed price of $250.

**Comment by rachellougee** [comment]
@pdpinch Thanks. Glad you pointed it out as I was a little confused about the discount field on both ends. In that case, the discount matched on RC

**Comment by rachellougee** [comment]
@rhysyngsun @jkachel @pdpinch Sorry one more thing, t looks like there isn't a unique key on FlexiblePrice model, so the same record https://micromasters-rc.odl.mit.edu/admin/financialaid/financialaid/235/change/ can be imported to MITxOnline multiple times. Should we add a unique key to FlexiblePrice? user + status+ tier or something?
I put up PR https://github.com/mitodl/mitxonline/pull/801 and notice this while testing it.

**Comment by jkachel** [comment]
I think there will be more work to add the unique key constraint. We'll also have to factor in some changes for storing submissions in the system. If you're allowed to submit the form (i.e. your status isn't Approved, Auto-Approved, or Denied), it currently puts in a new record regardless of whether or not there's an existing one. So, we'll at least also have to update the submission code to use a `get_or_create` and/or update the `FlexiblePrice` model to use the reversion library. That feels like it should be a separate issue to me. 

As far as a unique constraint goes, the core data elements are user and courseware object, I think, so those should be the fields we unique.

**Comment by rhysyngsun** [comment]
Might be good to pull in the reversion library for this, since having a history has potential usefulness outside of this.
