### ISSUE TITLE
Story: legacy MM program enrollments on dashboard 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#703]
As a returning DEDP learner, I can see my DEDP program enrollment on my dashboard.

For example, on MM RC, I see DEDP in the program drop-down at the top right of my dashboard. On mitxonline, I expect to see a card for the DEDP program on my dashboard.

#### required MM data:

- [ ] programs
- [ ] program enrollments

#### Related Issues

- [x] #704

**Comment by pdpinch** [comment]
@rhysyngsun @rachellougee do you think this can be closed?

**Comment by rhysyngsun** [comment]
There was still a use case around wanting the program enrollments from micromasters at least for reporting purposes.

**Comment by rachellougee** [comment]
@pdpinch @rhysyngsun Just to confirm if we only need to bring in DEDP program enrollments from MicroMasters? The description seems to indicate only DEDP, but the title didn't mention DEDP

**Comment by rhysyngsun** [comment]
@rachellougee yes, only DEDP. For now, just have it be "audit" because no one can pay for a program at the moment anyway

**Comment by rachellougee** [comment]
Just run it on production, and the imported number is a little less than I estimated. I think it's due to some learner's grades are not on mitxonline
```
Running: 009_import_course_certificate.sql

Rows added/updated: 4952
