### ISSUE TITLE
Story: display programs on the dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#704]
As a learner, I would like to see my dashboard organized into programs, to make it easier to see what I've completed. 

#### Designs and Mockups

Programs on the dashboard: https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468431706/preview?scrollOffset=0
Program drawer: https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468431707/preview?scrollOffset=0

#### Acceptance Criteria:

- [ ] If I have enrolled in _any_ course in a program, assume I am enrolled in the program as well. 
- [ ] In the program drawer, only display courses I am enrolled in (the mitxonline dashboard only displays what I am taking / have taken. Unlike the MM dashboard, it does not tell me what I need to take in the future. 

#### Related Issues:

- https://github.com/mitodl/mitxonline/issues/703

**Comment by jkachel** [comment]
Opened #725 for the dashboard work that needs to be done. I had a question though - where should the Get Certificate button be displayed for program enrollments? Can we just shoehorn that into the course's card in the drawer (for courses that the learner hasn't paid for yet)?
