### ISSUE TITLE
Story: legacy DEDP learners' program certificates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#706]
As a returning DEDP learner who earned a program certificate on micromasters.mit.edu, I can link to my program certificate on my mitxonline dashboard 

Program certificates will be hosted on mitxonline going forward, so this has a dependency on the program certificate templates and models. 

#### Designs and Mockups

TBD, but should be very similar to #691 

#### required MM fields

- [ ] Micromasters program certificates

#### Related issues

- program certificate templates and models
- #704

**Comment by pdpinch** [comment]
This is blocked until @pdpinch creates a template for the DEDP program certificate

**Comment by pdpinch** [comment]
Ok, I've created some DEDP program certificate versions in production. When migrated, the legacy program certificates should get the oldest version (includes Sanjay Sarma's signature).

**Comment by rachellougee** [comment]
Ran it on production
```
--------------------
Rows added/updated: 479
====================
Successfully imported MicroMasters data
```
