### ISSUE TITLE
Flexible pricing: update income form

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#709]
#### Designs and Mockups

See [https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468433645](https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468433645/preview)

#### Acceptance Criteria:

- [ ] take a look at the design and let us know if the form responses being outside the card will be a problem
- [ ] The checkbox is a required field, but doesn't require storing any data.

**Comment by asadali145** [comment]
@pdpinch Can you please provide links for the buttons in these designs? Also, the second design is related to flexible pricing denied state. Right? Or Is it related to processing?
https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468433646/preview
https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468433647/preview

**Comment by pdpinch** [comment]
https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468433646/preview

I left a note on the design. 

> To keep this simple, let's link this button to the home/catalog page for now. When we have a better place to link to, we will update it.

https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468433647/preview 

This screen is the "Application processing text" 

I think you should remove the two buttons for now. We will handle them in the CMS. 

We may do a follow-up PR to make the buttons function as intended.
