### ISSUE TITLE
Make dashboard accessible to authenticated Users only

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/mitxonline#72]
### Steps to Reproduce
- Setup MITx Online
- Make sure that you are Logged Out.
- Visit `/dashboard`, The dashboard page will be opened

### Expected Behavior
- Accessing the dashboard without authentication should redirect the user to the /signin form with an appropriate next parameter so that once they sign in successfully they are directed to the dashboard.

### Actual Behavior
- Visiting  `/dashboard` opens the dashboard page.

### Screenshot or Screencast
<img width="1439" alt="Screenshot 2021-08-09 at 5 13 27 PM" src="https://user-images.githubusercontent.com/34372316/128704372-d6984d92-9c22-44ed-9e85-ab05d97dafe6.png">

**Comment by pdpinch** [comment]
Accessing the dashboard without authentication should redirect the user to the /signin form with an appropriate next parameter so that once they sign in successfully they are directed to the dashboard.

**Comment by arslanashraf7** [comment]
_> Accessing the dashboard without authentication should redirect the user to the /signin form with an appropriate next parameter so that once they sign in successfully they are directed to the dashboard.

Thanks, Update the ticket description with this comment.

**Comment by gsidebo** [comment]
Closed by #77
