### ISSUE TITLE
Programs: update dashboard display for programs

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#725]
As a learner, I would like to see the programs I've enrolled in on the dashboard (whether they are direct enrollments in the program, or enrollments in a course that belongs to a program). 

~~This is blocked since the API needs to be amended first to return program enrollments properly - see~~ #719 . - It made more sense to pull the program enrollments out into a separate API, so the dashboard code will need to call that API instead.

#### Designs and Mockups

Programs on the dashboard: https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468431706/preview?scrollOffset=0
Program drawer: https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468431707/preview?scrollOffset=0

#### Acceptance Criteria:

- [ ] Use the updated API to display program enrollments alongside course enrollments.
- [ ] Courses that belong to a program should be displayed in the drawer. 
- [ ] Other courses in the program should not be displayed in the drawer - just the things that the learner is enrolled in.
- [ ] Programs should include tags as appropriate (see mockups). 
- [ ] Standalone courses should display as they were.

#### Related Issues

#704

**Comment by jkachel** [comment]
Two minor questions (probably for @pdpinch): 

1. Where should the program image come from? My plan currently is to use the image from the first course - is there somewhere else this should be set? 
2. What does the hamburger menu do? For courses, this gives you a menu to adjust email settings and unenroll from the course. I can work those out so that they make changes to all the associated course enrollments for the program (which may be a bit dangerous for the unenroll option). Alternatively, we can skip that menu, or have it pull up the course drawer.

**Comment by pdpinch** [comment]
> 1. Where should the program image come from? My plan currently is to use the image from the first course - is there somewhere else this should be set?

These change very seldom. If it's not too much trouble, I would pull it from the CMS, like we do in xPRO. 

> What does the hamburger menu do? For courses, this gives you a menu to adjust email settings and unenroll from the course. I can work those out so that they make changes to all the associated course enrollments for the program (which may be a bit dangerous for the unenroll option). Alternatively, we can skip that menu, or have it pull up the course drawer.

I think it should pull up the drawer.
