### ISSUE TITLE
flexible pricing: clean-up email template

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#727]
#### Designs and Mockups

MITx Online email:

![image](https://user-images.githubusercontent.com/430126/180305884-3128d6da-84f5-4bf0-9d17-c7994a566e71.png)

MicroMasters email, for reference:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/430126/180305956-9434394c-fb26-43ba-89fc-f1a5d6cdf985.png">

#### Acceptance Criteria:

- [ ] fix up the styling issues above
- [ ] move the logo to the top of the email, like it is in other email templates
- [ ] update the text (including line breaks): 

> Dear Peter, 
> 
> As requested, we have reset your request for financial assistance. Please visit the MITx Online site and re-submit your annual income information. 
> 
> Thank you, 
> The Data, Economics, and Development Policy team

- [ ] in the signature, use the program name when appropriate
- [ ] Can we provide a reliable URL to the form they need to update their income?

**Comment by collinpreston** [comment]
@pdpinch or @jkachel, what are the steps to reproduce the email shown above?  I tried going to `/admin/flexiblepricing/flexiblepricingrequestsubmission/add/` but the form on that page does not allow data entry.

**Comment by collinpreston** [comment]
@pdpinch , I don't have the Apple Mail app configured, but does this screenshot look good to you?
![Screen Shot 2022-07-22 at 3 44 29 PM](https://user-images.githubusercontent.com/8311573/180516482-28ce08ff-630a-446e-a3e2-50f3f00295d3.png)

**Comment by pdpinch** [comment]
One thing I forgot to call out: the logo should be at the top, not below the message. It should look similar to the enrollment email:

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/430126/180752771-bc59e174-c6b7-4753-84fb-ed0e15099897.png">

(screenshot from gmail)
