### ISSUE TITLE
Set support email address on RC server

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#729]
### Steps to Reproduce

1. try to enroll in 14.7450x, which apparently isn't currently open

### Expected Behavior

- You should get an error banner, with the text:
> Something went wrong with your enrollment. Please contact support at mitxonline-support@mit.edu 

### Actual Behavior

- banner says to contact `support@localhost`

### Screenshot or Screencast

<img width="759" alt="image" src="https://user-images.githubusercontent.com/430126/180307698-71cb9bfb-6876-4509-9164-66cbb6855677.png">

**Comment by pdpinch** [comment]
Note, I've fixed the issue with enrolling in 14.750x, so it may no longer be possible to reproduce this error with that course.

**Comment by pdpinch** [comment]
This will need a PR in saltops

**Comment by pdpinch** [comment]
It appears this address is already set, in https://github.com/mitodl/salt-ops/blob/a1f2b450472f88682bd0637a25a67bf5217b5f96/pillar/heroku/mitxonline.sls#L58

Maybe we need to check the error message to make sure it's pulling in the correct setting.

**Comment by asadali145** [comment]
Everything seems ok. Just got access to Heroku. Will look into it now.

**Comment by asadali145** [comment]
MITX_ONLINE_SUPPORT_EMAIL is not set for RC. Checked in Heroku and in the server as well. Fixed the config https://github.com/mitodl/salt-ops/pull/1531.

**Comment by asadali145** [comment]
I am not able to reproduce the error on RC. But for testing, I have verified the support email that we use in the above message and it seems to be working fine now. I have verified it in the browser console and in the server as well.
