### ISSUE TITLE
Add Google Tag support

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#73]
As a member of the marketing team, I'd like to manage ad campaign tracking via Google Tag Manager -- similar to what we did on xPRO. 

#### Acceptance Criteria:

- [x] Add boilerplate support for GTM
- [x] Create GTM and GA accounts for CI/RC
- [x] Add GTM key for CI and RC to salt-ops
- [x] Create GTM and GA accounts for production
- [x] Add GTM key for Production to salt-ops
 
#### Out of Scope

- Since there is no ecommerce yet on this site, we can't track any ecommerce events.

**Comment by arslanashraf7** [comment]
@pdpinch Can you share the details of the Test `Google Tag Manager/Google Analytics` that has been set up?

This might include:
- GTM Tracking ID (Could be taken from the [GTM project console](https://tagmanager.google.com/), it would be something like `GTM-XXXXXXX`)
- Google Analytics ID (Could be taken from the created property on [Analytics Console](https://analytics.google.com/)
- And developer access so that I could see the logged events

**Comment by asadiqbal08** [comment]
LGTM 👍 , 

Not related to this PR perhaps but I noticed one thing, we have defined `gtm_tracking_id` and `ga_tracking_id` in `AppContextSerializer` but we do not have any endpoint or usability in this project. maybe in the later requirements.

```
class AppContextSerializer(serializers.Serializer):
    """Serializer for the application context"""

    public_path = serializers.SerializerMethodField()
    gtm_tracking_id = serializers.SerializerMethodField()
    ga_tracking_id = serializers.SerializerMethodField()

```

**Comment by pdpinch** [comment]
Updated the description with some more acceptance criteria

**Comment by arslanashraf7** [comment]
@pdpinch 

>Add GTM key for CI and RC to salt-ops

Regarding the above, I don't think we have CI yet but for RC keys addition on salt-ops I did create & merge a PR recently https://github.com/mitodl/salt-ops/pull/1458

**Comment by arslanashraf7** [comment]
@pdpinch FYI, I've checked some boxes but definitely let me know when this ticket can be closed.

**Comment by arslanashraf7** [comment]
@pdpinch I believe that acceptance criteria have been met and I'm closing this ticket, Obviously, reopen if needed.
