### ISSUE TITLE
Periodically update enrollments from open edX 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#75]
As a MicroMasters learner, I want my mitxonline dashboard to reflect any course enrollments I've made through the MicroMasters site. This is complicated by the fact that enrollments initiated from the MM site will be created in open edX directly.

To avoid any delays in loading the learner dashboard, we can periodically update the enrollment state for any courses that are currently open for enrollment. 

### Acceptance Criteria:

- [ ] On a regular basis, query open edX for a list of enrolled users in each course that is open for enrollment
- [ ] Put this feature behind a flag

Related issues

- #74

**Comment by gsidebo** [comment]
We may want to disable the sync-on-dashboard-load behavior when we finally implement this so our users avoid performance issues when visiting the dashboard page. We could check New Relic to see what average loading times look like and decide from there. That behavior is feature flagged. Here's the original issue: https://github.com/mitodl/mitxonline/issues/74
