### ISSUE TITLE
Ecommerce: upgrading an enrollment does not change the enrollment mode

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#762]
### Steps to Reproduce

User doesn't appear to be a factor here, so testing this with a newly created account is recommended.

1. Enroll into a course that has a certificate without upgrading to the certificate level track. The enrollment should succeed.
2. Load your dashboard. The course should appear on the dashboard, and the Get Certificate button should be displayed.
3. Click the Get Certificate button. You should be redirect to the cart. 
4. Complete the purchase. You should receive a receipt via email and should be redirected to the MITx Online dashboard with a success message. Specifically, the message should note that you have enrolled in the paid version of the course. 
5. Observe the dashboard. The entry for the course should say "Enrolled in certificate course" and the Get Certificate button should not be visible.

### Expected Behavior

In step 5, the course should be tagged as enrolled in a certificate course and the Get Certificate button should not be visible.

### Actual Behavior

The upgrade does not happen, so the tag used is the "Enrolled in free course" tag and the Get Certificate button is still present.

### Notes

The transaction details should be recorded successfully. There will be a Fulfilled Order record, and a Transaction record will exist as well. Purchasing the certificate level course for a course with no enrollment does work.

**Comment by pdpinch** [comment]
#763 is merged and tested on RC. Do you think we can close this?

**Comment by arslanashraf7** [comment]
Yes, Closing this.
