### ISSUE TITLE
Flexible Pricing: Resetting two Flexible Pricing Requests from the same user will spam their email

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mitxonline#780]
### Steps to Reproduce
This was tested both locally and through RC.
- Create two Flexible Pricing Requests for a single user (I tested this using a single Course for both Flex Price Requests)
- Go to https://rc.mitxonline.mit.edu/staff-dashboard/flexible_pricing
- Reset both Flexible Pricing Requests for the user before the undo pop-up disappears.

### Expected Behavior

The user should receive a single email for each reset action which took place.

### Actual Behavior

The user's email will receive 6 to 8, maybe more, emails informing them of the status change.

**Comment by asadali145** [comment]
I think this one is invalid. A user cannot have multiple requests for a single course. So, you cannot reset multiple requests.
@collinpreston Can we please verify this one again?

**Comment by asadali145** [comment]
Sorry my bad, Just faced this issue locally.
