### ISSUE TITLE
Set up Cybersource in production 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#789]
As an admin, I'd like to confirm that all the necessary cybserource keys are already deployed to production. 

There are 8 keys in RC, and there are 8 keys defined in https://github.com/mitodl/salt-ops/blob/4f799a2ed463f6bf41a0566aafba93a7a67a466a/pillar/heroku/mitxonline.sls#L81-L88 but I don't know if they have the correct values in Vault. 

Some additional steps that we will need to do for production:

- [x] A new Cybersource secure acceptance profile needs to be created. Some specific things we discovered need to be configured in particular ways, besides whatever finance would typically configure (i.e. payment settings) are:
   - **Note:** for any settings changes, you typically need to click a "Save" button on that tab and then click "Promote" once your settings changes are ready
   - [x] Payment Form:
     - [x] Enable Billing Information
     - [x] Enable the following fields on the form and mark them required:
       - First Name
       - Last Name
       - Street Address 1
       - City
       - State (US/Canada)
       - State (Other World States)
       - Country
       - Email
     - [x] Notifications:
       - [x] Enable Merchant POST URL
       - [x] Set the url to `https://<HOSTNAME>/api/checkout/result/`, filling in the production hostname
- [x] Configure MITx Online:
  - From the new profile above, collect the following values and set in vault:
    - [x]  `MITOL_PAYMENT_GATEWAY_CYBERSOURCE_PROFILE_ID`:
      - This is the profile's ID, it can be seen if you view/edit the profile in the top left corner.
      - Saltops definition: https://github.com/mitodl/salt-ops/blob/main/pillar/heroku/mitxonline.sls#L85
    - [x]  `MITOL_PAYMENT_GATEWAY_CYBERSOURCE_ACCESS_KEY`:
      - The profile's access key. It's likely IS&T will need to get this value for you.
      - Saltops definition: https://github.com/mitodl/salt-ops/blob/main/pillar/heroku/mitxonline.sls#L84
    - [x]  `MITOL_PAYMENT_GATEWAY_CYBERSOURCE_SECURITY_KEY`:
      - The profile's security key. It's likely IS&T will need to get this value for you.
      - Saltops definition: https://github.com/mitodl/salt-ops/blob/main/pillar/heroku/mitxonline.sls#L88
    - [x] The `MITOL_PAYMENT_GATEWAY_CYBERSOURCE_MERCHANT_*` variables defined in pillar also need to be populated, but these should be the same values we use in other production environments (e.g. MicroMasters)

**Comment by shaidar** [comment]
Created profile with the settings listed in this issue, but was unable to promote/activate it as it requires an active security key. Will reach out to IS&T for that.

**Comment by pdpinch** [comment]
@shaidar I'm able to promote the profile now. Does that mean that you have all the security keys that you need? We'd like to try turning this on for one test course in production asap.

**Comment by pdpinch** [comment]
We tried setting this up on production on Wednesday 9/14, but it seems like we're missing some keys from IS&T.

**Comment by shaidar** [comment]
This should be all set on production now.
