### ISSUE TITLE
Courseruns need upgrade deadlines

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#792]
We can't allow users to pay for a course after the upgrade deadline set in open edX, because the enrollment will fail. 

As a course team member, I want to set an upgrade deadline for instructor-paced courses, so that learners don't pay for courses that they cannot pass. 

As a marketing team member, I want to know the upgrade deadline so I can motivate learners to pay for a course, "before time runs out"  

#### Acceptance Criteria:

- [ ] Add an upgrade deadline to courseruns
- [ ] don't allow payments after the upgrade deadline has passed (because they are going to fail) 
- [ ] ~synchronize the upgrade deadline from open edX to the mitxonline application~

#### Out of scope from this ticket (Based on comments)
- [ ] synchronize the upgrade deadline from open edX to the mitxonline application (See https://github.com/mitodl/mitxonline/issues/842)

**Comment by arslanashraf7** [comment]
A few questions/updates that I wanted to share/ask while working on this:

>don't allow payments after the upgrade deadline has passed (because they are going to fail)

Is there any behavior specified for this on the frontend side, e.g. if a course run upgrade deadline has passed?

1. (Not enrolled) Will we show enroll button? Should we allow free enrollments?
2. (Enrolled) We should hide `Get Certificate` button from everywhere. (Course Details page, Dashboard page)
3. If a user has multiple products and for some of them the `Upgrade Deadline` passed, should we not show those products on the cart or just remove them from the cart?

>synchronize the upgrade deadline from open edX to the mitxonline application

I tried to look around MIcromasters and MITxPRO for the usage of `Upgrade Deadline`, [MicroMasters has it](https://github.com/mitodl/micromasters/blob/master/courses/models.py#L227), but I'm not sure if we are syncing upgrade deadline with edX there?

In xPRO we use course detail API to sync some course attributes with edX e.g, Name, Enrollment start/end, etc. https://github.com/mitodl/mitxpro/blob/master/courses/utils.py#L271-L275.

I suppose when we say `Upgrade Deadline` we are talking about the field we set while creating `Verified` Course Mode in edX ?

The thing is the [Course Detail API from edX](https://courses.edx.org/api-docs/#/courses/courses_v1_courses_read) doesn't provide the `Upgrade Deadline` that we set for a Verified `Course Mode`. If we want to sync, we will need to use [Course Mode Details API from edX](https://courses.edx.org/api-docs/#/course_modes/course_modes_v1_courses_read) along with course details so we sync `Upgrade Deadline`.  However, We do have the Course end date in edX course detail API but I suppose we can't use that as the upgrade deadline. 

@pdpinch FYI, Could you share your thoughts ?

**Comment by pdpinch** [comment]
> (Not enrolled) Will we show enroll button? Should we allow free enrollments? 

The enroll button should be controlled by the start and end enrollment dates on the course run. Yes, on mitxonline we allow free enrollments (unlike xPRO).

**Comment by pdpinch** [comment]
> (Enrolled) We should hide Get Certificate button from everywhere. (Course Details page, Dashboard page)

Yes, this is the most important UI requirement for this issue. 

> If a user has multiple products and for some of them the Upgrade Deadline passed, should we not show those products on the cart or just remove them from the cart?

It's OK to show the product in the cart, but we should not allow the user to move ahead to cybersource. The most important thing is that we don't take payments for verified mode enrollments that are not available.

**Comment by pdpinch** [comment]
Regarding synchronizing the upgrade deadline, let's leave that for a separate issue. I can take care of it manually for now (which is what we do in micromasters).

**Comment by arslanashraf7** [comment]
> Regarding synchronizing the upgrade deadline, let's leave that for a separate issue. I can take care of it manually for now (which is what we do in micromasters).

Created a separate ticket for this https://github.com/mitodl/mitxonline/issues/842.

**Comment by arslanashraf7** [comment]
Closed via #842
