### ISSUE TITLE
Add embedded video to product detail page

### ISSUE THREAD

**Issue by gsidebo** [mitodl/mitxonline#80]
Related: #32 
Design: https://projects.invisionapp.com/d/main/#/console/21535972/455477372/preview

**Acceptance criteria:**
- Field added to product detail page CMS class for entering an embedded video URL
- If a video URL has been entered for some product page, the video can be played directly on the page
- If a video URL has not been entered for some product page, nothing is shown in that section of the page

**Implementation details:**
- Every one of our initial set of courses has a video in edX that we should be able to use. Get in touch with Peter to figure out which video platform we will be using, and what video URLs we might be able to use for testing.

**Open questions:**
- Do we need to support more than one video platform (e.g.: both Vimeo and Youtube)?

**Comment by pdpinch** [comment]
It looks like we only need YouTube for now. In the future, we may need to support HLS video from Cloudfront. For this reason, I think video.js would be a good player choice. 

Here are the legacy video URLs we need to support for October 1:

14.100x Microeconomics: https://www.youtube.com/watch?v=VpLHS0MhiXM
14.310x Data Analysis for Social Scientists: https://youtu.be/YpdhardLz1k
14.750x Political Economy and Economic Development MITx: https://youtu.be/kdGSqbnmfJU
14.73x The Challenges of Global Poverty: https://youtu.be/894VcOqcPYM
JPAL102x Designing and Running Randomized Evaluations:  https://youtu.be/GbQ1

**Comment by Wassaf-Shahzad** [comment]
@pdpinch  I have a few questions regarding this issue
Should youtube videos render the youtube playernusing iframe as done in MITxPro or should we use video.js ?
Incase  of vide.js, we will need videojs-youtube plugin to support youtube videos.

**Comment by pdpinch** [comment]
We discussed on Slack, but I'm noting the results here: we will use video.js with the videojs-youtube plugin.
