### ISSUE TITLE
"Need financial assistance?" link on the checkout page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#811]
When we did issue #677 / PR #764 it looks like we overlooked the last item on the list, possibly because I forgot to link to InVision. 

4. "Need financial assistance?" link on the checkout page

#### Designs and Mockups

https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/462885073/preview 

note the link in the top right

#### Acceptance Criteria:

- [ ] The link should only be available when the course in question offers flexible pricing / financial assistance
- [ ] The link should not display if the learner has already been approved for financial assistance
- [ ] The link should go to the appropriate flexible pricing form for the current course

**Comment by collinpreston** [comment]
@pdpinch can you please verify if these screenshots meet the requirements?
![Screen Shot 2022-08-15 at 12 20 36](https://user-images.githubusercontent.com/8311573/184674463-8152aedd-9d9b-4876-976b-e21298070b14.png)
![Screen Shot 2022-08-15 at 12 20 30](https://user-images.githubusercontent.com/8311573/184674465-81e1096e-625d-41cd-bb6b-bf539a08ce27.png)
![Screen Shot 2022-08-15 at 12 20 21](https://user-images.githubusercontent.com/8311573/184674467-86a307d3-a4c5-4004-96ba-6fc4f17526e9.png)

**Comment by pdpinch** [comment]
It's not a blocker, but in the mobile view:

<img width="50%" src="https://user-images.githubusercontent.com/8311573/184674465-81e1096e-625d-41cd-bb6b-bf539a08ce27.png">

Why does the "need financial assistance link?" move after the "Help and FAQ" ? 

In any case, can it be right aligned?
