### ISSUE TITLE
Refunds: Update the order lookup for refunds to use the new `reference_number` field

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#816]
Blocked by #808 

We've previously added ( https://github.com/mitodl/mitxonline/pull/808 ) a `reference_number` to `Order` to be able to disambiguate MicroMasters orders from MITx Online ones given that the primary keys will overlap and also that the MicroMasters orders will actually get different primary keys when they're imported anyway.

When learners contact support for a refund, the number they'll end up providing for MicroMasters orders won't be currently matched using the current strategy of looking up the numeric primary key.

To accommodate this, we want to update the current lookup to use the full reference number (e.g. MM-prod-5830, mitxonline-production-85474, etc)

**Comment by pdpinch** [comment]
I don't think this is blocked anymore.
