### ISSUE TITLE
Bug: google sheet refund celery task isn't running

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#828]
The validation we have in place to verify if the feature is configured is a little too aggressive and is causing itself to not run even though RC is correctly configured.

See https://sentry.io/organizations/mit-office-of-digital-learning/issues/3492734864/?project=5864687&query=&statsPeriod=14d

**Comment by pdpinch** [comment]
@annagav what's going on with this issue?

**Comment by annagav** [comment]
This Sentry error had been resolved
