### ISSUE TITLE
Dashboard reloads when clicking program title

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#829]
### Steps to Reproduce

1. On RC, enroll in a course with a program (free enrollment is fine; any DEDP course will do)
2. go to /dashboard
3. Click on the program title on the program card, e.g. "Data, Economics and Development Policy" 

### Expected Behavior

- I was expecting the program drawer to open 

### Actual Behavior

- The page reloads

**Comment by asadali145** [comment]
@jkachel Is it intentional to open a new tab by clicking on the Program title?
