### ISSUE TITLE
Flexible Pricing: custom email when denying a request 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#841]
As a course admin reviewing flexible pricing requests, I need to customize the email from when denying a request, so I can give the requestor instructions on how to correct their errors. 

It would be nice if the template for the email could reflect the justification for denying the request (ask @pdpinch for text).

#### Designs and Mockups

On MicroMasters, we present a form like this: 

<img width="975" alt="184567441-5c303f5b-0e09-4081-9f27-1b8c60bc2874" src="https://user-images.githubusercontent.com/430126/184567978-327a074e-0c78-4f1a-975d-f2e0ecc5a834.png">

On mitxonline, it would make sense to add the email response fields to the pop-up that appears when denying a request, i.e. 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/430126/184567517-508657bf-7c0b-4cad-9060-24827b3a0ebc.png">

We don't need to repeat the fields in the pop-up that are visible in the list view. 

#### Acceptance Criteria:

- [ ] Always send an email when denying a request
- [ ] Allow the admin reviewing the request to customize the email subject and body
- [ ] validate that the email subject and body are not empty

#### Related issues

- Allow admin to reset a request at the same time as denying it.

**Comment by asadali145** [comment]
> It would be nice if the template for the email could reflect the justification for denying the request (ask @pdpinch for text).
@pdpinch Can you please provide the text?
