### ISSUE TITLE
As a user, if I click on the course card on the Cart page, I should be navigated back to the course page.

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mitxonline#849]
### Steps to Reproduce

1. Add a course to a user's cart
2. View the cart and click on the course title from the course card (show in the screenshot below)
![Screen Shot 2022-08-15 at 16 49 23](https://user-images.githubusercontent.com/8311573/184716337-707ace43-a0e3-4abf-bd16-5ab0e270091e.png)

### Expected Behavior

The user will be navigated back to the Course's main page.

### Actual Behavior

The user is navigate to the Cart page (which they are already viewing).

**Comment by asadali145** [comment]
This issue is fixed under https://github.com/mitodl/mitxonline/pull/877 by @collinpreston. Closing this issue.
