### ISSUE TITLE
As a user with approved Flexible Pricing, when I click the "get certificate at reduced rate" button I should be navigated to the Cart

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mitxonline#850]
### Steps to Reproduce

1. Login as a user
2. Submit a flexible pricing request
3. Approve the flexible pricing request from step 2.
4. Navigate back to the flexible pricing request form from step 2.
5. Click on the button, Get certificate at reduced rate, shown in the screenshot below.
![Screen Shot 2022-08-15 at 16 50 46](https://user-images.githubusercontent.com/8311573/184716765-9d1daf55-a55b-4603-9595-d1bc1432a598.png)

### Expected Behavior

The user is navigated to the Cart which contains the course.

### Actual Behavior

The user is navigated to the main `mitxonline` page.

**Comment by asadali145** [comment]
Do we just want to redirect to the cart or do we want to add the product to the cart as well?
@pdpinch @collinpreston

**Comment by collinpreston** [comment]
This issue is being addressed through https://github.com/mitodl/mitxonline/pull/856 and was also logged as https://github.com/mitodl/mitxonline/issues/793.

@asadali145
