### ISSUE TITLE
Financial Assistance Request Approval Email raises ValueError: Cannot query "program-v1:MITx+DEDP | DEDP": Must be "Course" instance.

### ISSUE THREAD

**Issue by asadali145** [mitodl/mitxonline#852]
### Steps to Reproduce

- Submit financial assistance request for a course that belongs to a program i.e. DEDP.
- Visit flexible prices in the staff dashboard and approve the request.
- An exception will be raised: `ValueError: Cannot query "program-v1:MITx+DEDP | DEDP": Must be "Course" instance.`

### Expected Behavior

- Financial assistance request approval email is sent to the user.

### Actual Behavior

- Raises: `ValueError: Cannot query "program-v1:MITx+DEDP | DEDP": Must be "Course" instance.`

### Stacktrace

> File "/app/flexiblepricing/tasks.py", line 50, in notify_flexible_price_status_change_email
> celery_1    |     Sends email notifications when the flexible price status changes.
> celery_1    |   File "/app/flexiblepricing/mail_api.py", line 41, in generate_flexible_price_email
> celery_1    |     courserun = CourseRun.objects.filter(
> celery_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
> celery_1    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
> celery_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
> celery_1    |     return self._filter_or_exclude(False, args, kwargs)
> celery_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
> celery_1    |     clone._filter_or_exclude_inplace(negate, args, kwargs)
> celery_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
> celery_1    |     self._query.add_q(Q(*args, **kwargs))
> celery_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1416, in add_q
> celery_1    |     clause, _ = self._add_q(q_object, self.used_aliases)
> celery_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
> celery_1    |     child_clause, needed_inner = self.build_filter(
> celery_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1343, in build_filter
> celery_1    |     self.check_related_objects(join_info.final_field, value, join_info.opts)
> celery_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1170, in check_related_objects
> celery_1    |     self.check_query_object_type(value, opts, field)
> celery_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1151, in check_query_object_type
> celery_1    |     raise ValueError(
> celery_1    | ValueError: Cannot query "program-v1:MITx+DEDP | DEDP": Must be "Course" instance.

### Screenshot or Screencast
<img width="1419" alt="Screenshot 2022-08-16 at 1 39 16 PM" src="https://user-images.githubusercontent.com/52656433/184841492-529466a7-1b91-478b-ac6b-30526c50fff4.png">

**Comment by asadali145** [comment]
The issue is with the below code snippet. For the program courses, we add financial assistance requests for the program and when a request is approved we are trying to find `CourseRun` using `courseware_object` but courseware_object is a Program. So, we cannot match a `Program` type with a `Course` type.

```
if flexible_price.status == FlexiblePriceStatus.APPROVED:
    courserun = CourseRun.objects.filter(
        course=flexible_price.courseware_object
    ).first()
    product = Product.objects.get(object_id=courserun.id, is_active=True)
    price = DiscountType.get_discounted_price(
        [flexible_price.tier.discount], product
    )
    message = FLEXIBLE_PRICE_EMAIL_APPROVAL_MESSAGE.format(
        program_name=flexible_price.courseware_object.title, price=price
    )
    subject = FLEXIBLE_PRICE_EMAIL_APPROVAL_SUBJECT.format(
        program_name=flexible_price.courseware_object.title
    )
```

**Comment by jkachel** [comment]
I've got this updated locally to pull the discount amount, which does resolve the issue. I do need some text for the message, though. @pdpinch can you provide this?

The current text is this:

```
After reviewing your income documentation, the ${program_name} MITxOnline team has determined
that your personalized course price is ${price}.


You can pay for MITxOnline courses through the MITxOnline portal
(https://MITxOnline.mit.edu/dashboard). All coursework will be conducted on mitxonline.mit.edu
```

(where price is the product price and program_name is the name of the title of the courseware object). My temp fix now has this for updated text:

```
After reviewing your income documentation, the ${program_name} MITxOnline team has determined
that your personalized course discount is ${discount}.


You can pay for MITxOnline courses through the MITxOnline portal
(https://MITxOnline.mit.edu/dashboard). All coursework will be conducted on mitxonline.mit.edu
```

Further, discount is either `xx% off`, `$xx off`, or `$xx fixed price` (depending on the discount type). All of that can be changed.

**Comment by pdpinch** [comment]
It would have easier to comment on a PR, but here's what I think it should say:

```
After reviewing your income documentation, the ${program_name or course name} team has award you financial 
assistance in the amount of ${discount}.


You can pay for MITx Online courses through the MITx Online portal
(https://MITxOnline.mit.edu/dashboard). All coursework will be conducted on mitxonline.mit.edu
```

Where `${discount}` is one of `xx% off`, `$xx off` or `a fixed price of $xx`
