### ISSUE TITLE
Additional fields for course/programs API endpoints

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mitxonline#857]
The open-discussions ETL processors for ingesting MITX Online courses and programs would benefit from having a few additional attributes included in the API endpoints: price, url (missing from programs), and description

#### Designs
Add the following attributes to the course/program API response (via relevant serializers).

- `current_price`
- `page_url` (for programs)
- `description` (derived from CMS page?)

**Comment by jkachel** [comment]
Does the `description` field need to be stripped of HTML? It's a rich text field in the CMS.

**Comment by mbertrand** [comment]
Stripping out the HTML would be good.
