### ISSUE TITLE
Add edx-git-auto-export to mitxonline deployment

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#86]
As a course administrator, I'd like to manage the content for MITx Online courses via Github to help with versioning.

#### Acceptance Criteria:

- [x] Add https://github.com/mitodl/edx-git-auto-export to our mitxonline deployment
- [x] Configure a course ([studio => advanced settings](https://github.com/mitodl/edx-git-auto-export)) to use edx-git-auto-export to test

**Comment by pdpinch** [comment]
I believe this has been deployed to QA. It needs to be tested before we deploy to production.

**Comment by briangrossman** [comment]
Peter did a test an confirmed that this is working. 👍
