### ISSUE TITLE
Checkout: standardize course display 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#871]
The course card on the checkout page isn't very user friendly. It would be good if it could be more similar to the dashboard. 

#### Designs and Mockups

current Checkout page: 
- no course number; instead, a full course id 
- no label on the date
- no link to the course info

<img width="751" alt="image" src="https://user-images.githubusercontent.com/430126/185461262-061297d5-0c70-46b7-ab0d-d4b3a595e3e7.png">

current dashboard course card:
- course number
- "Starts" plus start date 
- link to "course details" 

<img width="727" alt="image" src="https://user-images.githubusercontent.com/430126/185461126-e735b39e-c4ea-4d85-90c6-f15c65cfe980.png">

#### Acceptance Criteria:

- [ ] display course number
- [ ] label the course date. Could be "starts" or "active"
- [ ] link to the course about page 

#### related issue 

- might want to combine this with another issue about the checkout page: #872

**Comment by collinpreston** [comment]
@pdpinch clicking the course title (bold red text) and clicking "Course details" from the Dashboard appears to load the same page.  There is currently a PR to fix the course title link for the course in a cart, but should I also add the "Course details" link if it navigates to the same location?

**Comment by collinpreston** [comment]
@pdpinch, this PR here (https://github.com/mitodl/mitxonline/pull/853) adds functionality for when a user clicks "Test External Course" from the Cart, they will be navigated to a new tab showing the course details (`http://mitxonline.odl.local:8013/courses/<course_URL>/`).  

Should that PR (853) actually redirect the user to `courses-qa.mitxonline.mit.edu`?  This is what clicking "Test External Course" from the Dashboard is doing.  
Or, is that other PR (853) correctly navigating the user to the course details page (`http://mitxonline.odl.local:8013/courses/<course_URL>/`)?
