### ISSUE TITLE
Bug: inactive products are added to the cart

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#873]
It looks like even though we now enforce only one active product per courseware when the `/cart/add?course_id=X` url is used it will add _all_ products to the cart regardless of their active status.

The relevant code is here: https://github.com/mitodl/mitxonline/blob/main/ecommerce/views/v0/__init__.py#L520-L530

We should probably solve this by updating `ProductsQuerySet` to filter to active record only. That should address the query on `Product` in the above code and also prevent an issue like this in the future. Some areas of code may need to be updated to use the `Product.all_objects` manager because there may be some usages of `Product.objects` that depend on that return all products. Django-admin is almost definitely one of those but as part of fixing this other usages should be investigated too.

**Comment by arslanashraf7** [comment]
Just mentioning for anyone reading through this,

As a result of [the fix PR for this](https://github.com/mitodl/mitxonline/pull/874) the other visible issues that were fixed except for the mentioned `/cart/add?course_id=X` issue:

1. The same behavior was applicable for product Ids too e.g. if we hit `/cart/add?product_id=X` the inactive product was getting added to the cart.
2. On the Course detail Page and Dashboard Page we'd see `Get Certificate` button in an enrolled free course, the associated PR also fixes this issue.

**Comment by arslanashraf7** [comment]
Closed via #874
