### ISSUE TITLE
Dashboard design update

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#884]
Course and program cards on the dashboard are currently a little busy and confusing. Also, the mobile dashboard isn't working well. 

#### Designs and Mockups

Dashboard with programs: https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468431706/preview?scrollOffset=0
Dashboard with expanded card for upsell: https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/469158352/preview?scrollOffset=1015
Program Drawer with upsell (scroll down): https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468431707/preview?scrollOffset=0
Mobile Program Drawer: https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/469158353/preview?scrollOffset=996

#### Acceptance Criteria:

- [x] Don't display "enrolled in free course" or "Enrolled in certificate track" labels on program cards
- [x] Link the program title to opening the program drawer
- [x] Don't display the full program id on the program card. Instead of `program-v1:MITx+DEDP |` it should display just `DEDP`
- [ ] display a default image if there isn't a custom one in the CMS, to keep the layout simple 
- [x] When the user can upgrade, expand the card to include an upgrade message and a "Get Certificate" button. If there is no upgrade option or the deadline has passed, hide this section. The text can be "Upgrade today and, upon passing, receive your certificate signed by MIT faculty to highlight the knowledge and skills you've gained from this MITx course." with upgrade today being a link. 
- [x] in mobile, the program drawer should slide out to cover all but 8px of the underlying dashboard, so the user can interact. There should be an "X" button to close the drawer in the top right

**Comment by collinpreston** [comment]
@pdpinch, so I am just about wrapping up development on this.  
I believe a couple of the items on your list already exist:
1. display default image.  This is controlled by the `DEFAULT_COURSE_IMG_PATH` constant which is set to `images/mit-dome.png` by default.
2. Link the program title to opening the program drawer.  Testing locally and on RC, this seems to already be functional.
