### ISSUE TITLE
Versioning of certificate templates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#887]
As a course team member, I'd like to update the signatories on a course certificate, and have it only affect new course certificates created in the future. In particular, I need to replace the outgoing VP's signature with the new VP's signature. 

See https://github.com/mitodl/hq/discussions/131 for a discussion on how to implement this 

#### Acceptance Criteria:

- [ ] write a brief description of the plan
   - [ ] how will migrations be handled?
   - [ ] how will existing PageVersions be addressed?
- [ ] include testing instructions that support changes to the template, learner views and anonymous views.

**Comment by rhysyngsun** [comment]
Blocking #705
