### ISSUE TITLE
Bug: Course purchase order error on 100% Discount

### ISSUE THREAD

**Issue by aliraza-abbasi** [mitodl/mitxonline#895]
### Steps to Reproduce

Apply 100% discount coupon and click on `Place your order`

### Stacktrace

- First: `File "/app/./ecommerce/views/v0/__init__.py", line 532, in get
    checkout_payload = api.generate_checkout_payload(request)
  File "/app/./ecommerce/api.py", line 127, in generate_checkout_payload
    USER_MSG_TYPE_PAYMENT_ACCEPTED_NOVALUE,
NameError: name 'USER_MSG_TYPE_PAYMENT_ACCEPTED_NOVALUE' is not defined`

- Second: This error comes up when USER_MSG_TYPE_PAYMENT_ACCEPTED_NOVALUE is imported from constants `File "/app/./ecommerce/views/v0/__init__.py", line 532, in get
    checkout_payload = api.generate_checkout_payload(request)
  File "/app/./ecommerce/api.py", line 124, in generate_checkout_payload
    "response": fulfill_completed_order(
TypeError: fulfill_completed_order() takes 3 positional arguments but 4 were given`

- Third: This error comes up when USER_MSG_TYPE_PAYMENT_ACCEPTED_NOVALUE commented in fulfill_completed_order() argument. Also the user got enrolled in the course but 500 Internal Server Error page is displayed. `Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view ecommerce.views.v0.CheckoutInterstitialView didn't return an HttpResponse object. It returned None instead.`

**Comment by pdpinch** [comment]
@arslanashraf7 can this be closed?

**Comment by arslanashraf7** [comment]
Yes, Closing it via https://github.com/mitodl/mitxonline/pull/899
