### ISSUE TITLE
don't show overflow ⋮ menu on program card

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#909]
### Steps to Reproduce

1. Enroll in a course that is part of a program
2. Visit /dashboard 
3. Click on the ⋮ menu on the program card 

### Expected Behavior

- I don't really expect an ⋮ menu on the program card at all

### Actual Behavior

- Clicking the ⋮ menu opens the program drawer

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/430126/187468345-9df8f615-8de7-4135-a0b5-8f0305e7a7c1.png)

**Comment by collinpreston** [comment]
I will do this along with https://github.com/mitodl/mitxonline/issues/905

**Comment by Ferdi** [comment]
That could be a useful UX element in the future. 

Also

![Screen Shot 2022-08-30 at 12 16 47 PM](https://user-images.githubusercontent.com/125561/187488480-dc54f55f-4bc4-455b-b7b4-227db0cfc0ee.png)

**Comment by Ferdi** [comment]
oh, nvm if the issue is only about *program* cards

**Comment by collinpreston** [comment]
Completed with https://github.com/mitodl/mitxonline/issues/905
