### ISSUE TITLE
Styling and layout fixes

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#91]
#### Designs and Mockups

[MITx Online - Feedback - Rnd1.pdf](https://github.com/mitodl/mitxonline/files/6984531/MITx.Online.-.Feedback.-.Rnd1.pdf)

#### Acceptance Criteria:

- [x] fix margins and spacing in the footer
- [x] set page background to white on course detail page; set course info box background to grey
- [x] fix header spacing on course detail page
- [x] fix header spacing on dashboard

**Comment by arslanashraf7** [comment]
Closed via #98
