### ISSUE TITLE
Enrolling in a course does not necessary means i'm interested in a program

### ISSUE THREAD

**Issue by Ferdi** [mitodl/mitxonline#912]
### Steps to Reproduce

Enroll in a DEDP course (e.g. Political Economy and Economic Development)

### Expected Behavior

See the course listed in my dashboard

### Actual Behavior

The course is not listed.  Its listed only in the list of courses for the program that particular course belongs to.

I think we should list it as a course in the list of courses (because that's what my intention was as a user) and in the drawer (to say that "btw, this course is part of this program, in case you were interested")

### Screenshot or Screencast

![Screen Shot 2022-08-30 at 12 53 32 PM](https://user-images.githubusercontent.com/125561/187496454-b0358c13-f627-4e24-add8-c2ecd5179273.png)
![Screen Shot 2022-08-30 at 12 53 48 PM](https://user-images.githubusercontent.com/125561/187496456-8b209f92-eeda-4542-8980-ef2a910675c8.png)

**Comment by rhysyngsun** [comment]
Related to this, making this change will also impact our need to address #703, which we'd pushed out a bit because the current behavior addressed that well enough for the short term.

**Comment by pdpinch** [comment]
Also related, in #915 we want to put the program card and drawer behind a feature flag.

**Comment by pdpinch** [comment]
We redesigned this with one dashboard for course enrollments and another dashboard for program enrollments.
