### ISSUE TITLE
Program drawer obscures notifications (for example, on successful unenrollment)

### ISSUE THREAD

**Issue by jkachel** [mitodl/mitxonline#921]
### Steps to Reproduce

1. Enroll in at least one course as audit that is in a program. 
2. Navigate to the dashboard and open the program drawer.
3. Attempt to unenroll from the course.

### Expected Behavior

The unenrollment notification should appear and be visible.

### Actual Behavior

The unenrollment notification is not visible. (It does appear but the program drawer is on top of it, so it's obscured - perhaps we should close the drawer?) 

### Screenshot or Screencast

You can sort of see the green sliver on the left side - that's the unenrollment notification for Designing and Running Randomized Evaluations, which I triggered from the drawer.

![image](https://user-images.githubusercontent.com/945611/187732037-7f2350d3-32f8-4007-b766-9a86385710f4.png)

**Comment by rachellougee** [comment]
I think this is the same issue as https://github.com/mitodl/mitxonline/issues/910

**Comment by jkachel** [comment]
Closing this - it's covered as part of #910.
