### ISSUE TITLE
Filter flexbile pricing admin by course/program 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#950]
As a member of the course team who is reviewing flexible pricing requests, I need to filter the list to only see a course/program that is relevant to me. 

#### Acceptance Criteria:

- [ ] On `/staff-dashboard/flexible_pricing`,add a drop-down for choosing from existing courses/programs with financial aid requests

**Comment by rachellougee** [comment]
@pdpinch Just to clarify, Is this referring to Django admin https://rc.mitxonline.mit.edu/admin/flexiblepricing/flexibleprice/
or dashboard https://rc.mitxonline.mit.edu/staff-dashboard/flexible_pricing?
