### ISSUE TITLE
prevent learners from accessing the open edX dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#951]
As a learner, I'm confused by having two different dashboards, one in mitxonline and one in open edX, with overlapping functions. 

The mitxonline dashboard is preferred, because mitxonline is the source of truth for payments and certificates. 

As discussed in https://github.com/mitodl/hq/discussions/234#discussioncomment-3596333, we can hide the open edX dashboard behind a redirect. 

#### Acceptance Criteria:

- [ ] Redirect open edX's /dashboard to the corresponding mitxonline /dashboard 
- [ ] Open a PR in [ol-infrastructure ](https://github.com/mitodl/ol-infrastructure/blob/main/src/ol_infrastructure/applications/edxapp/__main__.py#L1282-L1415) to add an appropriate redirect in Fastly
- [ ] needs to work for RC site and for production 
- [ ] We will need to test this carefully on RC to make sure the redirect doesn't interfere with account creation or login.

**Comment by asadali145** [comment]
FYI @pdpinch

We can add redirects in edX using the Django Admin site.
To add a redirect a URL:

Visit admin/redirects/redirect/
Add old and new URLs.
Visit the old URL and it should redirect to the new URL.
Tested the following things and are working fine:

User Creation & Login.
Tried to access the URL directly.
Access from the User profile dropdown.

**Comment by pdpinch** [comment]
Have you tested this on RC asad? I tried creating a new account, and logging in and logging out. It seemed to work well to me. 

I'd like to try turning this on in production on Monday. Do you have any concerns? 

cc @mitodl/devops

**Comment by asadali145** [comment]
Yes, I have tested it, Looks good to me as well.

**Comment by pdpinch** [comment]
We made the settings in django admin in production.
