### ISSUE TITLE
generate a list of paid & enrolled legacy users to upgrade automatically

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#960]
As a legacy MicroMasters user who:

1. Is enrolled in a current MITx Online course (3T2022 or 1T2023)
2. has paid
3. has not used all my exam attempts , 

I need to be enrolled in the verified track of my course(s).

As a CS teammember, I'd like to be able to confirm for specific users that contact CS that this will happen.

#### Acceptance Criteria:

- [ ] generate a list of users (emails) and course runs that should be upgraded
- [ ] write a management command or similar for enrolling these users in their courses as verified 
- [ ] since users can enroll, and users can pay, between now and the launch of ecommerce, we will need to be able to run this more than once. 
- [ ] Since these users have paid on micromasters, and AR/Finance has already accounted for their payments, no special tracking is required. 

#### Related issues 

- [ ] test importing of grades into open edX  
- [ ] #961

**Comment by annagav** [comment]
@pdpinch Is the first checkbox, generating the list of users that satisfy all 3 points above must be generated as result of a management command on micromasters? I might have missed this but I don't believe we have any representation of users exam attempts in mitxonline.

**Comment by pdpinch** [comment]
It doesn't matter to me where we run it. I think @rhysyngsun agrees with you that it needs to be run on micromasters. 

Do note though, that I think there's an edge case with how we calculate exam authorizations on micromasters, https://github.com/mitodl/micromasters/issues/5219

**Comment by pdpinch** [comment]
We can write a management command in micromasters to 

1. find everyone who is authorized for the exam
2. upgrade learners with an _existing_ enrollment in mitxonline to verified

**Comment by pdpinch** [comment]
While we're doing this, we should also capture a list of all the users who are authorized but have _not_ enrolled, which can be used as an input to #

**Comment by annagav** [comment]
@pdpinch latter proposed condition is going to give very different result, then the original request on the issue. The second approach, does not involve any current enrollment information. Is that what we want?

**Comment by pdpinch** [comment]
Sorry to distract. I was thinking that the two lists were opposites of each other, and therefor easy to create at the same time. If that's not the case you can ignore for now and we'll have a follow-up for #961.
