### ISSUE TITLE
generate enrollment codes for paid but not enrolled legacy users

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#961]
As a legacy MicroMasters user who:

1. Is **not** enrolled in a current MITx Online course (3T2022 or 1T2023)
2. has paid
3. has not used all my exam attempts , 

I'd like to contact CS to request an enrollment code (100% off coupon code/discount) for future use. 

As a CS teammember, I'd like to be able to distribute enrollment codes for anyone who has paid, so they can enroll in a verified track and take the proctored exam when they like. 

#### Acceptance Criteria:

- [ ] generate a list of users (emails) and course runs of users who have paid, but aren't enrolled in a current run 
- [ ] write a management command or similar to create 100% off discounts on mitxoline for these learners
- [ ] since the codes will be distributed only on request, we could generate this once and not be concerned with updates. Any user paying between now and the launch of ecommerce is expected to enroll. 
- [ ] Since these users have paid on micromasters, and AR/Finance has already accounted for their payments. The discount codes are primarily a convenience for the user, but we should consider a naming scheme that makes it easy for AR to recognize and ignore them. 

#### Related issues 

- [ ] test importing of grades into open edX  
- [x] #960

**Comment by rhysyngsun** [comment]
Just to clarify, by enrollment codes do you mean coupons codes?

**Comment by pdpinch** [comment]
> by enrollment codes do you mean coupons codes

Yes. I updated the description to make it clearer that an enrollment code is a coupon code with a 100% discount for a course.

**Comment by pdpinch** [comment]
As an input to this, I expect we'll have a list of user emails and courses. I expect there will be a few hundred of these.
