### ISSUE TITLE
Certificates: display course dates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#967]
As a learner, I'd like my certificate to include dates so that when I share it, people will know when I took the course. 

#### Designs and Mockups

See, for example, https://rc.xpro.mit.edu/certificate/c9819368-40c6-4ff4-b53c-7241348a09de/

#### Acceptance Criteria:

- [ ] The dates should be displayed even if there are no CEUs set
- [ ] On course certificates, the dates should be the start and end dates of the course.

#### Out of Scope

- Program certificates should display the earliest start date of all the course runs the learner passed and the latest end date of all the course runs the learner passed

**Comment by pdpinch** [comment]
Question: instead of using the end date of the course, can the 2nd date be the date the certificate was created? (not updated)

**Comment by pdpinch** [comment]
@aliraza-abbasi we have the same issue on xPRO.

**Comment by aliraza-abbasi** [comment]
@pdpinch please let me know which issue you are facing. I’ll check it on priority

**Comment by pdpinch** [comment]
@aliraza-abbasi it can wait until morning, but it is important: https://github.com/mitodl/mitxpro/issues/2420

**Comment by aliraza-abbasi** [comment]
> Question: instead of using the end date of the course, can the 2nd date be the date the certificate was created? (not updated)
> 
> For context, I'm thinking about how to handle self-paced courses.

Let me know which date should be displayed on the certificate. I'll add it also can I get the design where to add the start and end date

**Comment by aliraza-abbasi** [comment]
> @aliraza-abbasi it can wait until morning, but it is important: [mitodl/mitxpro#2420](https://github.com/mitodl/mitxpro/issues/2420)

I'm looking into it
