### ISSUE TITLE
Set up and configure Sentry for MITx Online 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#97]
As an engineer, I'd like to be notified, and be able to trace, exceptions in the mitxonline application.

**Comment by arslanashraf7** [comment]
Update:

I've looked around it and it seems to me that most of the code changes are already in place inside the code along with the configuration keys e.g.`SENTRY_DSN` are placed on Heroku as well. I assume this key has been generated through the sentry console.

To further test/debug the sentry integration i might need access to the `mitxonline` project on [MIT ODL Sentry](https://sentry.io/settings/mit-office-of-digital-learning/projects/).

**Comment by briangrossman** [comment]
@arslanashraf7 
@blarghmatey gave the #arbisoft group permissions to the the mitxonline project on Sentry.

**Comment by arslanashraf7** [comment]
@pdpinch Although I could see the MITxOnline events on the sentry for `prod/rc/dev`. But, Since you added the DevOps label so you might better comment if we should close this ticket or there is something that still needs attention.
