### ISSUE TITLE
broken link to flexible pricing form on about page pop-up

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#975]
### Steps to Reproduce

1. go to https://rc.mitxonline.mit.edu/courses/course-v1:MITxT+8.01.1x/
2. click on "Enroll Now" button
3. click on [Need financial assistance?](https://rc.mitxonline.mit.edu/courses/test-page-for-mechanics-kinematics-dynamics/mitx-mooc-financial-assistance-request/) link in the pop-up.

### Expected Behavior

- link to https://rc.mitxonline.mit.edu/courses/course-v1:MITxT+8.01.1x/mitx-mooc-financial-assistance-request/

### Actual Behavior

- link to https://rc.mitxonline.mit.edu/courses/test-page-for-mechanics-kinematics-dynamics/mitx-mooc-financial-assistance-request/

**Comment by rachellougee** [comment]
@pdpinch Just to confirm if we should always use the link under Price in CMS? 

For example, in some DEDP courses like https://rc.mitxonline.mit.edu/courses/course-v1:MITx+14.310x/, the flexible pricing request currently links to https://rc.mitxonline.mit.edu/courses/course-v1:MITx+14.310x/data-analysis-for-social-scientists-request-flexible-pricing/. But the link provided in CMS (https://rc.mitxonline.mit.edu/cms/pages/10/edit/) is https://rc.mitxonline.mit.edu/programs/program-v1:MITx+DEDP/dedp-micromasters-program-financial-assistance-form/ (for the program). In this case, what's the correct link?

**Comment by pdpinch** [comment]
> @pdpinch <https://github.com/pdpinch> Just to confirm if we should always use the link under Price in CMS?
> 
Yes, that is my expectation, at least for now.
