### ISSUE TITLE
Allow enrollment in archived courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#977]
As a course team, I'd like to allow learners to enroll in my course even after it has ended, the same as on edx.org. (open edX displays the message "This course is now archived. The forums have been closed, and assignments are for self-study only." when the course is in this state)

As a learner, I'd like to be able to enroll in archived courses for self-study, even though I can't get a certificate. 

We want to keep this change as simple as possible in anticipation of the about page redesign that will be coming soon. 

#### Designs and Mockups

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/430126/190459775-b54a14c0-9bdc-4bc9-9e40-25277f30553a.png">

#### Acceptance Criteria:

- [ ] ~~display "archived" in the start date box **when there are no future runs available**~~
- [ ] display the start dates as normal: they will be in the past for courses in this state 
- [ ] display "free (no certificate available)" in the price box 
- [ ] when the user clicks enroll, enroll them immediately. Don't open the "upgrade" pop-up. 
- [ ] confirm that these courses are not purchasable in the checkout cart (because it is past the upgrade deadline)

**Comment by pdpinch** [comment]
An example of a an archived course's about page on edx.org: https://www.edx.org/course/making-science-and-engineering-pictures-a-practica

**Comment by collinpreston** [comment]
@pdpinch should this still have the 'on hold' label?

**Comment by pdpinch** [comment]
I should add an example course to this issue and highlight the specific dates that are relevant to this state.

**Comment by pdpinch** [comment]
An example course in production is https://mitxonline.mit.edu/courses/course-v1:MITxT+24.118x/

The most recent run of the course has an end date in the past, but no enrollment end date, so users should be allowed to enroll, even if it is too late to submit answers. 

It has an upgrade date in the past, so users cannot pay for a certificate.
