### ISSUE TITLE
Before Launch: create DEDP data mappings, for courses and financial assistance

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#994]
#### Acceptance Criteria:

- [x] Needs DEDP course ID mapping on production. On RC it's at https://rc.mitxonline.mit.edu/admin/micromasters_import/courseid/
- [x] Needs DEDP program Tier ID mapping on production. On RC it's at https://rc.mitxonline.mit.edu/admin/micromasters_import/programtierid/

#### related issues

Any other data mappings required?

**Comment by rachellougee** [comment]
@pdpinch Could you give me access to https://micromasters.mit.edu/admin so I can map the DEDP course from MicroMaster to MITxOnline?
For #2, it will need to wait until https://github.com/mitodl/mitxonline/issues/998 is done to map the program Tier ID from MicroMaster to MITxOnline as https://mitxonline.mit.edu/admin/flexiblepricing/flexiblepricetier/ is empty

**Comment by rachellougee** [comment]
I've mapped the DEDP courses and program tier IDs from MicroMaster to MITxOnline on production (I used our BI link to check courses and tiers from MicroMaster production)
https://mitxonline.mit.edu/admin/micromasters_import/courseid/ 

DEDP courses | MicroMaster | MITxOnline
-- | -- | --
Microeconomics | https://micromasters.mit.edu/admin/courses/course/8/change/| https://mitxonline.mit.edu/admin/courses/course/1/change/
Designing and Running Randomized Evaluations | https://micromasters.mit.edu/admin/courses/course/11/change/| https://mitxonline.mit.edu/admin/courses/course/2/change/
Data Analysis for Social Scientists | https://micromasters.mit.edu/admin/courses/course/9/change/| https://mitxonline.mit.edu/admin/courses/course/3/change/
The Challenges of Global Poverty | https://micromasters.mit.edu/admin/courses/course/7/change/| https://mitxonline.mit.edu/admin/courses/course/4/change/
Foundations of Development Policy | https://micromasters.mit.edu/admin/courses/course/10/change/| https://mitxonline.mit.edu/admin/courses/course/5/change/
Political Economy and Economic Development | https://micromasters.mit.edu/admin/courses/course/31/change/| https://mitxonline.mit.edu/admin/courses/course/6/change/
Good Economics for Hard Times | https://micromasters.mit.edu/admin/courses/course/38/change/| https://mitxonline.mit.edu/admin/courses/course/16/change/



https://mitxonline.mit.edu/admin/micromasters_import/programtierid/ 



Tier Program | MicroMaster (current) | MITxOnline (current)
-- | -- | --
Tier 1 | https://micromasters.mit.edu/admin/financialaid/tierprogram/9/change/ | https://mitxonline.mit.edu/admin/flexiblepricing/flexiblepricetier/1/change/
Tier 2 | https://micromasters.mit.edu/admin/financialaid/tierprogram/10/change/  | https://mitxonline.mit.edu/admin/flexiblepricing/flexiblepricetier/2/change/
Tier 3 | https://micromasters.mit.edu/admin/financialaid/tierprogram/11/change/  | https://mitxonline.mit.edu/admin/flexiblepricing/flexiblepricetier/3/change/
Tier 4 | https://micromasters.mit.edu/admin/financialaid/tierprogram/12/change/  | https://mitxonline.mit.edu/admin/flexiblepricing/flexiblepricetier/4/change/
